#
# .vale.ini
# mas
#
# Vale 3.23.0
#

StylesPath = .vale
MinAlertLevel = suggestion

[*.{md,swift}]
BasedOnStyles = mas
mas.Terms = NO

[{Specs,Temp}/*.md]
mas.Terms = YES

[CODE_OF_CONDUCT.md]
mas.EmDashes = NO

[Temp/terms.md]
mas.Terms = NO
TokenIgnores = (REJECTED:[^\n]*)

[Tests/MASTests/Commands/MASTests+MAS.{Lookup,Search}.swift]
BasedOnStyles =
