#!/bin/zsh -f
#
# Scripts/format
# mas
#
# Copyright © 2025 mas-cli. All rights reserved.
#
# Automatically formats & fixes style violations using various tools.
#
# Please keep in sync with Scripts/lint.
#

. "${0:A:h}/_setup-script"

print_notice '🧹 Formatting' "${@}"

ensure_command_available markdownlint-cli2 swiftformat swiftlint

export -r MAS_DISTRIBUTION=format

# shellcheck disable=SC2034
readonly -a files=("${(@0)"$(non_ignored_files)"}")

printf -- $'--> 🕊​ SwiftFormat\n'
script -q /dev/null swiftformat --strict --markdown-files format-strict "${(@M)files:#*.(md|swift)}" </dev/null |
	filter_swiftformat_output '0/\d+ files formatted\.\r'

printf -- $'--> 🦅 SwiftLint\n'
swiftlint --fix --quiet --reporter relative-path -- "${(@M)files:#*.swift}"

printf -- $'--> 📏 Layout\n'
Scripts/layout -f

printf -- $'--> 〽️ Markdown\n'
markdownlint-cli2 --fix -- "${(@)${(@M)files:#*.md}/#/:}"

printf -- $'--> 🚷 Non-Executables\n'
# shellcheck disable=SC1036,SC2206
readonly -a non_executables=(${^${(M)files:#Scripts/*}}(N^f+111))
if (("${#non_executables[@]}")); then
	chmod -vv a+x "${non_executables[@]}"
	exit 1
fi
