#!/bin/zsh -f
#
# Scripts/generate-token
# mas
#
# Copyright © 2025 mas-cli. All rights reserved.
#
# Generates a GitHub App installation access token for GitHub Workflows.
#

. "${0:A:h}/_setup-script"

readonly header=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9
payload="${${${$(
	printf '{"iss":%s,"iat":%s,"exp":%s}' "${TOKEN_APP_ID}" "$(("$(date +%s)" - 60))" "$(("$(date +%s)" + 540))" | base64
)//[=$'\n']}//+/-}//\//_}"
readonly payload

# shellcheck disable=SC2154
response="$(curl\
	-sSX POST\
	-H "Authorization: Bearer ${header}.${payload}.${${${$(printf %s "${header}.${payload}" |
		openssl dgst -sha256 -sign <(printf %s "${TOKEN_APP_PRIVATE_KEY}") | base64)//[=$'\n']}//+/-}//\//_}"\
	-H 'Accept: application/vnd.github+json'\
	"https://api.github.com/app/installations/${TOKEN_APP_INSTALLATION_ID}/access_tokens"
)" ||
{
	printf $'Error: Failed to contact GitHub API\n' >&2
	exit 1
}
readonly response
token="$(printf %s "${response}" | jq -r .token 2>/dev/null || true)"
readonly token
if [[ -z "${token}" || "${token}" = null ]]; then
	printf $'Error: Failed to parse installation token from:\n%s\n' "${response}" >&2
	exit 2
fi
printf %s "${token}"
