#!/bin/zsh -Ndefgku
#
# Scripts/generate-manual
# mas
#
# Copyright © 2025 mas-cli. All rights reserved.
#
# Generates man page.
#

. "${0:A:h}/_setup-script"

print_notice '📖 Generating man pages for' "${@}"

export -r MAS_DISTRIBUTION="${1:-}"

swift package generate-manual "${@:2}"
