#!/bin/zsh -f
#
# Scripts/package
# mas
#
# Copyright © 2025 mas-cli. All rights reserved.
#
# Builds .pkg installer.
#

. "${0:A:h}/_setup-script"

print_notice '📦 Packaging installer for' "${@}"

readonly build_folder=.build
readonly destination_folder="${build_folder}/destination"
readonly sbom_folder="${build_folder}/sboms"

for folder in "${destination_folder}" "${sbom_folder}"; do
	[[ -e "${folder}" ]] && trash "${folder}"
done

export MAS_DO_NOT_PRINT_NOTICE=
Scripts/build "${1:-}" -c release --sbom-spec cyclonedx --sbom-spec spdx --sbom-output-dir "${sbom_folder}" "${@:2}"
unset MAS_DO_NOT_PRINT_NOTICE

readonly installation_folder=/usr/local/opt/mas
readonly installation_staging_folder="${destination_folder}${installation_folder}"
readonly usr_local_bin_staging_folder="${destination_folder}/usr/local/bin"
readonly min_macos_version=15
version="$(Scripts/version)"
readonly version

swift package generate-manual

mkdir -p "${installation_staging_folder}/bin"
mkdir -p "${installation_staging_folder}/etc/bash_completion.d"
mkdir -p "${installation_staging_folder}/share/fish/vendor_completions.d"
mkdir -p "${installation_staging_folder}/share/man/man1"
mkdir -p "${usr_local_bin_staging_folder}"

cp -c "$(swift build -c release --show-bin-path "${@:2}")/mas" "${installation_staging_folder}/bin"
cp -c contrib/completion/mas.bash "${installation_staging_folder}/etc/bash_completion.d/mas"
cp -c contrib/completion/mas.fish "${installation_staging_folder}/share/fish/vendor_completions.d"
cp -c LICENSE README.md "${installation_staging_folder}"
cp -c "${build_folder}/plugins/GenerateManual/outputs/mas/mas.1" "${installation_staging_folder}/share/man/man1"

ln -fs "${installation_folder}/bin/mas" "${usr_local_bin_staging_folder}/mas"

archs=("${(s: :n)$(lipo -archs "${installation_staging_folder}/bin/mas")}")
# shellcheck disable=SC2034
readonly -a archs
# shellcheck disable=SC2034,SC2124
readonly package_path_prefix="${build_folder}/mas-${version//\//_}-${(j:-:)archs[@]}"

xattr -crs "${destination_folder}"

pkgbuild\
	--identifier io.github.mas-cli.mas\
	--install-location /\
	--version "${version}"\
	--min-os-version "${min_macos_version}"\
	--compression latest\
	--root "${destination_folder}"\
	"${build_folder}/mas.pkg"

# shellcheck disable=SC1036
productbuild\
	--distribution =(<<<\
'<?xml version="1.0" encoding="utf-8"?>
<installer-gui-script minSpecVersion="2">
	<title>mas</title>
	<options customize="never" require-scripts="false" hostArchitectures="'"${(j:,:)archs[@]}"'"/>
	<volume-check>
		<allowed-os-versions>
			<os-version min="'"${min_macos_version}"'"/>
		</allowed-os-versions>
	</volume-check>
	<choices-outline>
		<line choice="mas"/>
	</choices-outline>
	<choice id="mas" title="mas" visible="false">
		<pkg-ref id="mas">mas.pkg</pkg-ref>
	</choice>
</installer-gui-script>'
	)\
	--package-path "${build_folder}"\
	"${package_path_prefix}.pkg"

mv "${sbom_folder}"/cyclonedx*.json "${package_path_prefix}.cdx.json"
mv "${sbom_folder}"/spdx*.json "${package_path_prefix}.spdx.json"
