#!/bin/zsh -f
#
# Scripts/release-start
# mas
#
# Copyright © 2025 mas-cli. All rights reserved.
#
# Starts the release process by triggering workflow dispatch to create a GitHub draft release & bump tap formula.
#
# Usage: release-start [-f <path>] <version> <title> [<ref>]
#
# <version> must match the following zsh pattern:
#
# ^[[:digit:]]+(\.[[:digit:]]+)*(-(alpha|beta|rc)\.[[:digit:]]+)?$
#
# <title> may contain at most 64 characters, which cannot be control characters
#
# <ref> if optional ref supplied, must be on the main branch; defaults to main
#

. "${0:A:h}/_setup-script"

zmodload zsh/zutil
zparseopts -D -F -A option_value f:
readonly -A option_value

readonly version="${1}"
readonly title="${2}"
readonly ref="${3:-main}"
readonly formula_path="${option_value[-f]}"

export MAS_VERSION="${version}"
print_notice '🚀 Starting release for' "${@}"
unset MAS_VERSION
printf $'\n'

if [[ ! "${version}" =~ '^[[:digit:]]+(\.[[:digit:]]+)*(-(alpha|beta|rc)\.[[:digit:]]+)?$' ]]; then
	printf $'Error: %s is not a valid version\n' "${version}" >&2
	exit 1
fi

if (("${#title}" > 64)); then
	printf $'Error: Title \'%s\' contains more than 64 characters\n' "${(q)title}" >&2
	exit 2
fi

if [[ "${title}" =~ [[:cntrl:]] ]]; then
	printf $'Error: Title \'%s\' contains control characters\n' "${(q)title}" >&2
	exit 3
fi

# shellcheck disable=SC1027,SC1036,SC1072,SC1073
if [[ "${title}" = (' '*|*' ') ]]; then
	printf $'Error: Title \'%s\' begins or ends with a space\n' "${(q)title}" >&2
	exit 4
fi

read -r gh_repo default_branch default_branch_sha < <(
	gh repo view\
		--json nameWithOwner,defaultBranchRef\
		-q '.nameWithOwner + " " + .defaultBranchRef.name + " " + .defaultBranchRef.target.oid'
)
readonly gh_repo default_branch default_branch_sha

if ! git merge-base --is-ancestor "${ref}" "${default_branch_sha}"; then
	printf $'Error: %s is not on the %s/%s branch\n' "${ref}" "${gh_repo}" "${default_branch}" >&2
	exit 5
fi

if [[ -n "${formula_path}" && ! -f "${formula_path}" ]]; then
	printf $'Error: No file exists at \'%s\'\n' "${(q)formula_path}" >&2
	exit 6
fi

gh workflow run release-start.yaml\
	-f version="${version}"\
	-f title="${title}"\
	-f ref="${ref}"\
	${formula_path:+-F formula=@"${formula_path}"}
