#!/bin/zsh -f
#
# Scripts/release-start
# mas
#
# Copyright © 2025 mas-cli. All rights reserved.
#
# Starts the release process by creating & pushing a signed annotated version tag to the GitHub repo.
#
# Usage: release-start <version-tag-name> <version-title> [<version-ref>]
#
# <version-tag-name> must match the following zsh pattern:
#
# ^v[[:digit:]]+(\.[[:digit:]]+)*(-(alpha|beta|rc)\.[[:digit:]]+)?$
#
# <version-title> may contain at most 64 characters, which cannot be control characters
#
# <version-ref> if optional value supplied, must be on the main branch; defaults to HEAD
#

. "${0:A:h}/_setup-script"

readonly tag="${1}"
readonly title="${2}"
readonly ref="${3:-HEAD}"

export MAS_VERSION="${tag#v}"
print_notice '🚀 Starting release for' "${@}"
unset MAS_VERSION
printf $'\n'

if [[ ! "${tag}" =~ '^v[[:digit:]]+(\.[[:digit:]]+)*(-(alpha|beta|rc)\.[[:digit:]]+)?$' ]]; then
	printf $'Error: %s is not a valid version tag\n' "${tag}" >&2
	exit 1
fi

if (("${#title}" > 64)); then
	printf $'Error: Title \'%s\' contains more than 64 characters\n' "${(q)title}" >&2
	exit 2
fi

if [[ "${title}" =~ [[:cntrl:]] ]]; then
	printf $'Error: Title \'%s\' contains control characters\n' "${(q)title}" >&2
	exit 3
fi

# shellcheck disable=SC1027,SC1036,SC1072,SC1073
if [[ "${title}" = (' '*|*' ') ]]; then
	printf $'Error: Title \'%s\' begins or ends with a space\n' "${(q)title}" >&2
	exit 4
fi

read -r gh_repo_url default_branch default_branch_sha < <(
	gh repo view --json url,defaultBranchRef -q '.url + " " + .defaultBranchRef.name + " " + .defaultBranchRef.target.oid'
)
readonly gh_repo_url default_branch default_branch_sha

git fetch -q "${gh_repo_url}.git" "${default_branch}"
commit_sha="$(git rev-parse --verify "${ref}^{commit}")"
readonly commit_sha
if ! git merge-base --is-ancestor "${commit_sha}" "${default_branch_sha}"; then
	printf $'Error: %s is not on the %s branch of %s\n' "${ref}" "${default_branch}" "${gh_repo_url}" >&2
	exit 5
fi

git tag -s --cleanup=whitespace "${tag}" -m "${title}" "${commit_sha}"
printf $'Created version tag %s with title \'%s\' for reference %s; pushing to %s\n\n'\
	"${tag}"\
	"${(q)title}"\
	"${ref}"\
	"${gh_repo_url}"
git push "${gh_repo_url}.git" tag "${tag}"
