#
# .github/workflows/build-test.yml
#
# https://docs.github.com/en/actions/reference/environment-variables#default-environment-variables

name: Build, Test, and Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:

    # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
    name: Build, Test, and Lint
    runs-on: macos-latest
    steps:
    # https://github.com/actions/checkout#usage
    - uses: actions/checkout@v3.0.2
      with:
        # Fetch tags for script/version
        fetch-depth: 0

    - name: Bootstrap
      run: script/bootstrap
      # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsenv

    - name: Build
      run: script/build

    - name: Test
      run: script/test

    - name: Lint
      run: script/lint
