#
# .github/workflows/tag-pushed.yaml
#
---
name: tag-pushed
on:
  push:
    tags: ['**']
permissions: {}
defaults:
  run:
    # Force all run commands to not use Rosetta 2
    shell: arch -arm64 /bin/zsh -efux --extended-glob --pipe-fail --warn-create-global {0}
jobs:
  tag-pushed:
    if: ${{!github.event.repository.fork}}
    runs-on: macos-26
    permissions:
      contents: write
    steps:
    - name: 🛒 Checkout repo
      env:
        GIT_CONFIG_COUNT: 1
        GIT_CONFIG_KEY_0: init.defaultBranch
        GIT_CONFIG_VALUE_0: ${{github.event.repository.default_branch}}
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        # Include all history & tags for Scripts/version
        fetch-depth: 0

    - name: 🔧 Setup repo
      run: Scripts/setup-workflow-repo

    - name: 🖋 Delete tag lacking trusted SSH signature
      run: |
        git fetch --force origin "${GITHUB_REF}:${GITHUB_REF}"
        if [[
          "$(git tag -l --format='%(contents:signature)' "${GITHUB_REF_NAME}")" != '-----BEGIN SSH SIGNATURE-----'*
        ]]; then
          printf $'::error::Tag %s does not have an SSH signature; deleting\n' "${GITHUB_REF_NAME}" >&2
          git push -d origin "${GITHUB_REF_NAME}"
          exit 1
        fi
        git config gpg.ssh.allowedSignersFile .github/allowed_signers
        if ! git verify-tag "${GITHUB_REF_NAME}" &>/dev/null; then
          printf $'::error::Tag %s SSH signature is not trusted; deleting\n' "${GITHUB_REF_NAME}" >&2
          git push -d origin "${GITHUB_REF_NAME}"
          exit 2
        fi

    - name: 🏷 Exit if not a version tag
      run: |
        if [[ ! "${GITHUB_REF_NAME}" =~ '^v[[:digit:]]+(\.[[:digit:]]+)*(-(alpha|beta|rc)\.[[:digit:]]+)?$' ]]; then
          printf $'::error::%s is not a version tag\n' "${GITHUB_REF_NAME}" >&2
          exit 3
        fi

    - name: 🌿 Delete version tag not on default branch
      env:
        DEFAULT_BRANCH: ${{github.event.repository.default_branch}}
      run: |
        if ! git merge-base --is-ancestor "${GITHUB_SHA}" "origin/${DEFAULT_BRANCH}"; then
          printf $'::error::Tag %s is not on the %s branch; deleting\n' "${GITHUB_REF_NAME}" "${DEFAULT_BRANCH}" >&2
          git push -d origin "${GITHUB_REF_NAME}"
          exit 4
        fi

    - name: 🛠 Select latest stable Xcode
      run: |
        setopt glob_assign
        readonly xcode_path=/Applications/Xcode_[0-9.]##.app(/On[1])
        sudo xcode-select -s "${xcode_path}"
        printf $'DEVELOPER_DIR=%s/Contents/Developer\n' "${xcode_path}" >>"${GITHUB_ENV}"

    - name: 📦 Build Apple & Intel installers
      run: |
        Scripts/package package --arch arm64
        Scripts/package package --arch x86_64

    - name: 🚰 Bump tap formula
      env:
        TOKEN_APP_ID: ${{secrets.TOKEN_APP_ID}}
        TOKEN_APP_INSTALLATION_ID: ${{secrets.TOKEN_APP_INSTALLATION_ID}}
        TOKEN_APP_PRIVATE_KEY: ${{secrets.TOKEN_APP_PRIVATE_KEY}}
      run: |
        HOMEBREW_GITHUB_API_TOKEN="$(Scripts/generate-token)"
        export -r HOMEBREW_GITHUB_API_TOKEN
        brew tap "${GITHUB_REPOSITORY_OWNER}/tap"
        unsetopt err_exit
        bump_output="$(brew bump-formula-pr\
          --tag "${GITHUB_REF_NAME}"\
          --revision "${GITHUB_SHA}"\
          --no-fork\
          --no-browse\
          --online\
          --strict\
          --verbose\
          "${GITHUB_REPOSITORY_OWNER}/tap/mas"\
          2>&1
        )"
        readonly bump_status="${?}"
        readonly bump_output
        setopt err_exit
        printf %s "${bump_output}"
        if [[ "${bump_status}" -ne 0 ]]; then
          printf $'::error::Failed to bump tap formula for tag %s\n' "${GITHUB_REF_NAME}" >&2
          exit 2
        fi
        if [[ "${bump_output}" != *(#b)(https://github.com/"${GITHUB_REPOSITORY_OWNER}"/homebrew-tap/pull/[0-9]##)* ]]
        then
          printf $'::error::Failed to parse tap formula bump PR URL for tag %s\n' "${GITHUB_REF_NAME}" >&2
          exit 3
        fi
        printf %s "${match[1]}" > .build/bump.url

    - name: 📝 Create draft release
      env:
        GH_TOKEN: ${{github.token}}
      run: |
        gh release create\
          "${GITHUB_REF_NAME}"\
          ".build/mas-${GITHUB_REF_NAME#v}-arm64.pkg"\
          ".build/mas-${GITHUB_REF_NAME#v}-x86_64.pkg"\
          .build/bump.url\
          -d\
          ${"${GITHUB_REF_NAME//[^-]}":+-p}\
          -t "${GITHUB_REF_NAME}: ${$(git tag -l "${GITHUB_REF_NAME}" --format='%(contents)')%%$'\n'*}"\
          --generate-notes
