#
# .github/workflows/tag-pushed.yaml
#
---
name: tag-pushed
on:
  push:
    tags: ['**']
permissions: {}
defaults:
  run:
    # Force all run commands to not use Rosetta 2
    shell: arch -arm64 /bin/zsh -efux --extended-glob --pipe-fail --warn-create-global {0}
jobs:
  tag-pushed:
    if: ${{!github.event.repository.fork}}
    runs-on: macos-26
    permissions:
      contents: write
    steps:
    - name: 🛒 Checkout repo
      env:
        GIT_CONFIG_COUNT: 1
        GIT_CONFIG_KEY_0: init.defaultBranch
        GIT_CONFIG_VALUE_0: ${{github.event.repository.default_branch}}
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        # Include all history & tags for Scripts/version
        fetch-depth: 0

    - name: 🔧 Setup repo
      run: Scripts/setup-workflow-repo

    - name: 🖋 Delete tag lacking trusted SSH signature
      run: |
        git fetch --force origin "${GITHUB_REF}:${GITHUB_REF}"
        if [[
          "$(git tag -l --format='%(contents:signature)' "${GITHUB_REF_NAME}")" != '-----BEGIN SSH SIGNATURE-----'*
        ]]; then
          printf $'::error::Tag %s does not have an SSH signature; deleting\n' "${GITHUB_REF_NAME}" >&2
          git push -d origin "${GITHUB_REF_NAME}"
          exit 1
        fi
        git config gpg.ssh.allowedSignersFile .github/allowed_signers
        if ! git verify-tag "${GITHUB_REF_NAME}" &>/dev/null; then
          printf $'::error::Tag %s SSH signature is not trusted; deleting\n' "${GITHUB_REF_NAME}" >&2
          git push -d origin "${GITHUB_REF_NAME}"
          exit 2
        fi

    - name: 🏷 Exit if not a version tag
      run: |
        if [[ ! "${GITHUB_REF_NAME}" =~ '^v[[:digit:]]+(\.[[:digit:]]+)*(-(alpha|beta|rc)\.[[:digit:]]+)?$' ]]; then
          printf $'::error::%s is not a version tag\n' "${GITHUB_REF_NAME}" >&2
          exit 3
        fi

    - name: 🌿 Delete version tag not on default branch
      env:
        DEFAULT_BRANCH: ${{github.event.repository.default_branch}}
      run: |
        if ! git merge-base --is-ancestor "${GITHUB_SHA}" "origin/${DEFAULT_BRANCH}"; then
          printf $'::error::Tag %s is not on the %s branch; deleting\n' "${GITHUB_REF_NAME}" "${DEFAULT_BRANCH}" >&2
          git push -d origin "${GITHUB_REF_NAME}"
          exit 4
        fi

    - name: ⚖️ Verify draft release title & tag message match
      env:
        GH_TOKEN: ${{github.token}}
      run: |
        unsetopt err_exit
        draft_title=\
        "$(gh release view "${GITHUB_REF_NAME}" --json name,isDraft -q 'select(.isDraft == true) | .name' 2>/dev/null)"
        readonly found_draft="${?}"
        readonly draft_title
        setopt err_exit
        if [[ "${found_draft}" -ne 0 || -z "${draft_title}" ]]; then
          printf $'::error::Failed to find draft release for tag %s; deleting\n' "${GITHUB_REF_NAME}" >&2
          git push -d origin "${GITHUB_REF_NAME}"
          exit 5
        fi
        tag_title="${GITHUB_REF_NAME}: $(git tag -l --format='%(contents:subject)' "${GITHUB_REF_NAME}")"
        readonly tag_title
        if [[ "${draft_title}" != "${tag_title}" ]]; then
          printf\
            $'::error::Draft release title (%s) does not match tag title (%s); deleting\n'\
            "${draft_title}"\
            "${tag_title}"\
            >&2
          git push -d origin "${GITHUB_REF_NAME}"
          exit 6
        fi

    - name: 📢 Publish release
      env:
        GH_TOKEN: ${{github.token}}
      run: gh release edit "${GITHUB_REF_NAME}" --draft=false

    - name: 🚰 Update tap formula bump PR
      env:
        GH_TOKEN: ${{github.token}}
        TOKEN_APP_ID: ${{secrets.TOKEN_APP_ID}}
        TOKEN_APP_INSTALLATION_ID: ${{secrets.TOKEN_APP_INSTALLATION_ID}}
        TOKEN_APP_PRIVATE_KEY: ${{secrets.TOKEN_APP_PRIVATE_KEY}}
      run: |
        unsetopt err_exit
        bump_url="$(gh release download "${GITHUB_REF_NAME}" -p bump.url -O - 2>/dev/null)"
        readonly found_bump_url="${?}"
        readonly bump_url
        setopt err_exit
        if [[ "${found_bump_url}" -ne 0 || -z "${bump_url}" ]]; then
          printf $'::error::Failed to find tap formula bump PR URL for tag %s\n' "${GITHUB_REF_NAME}" >&2
          exit 7
        fi
        HOMEBREW_GITHUB_API_TOKEN="$(Scripts/generate-token)"
        export -r HOMEBREW_GITHUB_API_TOKEN
        brew tap "${GITHUB_REPOSITORY_OWNER}/tap" "${GITHUB_SERVER_URL}/"${GITHUB_REPOSITORY_OWNER}/homebrew-tap"
        brew bump-formula-pr\
          --tag "${GITHUB_REF_NAME}"\
          --revision "${GITHUB_SHA}"\
          --no-fork\
          --no-browse\
          --online\
          --strict\
          --verbose\
          "${GITHUB_REPOSITORY_OWNER}/tap/mas"
        gh release delete-asset "${GITHUB_REF_NAME}" bump.url -y
