//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSObservable.h"

@interface _AMSKeyValueObservable : AMSObservable

@property (retain, nullable) NSObject *context;
@property (copy, nullable) NSString *keyPath;
@property (weak) NSObject *object;

- (BOOL)sendCompletion;
- (BOOL)cancel;
- (void)observeValueForKeyPath:(id)path ofObject:(id)object change:(id)change context:(void *)context;
- (nonnull instancetype)initWithObject:(id)object keyPath:(id)path options:(unsigned long long)options;

@end
