//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSBiometricsSignatureResult.h"

@interface _PaymentSheetState : NSObject

@property (retain, nullable) NSError *error;
@property BOOL didAuthorizePayment;
@property BOOL didBiometricsLockout;
@property unsigned long long cancellationType;
@property BOOL didPresent;
@property (retain, nullable) NSString *passwordEquivalentToken;
@property (retain, nullable) NSNumber *paymentMethodType;
@property (retain, nullable) NSString *paymentToken;
@property (retain, nullable) AMSBiometricsSignatureResult *signatureResult;

- (nonnull instancetype)init;

@end
