//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSAccountCachedServerDataServiceInterface-Protocol.h"

@class _TtCs12_SwiftObject, v24@?0@";

@interface _TtCV18AppleMediaServices29SuggestedRatingsConfigurationP33_CA15A9948F8FE6F763BFB83B377B791313BagValueCache : _TtCs12_SwiftObject { // (Swift)
	v24@?0@"<AMSAccountCachedServerDataServiceInterface>"8@"NSError"16 $defaultActor;
	v24@?0@"<AMSAccountCachedServerDataServiceInterface>"8@"NSError"16 cachedModel;
}

@end
