//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSAccountCachedServerDataServiceInterface-Protocol.h"
#include "RBSAssertionObserving-Protocol.h"

@class v24@?0@";

@interface _TtCV18AppleMediaServices9KeepAliveP33_8D5EA5EE57B6E86A66C300315FB9941621RBSAssertionComponent : NSObject <RBSAssertionObserving> { // (Swift)
	v24@?0@"<AMSAccountCachedServerDataServiceInterface>"8@"NSError"16 logKey;
	v24@?0@"<AMSAccountCachedServerDataServiceInterface>"8@"NSError"16 assertion;
	v24@?0@"<AMSAccountCachedServerDataServiceInterface>"8@"NSError"16 invalidationHandler;
}

- (void)assertionWillInvalidate:(id)invalidate;
- (void)assertion:(id)assertion didInvalidateWithError:(nullable NSError *)error;
- (nonnull instancetype)init;

@end
