//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@class Builtin.DefaultActorStorage, Foundation.Date, Swift.AsyncStream.Continuation Swift.Result AppleMediaServices.AccountCachedServerData.CompleteDataUpdate AppleMediaServices.AccountCachedServerData.Error _$sG_ ->, _$sScS -> Swift.Result AppleMediaServices.AccountCachedServerData.CompleteDataUpdate AppleMediaServices.AccountCachedServerData.Error, _$sSh -> AppleMediaServices.AccountIdentity, _$sSo29AMSDarwinNotificationObserverC, _TtCs12_SwiftObject, ppleMediaServices.AccountCachedServerDataDaemonAccessor.ServiceProvider ?, ppleMediaServices.AccountCachedServerDataDaemonAccessor.ServiceProvider _$syc;

@interface _TtC18AppleMediaServices37AccountCachedServerDataDaemonAccessor : _TtCs12_SwiftObject { // (Swift)
	Builtin.DefaultActorStorage $defaultActor;
	_Atomic ppleMediaServices.AccountCachedServerDataDaemonAccessor.ServiceProvider ? storedConnection;
	_$sSh -> AppleMediaServices.AccountIdentity currentlyObservedIDs;
	Swift.AsyncStream.Continuation Swift.Result AppleMediaServices.AccountCachedServerData.CompleteDataUpdate AppleMediaServices.AccountCachedServerData.Error _$sG_ -> observerContinuation;
	_$sSo29AMSDarwinNotificationObserverC notificationObserver;
	_Atomic ppleMediaServices.AccountCachedServerDataDaemonAccessor.ServiceProvider _$syc serviceProvider;
	Foundation.Date previousLazySyncAt;
	_$sScS -> Swift.Result AppleMediaServices.AccountCachedServerData.CompleteDataUpdate AppleMediaServices.AccountCachedServerData.Error dataSequence;
}

@end
