//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSAccountCachedServerDataServiceInterface-Protocol.h"
#include "AMSBagValueFetching-Protocol.h"

@class v24@?0@";

@interface _TtC18AppleMediaServicesP33_DB210F3D31AA4C5BFE8754B925F1C10622BagServiceValueFetcher : NSObject <AMSBagValueFetching> { // (Swift)
	v24@?0@"<AMSAccountCachedServerDataServiceInterface>"8@"NSError"16 bagLoader;
	v24@?0@"<AMSAccountCachedServerDataServiceInterface>"8@"NSError"16 valueFetcher;
}

@property (nonatomic, readonly) NSString *key;
@property (nonatomic, readonly) BOOL isLoaded;

- (void)loadWithCompletion:(UnknownBlock)completion;
- (nonnull instancetype)init;
- (void)processedDefaultValueWithCompletion:(UnknownBlock)completion;

@end
