//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSMetricsEventAnomaly-Protocol.h"

@class _$sSS, _$sSSSg, _$sSo15AMSMetricsEventC;

@interface _TtC18AppleMediaServices33AutoBugCaptureMetricsEventAnomaly : NSObject <AMSMetricsEventAnomaly> { // (Swift)
	_$sSo15AMSMetricsEventC metricsEvent;
	_$sSS subtype;
	_$sSSSg subtypeContext;
}

@property (nonatomic, readonly) NSString *identifier;

- (void)report;
- (nonnull instancetype)init;

@end
