//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@class Builtin.DefaultActorStorage, Swift.Bool, _$sScT -> AppleMediaServices.QRCodeResult _$s_p Swift.Error ?, _TtCs12_SwiftObject, ppleMediaServices.QRCodeHandlerConfiguration, ppleMediaServices.QRCodeHandlerDelegate ?, ppleMediaServices.QRCodePollingSource, ppleMediaServices.QRCodeSetupDataSource;

@interface _TtC18AppleMediaServices13QRCodeHandler : _TtCs12_SwiftObject { // (Swift)
	Builtin.DefaultActorStorage $defaultActor;
	_Atomic ppleMediaServices.QRCodeHandlerDelegate ? delegate;
	_Atomic ppleMediaServices.QRCodeHandlerConfiguration configuration;
	_Atomic ppleMediaServices.QRCodePollingSource pollingSource;
	_Atomic ppleMediaServices.QRCodeSetupDataSource setupDataSource;
	Swift.Bool isActive;
	_$sScT -> AppleMediaServices.QRCodeResult _$s_p Swift.Error ? currentTask;
}

@end
