//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@class Builtin.DefaultActorStorage, _TtCs12_SwiftObject, ppleMediaServices.AccountProvider, ppleMediaServices.ConsumerIDRotationRequester, ppleMediaServices.IdentifierStore;

@interface _TtC18AppleMediaServices28MetricsConsumerIDRotateActor : _TtCs12_SwiftObject { // (Swift)
	Builtin.DefaultActorStorage $defaultActor;
	_Atomic ppleMediaServices.AccountProvider accountProvider;
	_Atomic ppleMediaServices.ConsumerIDRotationRequester requester;
	_Atomic ppleMediaServices.IdentifierStore store;
}

@end
