//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@class _$sSSSg, _$sSa -> AppleMediaServices.AMSPaymentExpandableInfoDetails ?;

@interface _TtC18AppleMediaServices24AMSPaymentExpandableInfo : NSObject <NSSecureCoding> // (Swift)

@property (nonatomic, readonly) NSString *title;
@property (nonatomic, readonly) NSArray *info;

+ (BOOL)supportsSecureCoding;

- (void)encodeWithCoder:(nullable NSCoder *)coder;
- (nonnull instancetype)init;
- (nonnull instancetype)initWithCoder:(nullable NSCoder *)coder;
- (nonnull instancetype)initWithTitle:(id)title info:(id)info;

@end
