//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSAccountCachedServerDataServiceInterface-Protocol.h"
#include "AMSURLHandling-Protocol.h"
#include "AMSURLProtocolDelegate-Protocol.h"
#include "AMSURLSession.h"

@class NSURLRequest, NSURLResponse, NSURLSessionTask, NSURLSessionTaskMetrics, v24@?0@";

@interface _TtC18AppleMediaServicesP33_1DA2568BEFA51656D884E7AA9CC6F3E225MinimalURLProtocolHandler : NSObject <AMSURLProtocolDelegate, AMSURLHandling> { // (Swift)
	v24@?0@"<AMSAccountCachedServerDataServiceInterface>"8@"NSError"16 metricsHandler;
}

@property (nonatomic, weak) AMSURLSession *session;

- (void)decodeMutableData:(NSMutableData *)data task:(NSURLSessionTask *)task completionHandler:(UnknownBlock)handler;
- (void)reportMetricsForContext:(id)context;
- (void)handleResponse:(NSURLResponse *)response task:(NSURLSessionTask *)task completionHandler:(UnknownBlock)handler;
- (nonnull instancetype)init;
- (void)handleCompletionWithTask:(NSURLSessionTask *)task metrics:(NSURLSessionTaskMetrics *)metrics decodedObject:(id)object completionHandler:(UnknownBlock)handler;
- (void)didCreateTask:(NSURLSessionTask *)task fromRequest:(NSURLRequest *)request completionHandler:(UnknownBlock)handler;
- (void)reconfigureNewRequest:(NSURLRequest *)request originalTask:(NSURLSessionTask *)task redirect:(BOOL)redirect completionHandler:(UnknownBlock)handler;

@end
