//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSAccountCachedServerDataServiceInterface-Protocol.h"
#include "SDRDiagnosticReporterDelegate-Protocol.h"

@class v24@?0@";

@interface _TtC18AppleMediaServicesP33_53E9BFD2965C81AFBEDE880E2C1BF3BA30AutoBugCaptureCallbackDelegate : NSObject <SDRDiagnosticReporterDelegate> { // (Swift)
	v24@?0@"<AMSAccountCachedServerDataServiceInterface>"8@"NSError"16 receivedError;
	v24@?0@"<AMSAccountCachedServerDataServiceInterface>"8@"NSError"16 queue;
}

- (nonnull instancetype)init;
- (void)reporterConnectionInterrupted:(id)interrupted;
- (void)reporterConnectionInvalidated:(id)invalidated;

@end
