//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSAccountCachedServerDataServiceInterface-Protocol.h"

@class _TtCs12_SwiftObject, v24@?0@";

@interface _TtCC18AppleMediaServices23AccountCachedServerDataP33_F6A001C17FCEE4AD303229B86F02BD5321ObservationController : _TtCs12_SwiftObject { // (Swift)
	v24@?0@"<AMSAccountCachedServerDataServiceInterface>"8@"NSError"16 lock;
	v24@?0@"<AMSAccountCachedServerDataServiceInterface>"8@"NSError"16 observedIDs;
	v24@?0@"<AMSAccountCachedServerDataServiceInterface>"8@"NSError"16 observedIDsContinuation;
	v24@?0@"<AMSAccountCachedServerDataServiceInterface>"8@"NSError"16 eventSender;
}

@end
