//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@class Swift.Bool, Swift.Int64 ?, _$sSSSg, _TtCs12_SwiftObject, __C.AMSAccountMediaType ?, ppleMediaServices.MockAccountStore;

@interface _TtC18AppleMediaServices27PassingMockAuthenticateTask : _TtCs12_SwiftObject { // (Swift)
	__C.AMSAccountMediaType ? accountMediaType;
	_Atomic ppleMediaServices.MockAccountStore accountStore;
	_$sSSSg altDSID;
	Swift.Bool canMakeAccountActive;
	Swift.Int64 ? dsid;
	_$sSSSg username;
}

@end
