//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@class Builtin.DefaultActorStorage, _$sSSSg, _$sSo14NSUserDefaultsC, _TtCs12_SwiftObject;

@interface _TtC18AppleMediaServices23StoreReviewGatingLedger : _TtCs12_SwiftObject { // (Swift)
	Builtin.DefaultActorStorage $defaultActor;
	_$sSo14NSUserDefaultsC amsUserDefaults;
	_$sSSSg $__lazy_storage_$_currentBundleId;
}

@end
