//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@class NSURLProtocol, _$sSo19AMSMockNetworkProxyC;

@interface _TtC18AppleMediaServices16MockNetworkProxy : NSURLProtocol { // (Swift)
	_$sSo19AMSMockNetworkProxyC networkProxy;
}

+ (id)canonicalRequestForRequest:(id)request;
+ (BOOL)canInitWithRequest:(id)request;

- (void)startLoading;
- (void)stopLoading;
- (nonnull instancetype)initWithRequest:(id)request cachedResponse:(id)response client:(nullable ISStoreClient *)client;

@end
