//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSAuthenticateRequest.h"
#include "AMSURLProtocolDelegate-Protocol.h"
#include "AMSURLSession.h"

@class NSURLSessionTask;

@interface _TtC18AppleMediaServices18CIDAuthURLDelegate : NSObject <NSURLSessionDelegate, AMSURLProtocolDelegate> // (Swift)

- (void)AMSURLSession:(AMSURLSession *)amsurlsession task:(NSURLSessionTask *)task handleAuthenticateRequest:(AMSAuthenticateRequest *)request completion:(UnknownBlock)completion;
- (nonnull instancetype)init;

@end
