//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@class Swift.Error ?, _$sSD -> AppleMediaServices.MockAccountType _$sSh -> AppleMediaServices.MockAccount, _$sSDySS Swift.Error, _TtCs12_SwiftObject;

@interface _TtC18AppleMediaServices16MockAccountStore : _TtCs12_SwiftObject { // (Swift)
	_$sSD -> AppleMediaServices.MockAccountType _$sSh -> AppleMediaServices.MockAccount mockedAccounts;
	Swift.Error ? saveError;
	_$sSDySS Swift.Error targetedSaveErrors;
}

@end
