//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSAccountCachedServerDataServiceInterface-Protocol.h"
#include "AMSAuthenticateRequest.h"
#include "AMSDeveloperSilentAuthTokenDelegateProtocol-Protocol.h"
#include "AMSURLProtocolDelegate-Protocol.h"
#include "AMSURLSession.h"

@class NSURLSessionTask, v24@?0@";

@interface _TtC18AppleMediaServicesP33_68239C40601534D7947471707625281632DeveloperSilentAuthTokenDelegate : NSObject <AMSDeveloperSilentAuthTokenDelegateProtocol, AMSURLProtocolDelegate, NSURLSessionDelegate> { // (Swift)
	v24@?0@"<AMSAccountCachedServerDataServiceInterface>"8@"NSError"16 bag;
}

- (void)AMSURLSession:(AMSURLSession *)amsurlsession task:(NSURLSessionTask *)task handleAuthenticateRequest:(AMSAuthenticateRequest *)request completion:(UnknownBlock)completion;
- (nonnull instancetype)init;

@end
