//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@protocol AKAppleIDAuthenticationDelegate <NSObject>

@required

@optional

- (BOOL)authenticationController:(id)controller shouldContinueWithAuthenticationResults:(id)results error:(nullable NSError *)error forContext:(id)context;
- (void)authenticationController:(id)controller shouldContinueWithAuthenticationResults:(id)results error:(nullable NSError *)error forContext:(id)context completion:(UnknownBlock)completion;

@end
