//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSAccountCachedServerDataFields.h"

@interface AMSAccountCachedServerDataAccountResult : NSObject <NSSecureCoding>

@property (retain, nonatomic, nullable) AMSAccountCachedServerDataFields *fields;
@property (retain, nonatomic, nullable) NSError *error;

+ (BOOL)supportsSecureCoding;

- (void)encodeWithCoder:(nullable NSCoder *)coder;
- (nonnull instancetype)initWithCoder:(nullable NSCoder *)coder;

@end
