//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@class ACAccount;

@interface AMSAuthKitUpdateResult : NSObject <NSSecureCoding>

@property (readonly) ACAccount *account;
@property (readonly) NSDictionary *authenticationResults;
@property (readonly) unsigned long long credentialSource;

+ (BOOL)supportsSecureCoding;
+ (id)_createUpdatedAccount:(id)account usingAuthenticationResults:(id)results options:(id)options;

- (void)encodeWithCoder:(nullable NSCoder *)coder;
- (nonnull NSString *)description;
- (nonnull instancetype)initWithCoder:(nullable NSCoder *)coder;
- (nonnull instancetype)initWithAccount:(id)account authenticationResults:(id)results credentialSource:(unsigned long long)source options:(id)options;
- (nonnull instancetype)initWithAccount:(id)account authenticationResults:(id)results options:(id)options;

@end
