//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSBagConsumer-Protocol.h"

@interface AMSAnisette : NSObject <AMSBagConsumer>

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)createBagForSubProfile;
+ (id)bagSubProfileVersion;
+ (id)bagSubProfile;
+ (BOOL)handleResponse:(id)response account:(id)account type:(long long)type bag:(id)bag;
+ (id)handleResponse:(id)response type:(long long)type bag:(id)bag account:(id)account;
+ (void)_bagDomainExistsForURL:(nullable NSURL *)url type:(long long)type bag:(id)bag completion:(UnknownBlock)completion;
+ (unsigned long long)_accountIDForType:(long long)type account:(id)account;
+ (BOOL)_shouldRetryAfterError:(nullable NSError *)error;
+ (id)bagKeySet;
+ (id)headersForRequest:(id)request account:(id)account type:(long long)type bag:(id)bag;
+ (id)_handleActionName:(id)name actionData:(id)data account:(id)account type:(long long)type bag:(id)bag;
+ (id)_eraseProvisioningForType:(long long)type account:(id)account;
+ (id)_headersForRequest:(id)request account:(id)account type:(long long)type;
+ (id)_syncMachineWithActionData:(id)data type:(long long)type account:(id)account bag:(id)bag;
+ (id)_provisionMachineWithActionData:(id)data type:(long long)type account:(id)account bag:(id)bag;

@end
