//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSAccountCachedServerDataServiceInterface-Protocol.h"

@class v24@?0@";

@interface AMSAutoBugCaptureDiagnosticActionOptions : NSObject { // (Swift)
	v24@?0@"<AMSAccountCachedServerDataServiceInterface>"8@"NSError"16 logArchive;
	v24@?0@"<AMSAccountCachedServerDataServiceInterface>"8@"NSError"16 getNetworkInfo;
	v24@?0@"<AMSAccountCachedServerDataServiceInterface>"8@"NSError"16 crashAndSpinLogs;
	v24@?0@"<AMSAccountCachedServerDataServiceInterface>"8@"NSError"16 diagnosticExtensionOptions;
	v24@?0@"<AMSAccountCachedServerDataServiceInterface>"8@"NSError"16 probeOptions;
}

- (nonnull instancetype)init;
- (nonnull instancetype)initWithLogArchive:(BOOL)archive getNetworkInfo:(BOOL)info crashAndSpinLogs:(BOOL)logs diagnosticExtensionOptions:(id)options probeOptions:(id)options;

@end
