//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@interface AMSAccountManagementService : NSObject

- (id)_accountManagementServiceAsyncWithConnection:(id)connection;
- (id)_accountManagementServiceSyncWithConnection:(id)connection error:(id *)error;
- (BOOL)_supportsDirectAccess;
- (id)performCreateLocalAccountWithIdentifier:(id)identifier;
- (void)performCreateLocalAccountWithIdentifier:(id)identifier error:(id *)error;
- (id)performCreateLocalAccountWithIdentifier:(id)identifier mediaType:(id)type;
- (void)performCreateLocalAccountWithIdentifier:(id)identifier mediaType:(id)type error:(id *)error;
- (id)performCreateLocalAccountWithType:(id)type;
- (void)performCreateLocalAccountWithType:(id)type error:(id *)error;
- (id)performCreateLocalAccountWithType:(id)type mediaType:(id)type;
- (void)performCreateLocalAccountWithType:(id)type mediaType:(id)type error:(id *)error;

@end
