//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "_TtC18AppleMediaServices28AgeGroupContentPolicyContent.h"

@interface AMSAgeGroupContentPolicy : NSObject

@property (nonatomic, readonly) NSString *description;
@property (nonatomic, readonly) NSString *identifier;
@property (nonatomic, readonly) NSString *ageGroup;
@property (nonatomic, readonly) BOOL allowPurchases;
@property (nonatomic, readonly) NSArray *recommendedContentRatings;
@property (nonatomic, readonly) _TtC18AppleMediaServices28AgeGroupContentPolicyContent *content;

- (nonnull instancetype)initWithDictionary:(nullable NSDictionary *)dictionary;
- (nonnull instancetype)init;

@end
