//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AKAppleIDAuthenticationDelegate-Protocol.h"
#include "AMSAuthenticateOptions.h"
#include "AMSTask.h"

@class ACAccount;

@interface AMSAuthKitUpdateTask : AMSTask <AKAppleIDAuthenticationDelegate>

@property (readonly) ACAccount *account;
@property (readonly) AMSAuthenticateOptions *options;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (void)_updateAccountRawPasswordUsingSecondaryAccounts:(id)accounts options:(id)options;

- (BOOL)authenticationController:(id)controller shouldContinueWithAuthenticationResults:(id)results error:(nullable NSError *)error forContext:(id)context;
- (nonnull instancetype)initWithAccount:(id)account options:(id)options;
- (void)_configureClientInfoForContext:(id)context;
- (unsigned long long)_authenticationType;
- (BOOL)_canPresentBackgroundPrompt;
- (void)_configureAuthKitContext:(id)context;
- (void)_configureCompanionDeviceForContext:(id)context;
- (void)_configureIdentifiersForContext:(id)context;
- (void)_configureProxyIdentifiersForContext:(id)context;
- (void)_configureStringsForContext:(id)context;
- (id)_createAuthKitContext;
- (id)_createAuthKitController;
- (void)_logPromptSummaryForResults:(id)results context:(id)context;
- (BOOL)_shouldPrefillPrimaryiCloudAccount;
- (id)performAuthKitUpdate;

@end
