//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSObservable.h"

@class ACAccount;

@interface AMSAccountsChangedObservable : NSObject

@property (retain, nullable) AMSObservable *observable;
@property (readonly) struct os_unfair_lock_s { unsigned int x0; } notificationsLock;
@property (readonly) ACAccount *account;
@property (readonly) NSString *accountTypeIdentifier;

+ (id)sharedInstance;
+ (void)_processChangedAccount:(id)account;
+ (id)createdObservablesAccessQueue;
+ (id)sharedLocalAccountInstance;
+ (id)createdObservables;

- (void)unsubscribe:(id)unsubscribe;
- (void)_accountStoreDidChange:(id)change;
- (nonnull instancetype)initWithAccount:(id)account;
- (BOOL)_shouldNotifyObserversForChangedAccount:(id)account;
- (id)_initWithAccount:(id)account accountTypeIdentifier:(id)identifier;
- (void)subscribe:(id)subscribe;
- (void)_processChangedAccount:(id)account;
- (nonnull instancetype)initWithAccountTypeIdentifier:(id)identifier;
- (void)dealloc;

@end
