//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@protocol AMSAccountCachedServerDataServiceInterface <NSObject>

@required

- (void)externalSyncAndUpdateEligibilityForAccountID:(id)id timeout:(double)timeout reply:(UnknownBlock)reply;
- (void)getDataForAccountIDs:(id)ids reply:(UnknownBlock)reply;
- (void)lazySyncForAccounts:(id)accounts reply:(UnknownBlock)reply;
- (void)manualSyncForAccountID:(id)id reply:(UnknownBlock)reply;
- (void)queueMetricsEventNotingExpiry:(id)expiry appID:(id)id reply:(UnknownBlock)reply;
- (void)setAutoPlayState:(BOOL)state forAccountID:(id)id reply:(UnknownBlock)reply;
- (void)setPersonalizationState:(BOOL)state forAccountID:(id)id reply:(UnknownBlock)reply;

@optional

@end
