//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSProcessInfo.h"

@class AKAuthenticatableResource;

@interface AMSAuthenticateOptions : NSObject <NSCopying, NSSecureCoding>

@property unsigned long long allowPasswordGeneration;
@property BOOL allowSecondaryCredentialSource;
@property (retain, nullable) NSString *companionDeviceClientInfo;
@property (retain, nullable) NSString *companionDeviceUDID;
@property BOOL demoAccountSetup;
@property BOOL ephemeral;
@property (retain, nullable) NSString *metricsIdentifier;
@property (readonly) NSDictionary *optionsDictionaryForLogging;
@property (copy, nullable) NSString *passwordlessToken;
@property long long serviceType;
@property (retain, nullable) NSString *simpleProfileAltDSID;
@property BOOL simpleProfileCreated;
@property (retain, nullable) NSNumber *simpleProfileDSID;
@property (readonly) BOOL remoteProxyAuthentication;
@property (retain, nullable) NSString *serviceIdentifier;
@property BOOL allowServerDialogs;
@property unsigned long long authenticationType;
@property (copy, nullable) NSString *appProvidedContext;
@property (copy, nullable) NSDictionary *appProvidedData;
@property (retain, nullable) AKAuthenticatableResource *authenticatableResource;
@property (retain, nullable) NSString *cancelButtonString;
@property BOOL canMakeAccountActive;
@property (retain, nullable) NSDictionary *createAccountQueryParams;
@property (retain, nullable) AMSProcessInfo *clientInfo;
@property unsigned long long credentialSource;
@property (retain, nullable) NSString *debugReason;
@property (retain, nullable) NSString *defaultButtonString;
@property (retain, nullable) NSString *delegateAuthChallenge;
@property BOOL delegateAuthEnabled;
@property BOOL enableAccountCreation;
@property (retain, nullable) NSDictionary *HTTPHeaders;
@property (retain, nullable) NSURL *iconBundleURL;
@property BOOL ignoreAccountConversion;
@property BOOL forceSyncToPairedWatch;
@property (retain, nullable) NSString *logKey;
@property unsigned long long multiUserAuthentication;
@property (retain, nullable) NSString *promptTitle;
@property (retain, nullable) NSString *proxyAppBundleID;
@property (retain, nullable) NSString *proxyAppName;
@property (retain, nullable) NSString *reason;
@property (retain, nullable) NSString *userAgent;
@property (retain, nullable) NSString *userAgentSuffix;
@property BOOL usernameEditable;
@property BOOL serviceTokenOnly;

+ (BOOL)supportsSecureCoding;
+ (id)_stringForAuthenticationType:(unsigned long long)type;

- (void)setMediaType:(id)type;
- (nonnull instancetype)initWithOptionsDictionary:(nullable NSDictionary *)dictionary;
- (nonnull instancetype)copyWithZone:(nullable struct _NSZone *)zone;
- (void)encodeWithCoder:(nullable NSCoder *)coder;
- (BOOL)isEqual:(nullable id)object;
- (id)optionsDictionary;
- (nonnull instancetype)init;
- (nonnull NSString *)description;
- (id)mediaType;
- (nonnull instancetype)initWithCoder:(nullable NSCoder *)coder;
- (id)presentingViewController;
- (void)setPresentingViewController:(id)controller;
- (void)setAuthKitData:(id)data;
- (id)authKitData;
- (BOOL)isDemoAccountSetup;
- (BOOL)isRemoteProxyAuthentication;
- (id)optionsDictionaryForRemoteProxyAuthentication;

@end
