//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSBagConsumer-Protocol.h"
#include "AMSBagProtocol-Protocol.h"
#include "AMSProcessInfo.h"
#include "AMSTask.h"
#include "AMSURLRequestEncoder.h"
#include "AMSURLSession.h"

@class ACAccount, ACAccountStore;

@interface AMSAccountDeviceInfoTask : AMSTask <AMSBagConsumer>

@property (retain, nullable) AMSURLSession *session;
@property (retain, nullable) AMSURLRequestEncoder *requestEncoder;
@property (retain, nullable) NSString *serialNumber;
@property (retain, nullable) ACAccountStore *accountStore;
@property (readonly) ACAccount *account;
@property (readonly) id <AMSBagProtocol> bag;
@property (retain, nullable) AMSProcessInfo *clientInfo;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)createBagForSubProfile;
+ (id)bagSubProfileVersion;
+ (id)bagSubProfile;

- (id)perform;
- (id)_deviceInfoRequest;
- (id)_requestWithURL:(nullable NSURL *)url;
- (id)_updateAccountWithInfo:(id)info;
- (nonnull instancetype)initWithAccount:(id)account accountStore:(id)store bag:(id)bag;
- (nonnull instancetype)initWithAccount:(id)account accountStore:(id)store bag:(id)bag requestEncoder:(id)encoder session:(id)session serialNumber:(id)number;

@end
