//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSAuthenticateMetricsProtocol-Protocol.h"
#include "AMSBagConsumer-Protocol.h"
#include "AMSBagProtocol-Protocol.h"
#include "AMSMetrics.h"

@interface AMSAuthenticateMetrics : NSObject <AMSBagConsumer, AMSAuthenticateMetricsProtocol>

@property (readonly) id <AMSBagProtocol> bag;
@property (readonly) AMSMetrics *metrics;
@property (retain, nullable) NSDate *beginDate;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)createBagForSubProfile;
+ (id)bagSubProfileVersion;
+ (id)bagSubProfile;
+ (id)_eventWithTopic:(id)topic;
+ (id)_metricsInstanceWithBag:(id)bag;

- (nonnull instancetype)initWithBag:(id)bag;
- (nonnull instancetype)init;
- (void)flushEvents;
- (id)_enqueueEvents:(id)events;
- (BOOL)_accountIsSecondaryHomeUser:(id)user;
- (id)_authenticationTypeStringFor:(unsigned long long)_for;
- (id)_clampTimeStampValue:(id)value;
- (id)_credentialSourceStringFor:(unsigned long long)_for;
- (id)_durationSinceDate:(id)date;
- (id)_enqueueEventWithTopic:(id)topic properties:(id)properties;
- (id)_enqueueProperties:(id)properties account:(id)account;
- (id)_eventTime;
- (BOOL)_isTopicDefined:(id)defined;
- (id)_topicFromBag;
- (id)_userIdForBagNamespace:(id)_namespace;
- (id)enqueueAuthKitBeginEventWithOptions:(id)options account:(id)account;
- (id)enqueueAuthKitFinishEventWithOptions:(id)options account:(id)account error:(nullable NSError *)error;
- (id)enqueueAuthenticationBeginEventWithOptions:(id)options serverRequested:(BOOL)requested account:(id)account;
- (id)enqueueVerifyCredentialsBeginEventWithOptions:(id)options account:(id)account;
- (id)enqueueVerifyCredentialsFinishEventWithOptions:(id)options account:(id)account error:(nullable NSError *)error;
- (id)enqueueWithEvent:(unsigned long long)event context:(id)context;

@end
