//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@interface AMSAgeVerificationCore : NSObject

+ (id)_ageVerificationPresentationResultFromVerificationResult:(id)result;
+ (id)_appendClientFields:(id)fields asQueryParametersToURL:(nullable NSURL *)url;
+ (BOOL)_isAgeVerificationNeededForExpiration:(id)expiration at:(id)at;
+ (BOOL)_isTimestamp:(id)timestamp validAsOf:(id)of;
+ (id)_momentOfExpiryFrom:(id)from;
+ (id)_resultForAccountVerificationExpirationTimestamp:(id)timestamp withBagControlledAgeVerificationRequired:(id)required bagWarningThresholdDays:(id)days at:(id)at;
+ (id)_timestampForWarningThresholdDays:(id)days addedTo:(id)to;

@end
