//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSAuthKitUpdateResult.h"

@class ACAccount;

@interface AMSAuthenticateResult : NSObject <NSSecureCoding>

@property (retain, nullable) AMSAuthKitUpdateResult *authKitUpdateResult;
@property (readonly) ACAccount *account;
@property (readonly) NSDictionary *authenticationResults;
@property (readonly) NSString *editToken;
@property (readonly) NSDictionary *serverResponse;

+ (BOOL)supportsSecureCoding;

- (nonnull instancetype)initWithAccount:(id)account;
- (void)encodeWithCoder:(nullable NSCoder *)coder;
- (nonnull NSString *)description;
- (nonnull instancetype)initWithCoder:(nullable NSCoder *)coder;

@end
