//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSActionContext.h"

@interface AMSActionRunner : NSObject // (Swift)

+ (id)handle:(id)handle context:(id)context;
+ (BOOL)canHandle:(id)handle context:(id)context;
+ (void)handle:(NSDictionary *)handle context:(AMSActionContext *)context completionHandler:(UnknownBlock)handler;

- (nonnull instancetype)init;

@end
