//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSAccountCachedServerDataServiceInterface-Protocol.h"
#include "AMSAutoBugCaptureDiagnosticActionOptions.h"

@class v24@?0@";

@interface AMSAutoBugCaptureReport : NSObject { // (Swift)
	v24@?0@"<AMSAccountCachedServerDataServiceInterface>"8@"NSError"16 reporter;
	v24@?0@"<AMSAccountCachedServerDataServiceInterface>"8@"NSError"16 callbackDelegate;
}

@property (nonatomic, readonly) NSString *domain;
@property (nonatomic, readonly) NSString *type;
@property (nonatomic, readonly) NSString *subtype;
@property (nonatomic, readonly) NSString *subtypeContext;
@property (nonatomic, readonly) NSString *process;
@property (nonatomic, readonly) NSArray *thresholdValues;

+ (void)sendSnapshotFromXPCWithSignature:(NSDictionary *)signature delay:(double)delay events:(NSArray *)events payload:(NSDictionary *)payload actions:(NSDictionary *)actions completionHandler:(UnknownBlock)handler;

- (nonnull instancetype)init;
- (void)captureWithDelay:(double)delay events:(NSArray *)events payload:(NSDictionary *)payload actions:(AMSAutoBugCaptureDiagnosticActionOptions *)actions completionHandler:(UnknownBlock)handler;
- (nonnull instancetype)initWithDomain:(id)domain type:(id)type subtype:(id)subtype subtypeContext:(id)context process:(id)process thresholdValues:(id)values;

@end
