//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSAuthenticateMetricsProtocol-Protocol.h"
#include "AMSAuthenticateOptions.h"
#include "AMSAuthenticateTaskDelegate-Protocol.h"
#include "AMSBagConsumer-Protocol.h"
#include "AMSBagProtocol-Protocol.h"
#include "AMSMutablePromise.h"
#include "AMSTask.h"

@class ACAccountStore;

@interface AMSAuthenticateTask : AMSTask <AMSBagConsumer>

@property (readonly) NSDictionary *initialAuthenticationResults;
@property (retain, nullable) AMSMutablePromise *resultPromise;
@property (retain, nullable) NSMutableArray *errors;
@property BOOL isLocalAccountProvided;
@property BOOL isServerRequested;
@property (retain, nullable) id <AMSAuthenticateMetricsProtocol> metrics;
@property (retain, nullable) ACAccountStore *accountStore;
@property (retain, nullable) id <AMSBagProtocol> bag;
@property (weak) id <AMSAuthenticateTaskDelegate> delegate;
@property (readonly) AMSAuthenticateOptions *options;
@property (copy, nullable) NSString *password;
@property (copy, nullable) NSString *multiUserToken;
@property (copy, nullable) NSString *rawPassword;
@property (copy, nullable) NSString *altDSID;
@property (retain, nullable) NSNumber *DSID;
@property (retain, nullable) NSUUID *homeIdentifier;
@property (retain, nullable) NSUUID *homeUserIdentifier;
@property (copy, nullable) NSString *username;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)createBagForSubProfile;
+ (id)bagSubProfileVersion;
+ (id)bagSubProfile;
+ (id)bagKeySet;
+ (id)_accountStoreForOptions:(id)options;
+ (id)_createFallbackBag;
+ (id)loadCreateAppleIDWithClientInfo:(id)info bag:(id)bag;
+ (id)loadCreateAppleIDWithClientInfo:(id)info url:(nullable NSURL *)url bag:(id)bag;

- (nonnull instancetype)initWithRequest:(id)request;
- (nonnull instancetype)initWithRequest:(id)request bag:(id)bag;
- (nonnull instancetype)init;
- (nonnull instancetype)initWithAccount:(id)account options:(id)options;
- (id)_sanitizeError:(nullable NSError *)error;
- (id)_runCreateAccountDialogWithBag:(id)bag;
- (id)_accountForAuthenticationWithError:(id *)error;
- (id)_attemptCompanionAuthenticationForAccount:(id)account;
- (void)_attemptMultiUserTokenAuthenticationForAccount:(id)account completion:(UnknownBlock)completion;
- (id)_attemptPasswordReuseAuthenticationForAccount:(id)account;
- (id)_createAuthKitUpdateTaskForAccount:(id)account;
- (id)_createAuthKitUpdateTaskForAccount:(id)account options:(id)options;
- (id)_finishWithVerifiedAccount:(id)account andAuthKitUpdateResult:(id)result;
- (void)_handleDialogFromError:(nullable NSError *)error completion:(UnknownBlock)completion;
- (BOOL)_isMetricsEnabled;
- (void)_performAuthenticationAndGeneratePasswordWithAccount:(id)account;
- (id)_performAuthenticationUsingAccount:(id)account credentialSource:(unsigned long long)source;
- (void)_performAuthenticationWithInitialResultsAndAccount:(id)account;
- (void)_postFollowUpForFailedAuthenticationWithAccount:(id)account;
- (void)_processAuthKitUpdateResult:(id)result error:(nullable NSError *)error;
- (id)_runCreateAccountDialog;
- (id)_runDialogRequest:(id)request;
- (BOOL)_shouldShowCreateAccountDialogForAccount:(id)account;
- (id)_signIntoOtherMediaTypeWithVerifiedAccount:(id)account authenticationResults:(id)results;
- (void)_updateAccountPasswordUsingSecondaryAccounts:(id)accounts;
- (void)_updateAccountWithProvidedInformation:(id)information;
- (id)homeID;
- (nonnull instancetype)initWithAccount:(id)account accountStore:(id)store options:(id)options;
- (nonnull instancetype)initWithAccount:(id)account accountStore:(id)store options:(id)options bag:(id)bag;
- (nonnull instancetype)initWithAccount:(id)account options:(id)options bag:(id)bag;
- (nonnull instancetype)initWithAuthenticationResults:(id)results accountStore:(id)store options:(id)options;
- (nonnull instancetype)initWithAuthenticationResults:(id)results accountStore:(id)store options:(id)options bag:(id)bag;
- (nonnull instancetype)initWithAuthenticationResults:(id)results options:(id)options;
- (nonnull instancetype)initWithAuthenticationResults:(id)results options:(id)options bag:(id)bag;
- (nonnull instancetype)initWithRequest:(id)request accountStore:(id)store;
- (nonnull instancetype)initWithRequest:(id)request accountStore:(id)store bag:(id)bag;
- (id)performAuthentication;
- (void)setHomeID:(id)id;

@end
