//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSBagConsumer-Protocol.h"
#include "AMSBagProtocol-Protocol.h"
#include "AMSQRCodeDialogTask.h"
#include "AMSRequestPresentationDelegate-Protocol.h"
#include "AMSTask.h"

@class ACAccount;

@interface AMSAgeVerificationTask : AMSTask <AMSBagConsumer>

@property (retain, nullable) AMSQRCodeDialogTask *task;
@property (readonly) ACAccount *account;
@property (readonly) id <AMSBagProtocol> bag;
@property (retain, nullable) NSDictionary *options;
@property (retain, nullable) NSString *pincode;
@property (readonly) id <AMSRequestPresentationDelegate> presentationDelegate;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)createBagForSubProfile;
+ (id)bagSubProfileVersion;
+ (id)bagSubProfile;
+ (id)bagKeySet;
+ (id)_errorCheckWithAccount:(id)account bag:(id)bag;

- (id)performTask;
- (id)_performTaskForAccount:(id)account withBag:(id)bag;
- (void)_handleAccountStoreDidChangeNotification:(id)notification;
- (void)_handleAccountStoreDidChangeNotification:(id)notification at:(id)at;
- (void)_startObservingAccountStoreChanges;
- (void)_stopObservingAccountStoreChanges;
- (nonnull instancetype)initWithAccount:(id)account bag:(id)bag options:(id)options presentationDelegate:(id)delegate;
- (id)isVerificationNeeded;

@end
