//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSAuthenticateOptions.h"

@class ACAccount;

@interface AMSAuthenticateRequest : NSObject <NSSecureCoding>

@property (retain, nullable) ACAccount *account;
@property BOOL isServerRequested;
@property (retain, nullable) NSString *logKey;
@property (retain, nullable) AMSAuthenticateOptions *options;
@property (retain, nullable) NSDictionary *userInfo;

+ (BOOL)supportsSecureCoding;

- (void)encodeWithCoder:(nullable NSCoder *)coder;
- (nonnull NSString *)description;
- (nonnull instancetype)initWithCoder:(nullable NSCoder *)coder;
- (nonnull instancetype)initWithAccount:(id)account options:(id)options;
- (nonnull instancetype)initWithDSID:(nullable NSNumber *)dsID altDSID:(nullable NSNumber *)dsID username:(id)username options:(id)options;

@end
