//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@interface AMSBuyParams : NSObject <NSCopying, NSSecureCoding> {
	NSMutableDictionary *_backingDictionary;
}

@property (readonly, copy) NSDictionary *normalizedDictionary;
@property (readonly) BOOL freeTrial;
@property (readonly) double price;
@property (readonly) NSDictionary *objectForLogging;
@property (readonly, copy) NSDictionary *dictionary;

+ (id)buyParamsWithString:(id)string;
+ (BOOL)supportsSecureCoding;

- (nonnull instancetype)initWithString:(id)string;
- (nonnull instancetype)initWithArray:(id)array;
- (id)propertyForKey:(id)key;
- (id)stringValue;
- (nonnull instancetype)copyWithZone:(nullable struct _NSZone *)zone;
- (BOOL)containsKey:(id)key;
- (void)clear;
- (void)encodeWithCoder:(nullable NSCoder *)coder;
- (void)setProperty:(id)property forKey:(id)key;
- (nonnull instancetype)init;
- (id)objectForKeyedSubscript:(id)subscript;
- (nonnull NSString *)description;
- (nonnull instancetype)initWithCoder:(nullable NSCoder *)coder;
- (void)setObject:(id)object forKeyedSubscript:(id)subscript;
- (id)parameterForKey:(id)key;
- (id)_convertParsedBuyParamIfNeeded:(id)needed;
- (id)_normalizedDictionary;
- (void)_parseBuyParams:(id)params;
- (void)_parseBuyParamsArray:(id)array;
- (void)addBlindedSignature:(id)signature;
- (nullable NSDictionary *)dictionaryForFPDI;
- (BOOL)isFreeTrial;
- (BOOL)isRedownload;
- (void)removeBlindedData;
- (id)requestDataWithError:(id *)error;
- (void)setParameter:(id)parameter forKey:(id)key;

@end
