//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSFrozenBagValue.h"
#include "AMSPromise.h"

@interface AMSBridgedBagValue : AMSFrozenBagValue

@property (retain, nullable) AMSPromise *valuePromise;

- (void)valueWithCompletion:(UnknownBlock)completion;
- (nonnull instancetype)initWithKey:(id)key valueType:(unsigned long long)type valuePromise:(id)promise;

@end
