//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@interface AMSBiometrics : NSObject

+ (long long)stateForAccount:(id)account;
+ (BOOL)_deleteKeysWithOptions:(id)options error:(id *)error;
+ (long long)deviceState;
+ (id)disableForAccount:(id)account;
+ (id)isActionSupportedForType:(long long)type account:(id)account options:(id)options;
+ (id)signChallenge:(id)challenge withAccount:(id)account clientInfo:(id)info options:(id)options;
+ (id)minimumACLVersionForAction:(long long)action;
+ (id)_stateHeaderValueForAccount:(id)account;
+ (BOOL)_shouldAddBiometricHeader;
+ (BOOL)isActionSupportedForType:(long long)type account:(id)account options:(id)options error:(id *)error;
+ (id)handleResponse:(id)response financeResponse:(id)response session:(id)session taskInfo:(id)info;
+ (BOOL)deleteAllKeysWithError:(id *)error;
+ (void)setDeviceState:(long long)state;
+ (BOOL)isIdentityMapValid;
+ (BOOL)deleteKeysWithError:(id *)error;
+ (id)identityMap;
+ (id)resumptionHeadersFromRequest:(id)request;
+ (id)ACLVersionForAccount:(id)account options:(id)options error:(id *)error;
+ (BOOL)isAvailableForAccount:(id)account;
+ (long long)type;
+ (id)signAndReturnChallenge:(id)challenge withAccount:(id)account clientInfo:(id)info options:(id)options;
+ (id)setState:(long long)state forAccount:(id)account;
+ (id)ACLVersionForAccessControl:(struct __SecAccessControl *)control;
+ (BOOL)isActionSupported:(long long)supported withAccessControl:(struct __SecAccessControl *)control;
+ (BOOL)isActionSupported:(long long)supported withConstraints:(id)constraints;
+ (void)saveIdentityMap;
+ (id)ACLVersionForConstraints:(id)constraints;
+ (BOOL)hasKeysForAccount:(id)account forSignaturePurpose:(unsigned long long)purpose withError:(id *)error;
+ (id)headersWithAccount:(id)account options:(id)options signatureResult:(id)result;
+ (BOOL)isDeviceInBiometricLockout;
+ (BOOL)proxyDeleteAllKeysWithError:(id *)error;

@end
