//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@interface AMSBagDataSourceChange : NSObject

@property (readonly) NSString *accountIdentifier;
@property (readonly) NSString *loadedBagIdentifier;
@property (readonly) NSString *loadedBagPartialIdentifier;
@property (readonly) NSDictionary *originalData;
@property (readonly) NSDate *originalExpirationDate;
@property (readonly) NSString *profile;
@property (readonly) NSString *profileVersion;
@property (readonly) NSDictionary *updatedData;
@property (readonly) NSDate *updatedExpirationDate;
@property (readonly) NSSet *changedKeys;

- (nonnull instancetype)initWithProfile:(id)profile profileVersion:(id)version originalData:(id)data originalExpirationDate:(id)date updatedData:(id)data updatedExpirationDate:(id)date changedKeys:(id)keys loadedBagIdentifier:(id)identifier loadedBagPartialIdentifier:(id)identifier accountIdentifier:(id)identifier;

@end
