//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSRequestPresentationDelegate-Protocol.h"
#include "AMSURLSession.h"

@class NSURLSessionTask;
@protocol OS_dispatch_queue;

@interface AMSBiometricsPresentationProxy : NSObject <AMSRequestPresentationDelegate>

@property (retain, nullable) dispatch_queue_t delegateQueue;
@property (readonly) AMSURLSession *session;
@property (readonly) NSURLSessionTask *task;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (nonnull instancetype)initWithSession:(id)session task:(id)task;
- (void)handleDialogRequest:(id)request completion:(UnknownBlock)completion;
- (void)handleAuthenticateRequest:(id)request completion:(UnknownBlock)completion;

@end
