//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@class ACAccount;

@protocol AMSBagAccountProvider <NSObject>

@required

@property (readonly) NSString *identity;
@property (readonly) ACAccount *account;

- (BOOL)associatedAccountIsEqualToAccount:(id)account forMediaType:(id)type;
- (id)bagAccountForAccountMediaType:(id)type;
- (id)bagAccountPromiseForAccountMediaType:(id)type;
- (id)bagStorefrontForAccountMediaType:(id)type;
- (id)bagStorefrontPromiseForAccountMediaType:(id)type;

@optional

@end
