//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSBagDataSourceProtocol-Protocol.h"
#include "AMSProcessInfo.h"

@interface AMSBagFrozenDataSource : NSObject <AMSBagDataSourceProtocol, NSCopying, NSSecureCoding>

@property (readonly) NSDictionary *data;
@property (readonly) NSDictionary *defaultValues;
@property (readonly, nonatomic) NSDictionary *dictionary;
@property (readonly) NSDate *expirationDate;
@property (readonly) BOOL loaded;
@property (readonly, copy) NSString *bagLoadingPartialIdentifier;
@property (readonly, copy) AMSProcessInfo *processInfo;
@property (readonly, copy) NSString *profile;
@property (readonly, copy) NSString *profileVersion;
@property (retain, nullable) NSString *descriptionExtended;
@property (copy, nullable) UnknownBlock dataSourceChangedHandler;
@property (copy, nullable) UnknownBlock dataSourceDataInvalidatedHandler;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (BOOL)supportsSecureCoding;

- (id)valueForURLVariable:(nullable NSURL *)urlvariable account:(id)account;
- (void)loadWithCompletion:(UnknownBlock)completion;
- (void)valueForURLVariable:(nullable NSURL *)urlvariable account:(id)account completion:(UnknownBlock)completion;
- (id)defaultValueForKey:(id)key;
- (void)setDefaultValue:(id)value forKey:(id)key;
- (BOOL)isLoaded;
- (id)_initWithProfile:(id)profile profileVersion:(id)version data:(id)data expirationDate:(id)date processInfo:(id)info defaultValues:(id)values;
- (nonnull instancetype)copyWithZone:(nullable struct _NSZone *)zone;
- (void)encodeWithCoder:(nullable NSCoder *)coder;
- (nonnull instancetype)initWithCoder:(nullable NSCoder *)coder;

@end
