//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSProcessInfo.h"

@protocol AMSBagDataSourceProtocol <NSObject>

@required

@property (readonly) NSDate *expirationDate;
@property (readonly) BOOL loaded;
@property (readonly, copy) NSString *bagLoadingPartialIdentifier;
@property (readonly, copy) AMSProcessInfo *processInfo;
@property (readonly, copy) NSString *profile;
@property (readonly, copy) NSString *profileVersion;

- (id)valueForURLVariable:(nullable NSURL *)urlvariable account:(id)account;
- (void)loadWithCompletion:(UnknownBlock)completion;
- (void)valueForURLVariable:(nullable NSURL *)urlvariable account:(id)account completion:(UnknownBlock)completion;
- (id)defaultValueForKey:(id)key;
- (void)setDefaultValue:(id)value forKey:(id)key;
- (BOOL)isLoaded;

@optional

@property (retain, nullable) NSString *descriptionExtended;
@property (copy, nullable) UnknownBlock dataSourceChangedHandler;
@property (copy, nullable) UnknownBlock dataSourceDataInvalidatedHandler;

- (id)loadedValuesForKeys:(id)keys outExpirationDate:(id *)date;

@end
