//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@interface AMSBagURLParser : NSObject

+ (id)URLBySubstitutingVariablesInURLString:(nullable NSURL *)urlstring usingBlock:(UnknownBlock)block;
+ (struct _NSRange { unsigned long long x0; unsigned long long x1; })_rangeofSubstringWithOpeningTag:(id)tag closingTag:(id)tag inString:(id)string;
+ (id)URLBySubstitutingVariablesInURLString:(nullable NSURL *)urlstring usingPromiseBlock:(UnknownBlock)block;
+ (id)_firstVariableInTemplate:(id)_template includeTags:(BOOL)tags;
+ (struct _NSRange { unsigned long long x0; unsigned long long x1; })_rangeOfTemplateInURLString:(nullable NSURL *)urlstring;
+ (id)_URLBySubstitutingVariablesInURLString:(nullable NSURL *)urlstring range:(struct _NSRange { unsigned long long x0; unsigned long long x1; })range usingPromiseBlock:(UnknownBlock)block;

@end
