//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSBagDataSourceProtocol-Protocol.h"
#include "AMSBagValueFetching-Protocol.h"

@class ACAccount;

@interface AMSBagValueDataSourceValueFetcher : NSObject <AMSBagValueFetching>

@property (readonly, nonatomic) unsigned long long valueType;
@property (readonly, nonatomic) ACAccount *account;
@property (weak, nonatomic) id <AMSBagDataSourceProtocol> dataSource;
@property (readonly, nonatomic) BOOL isLoaded;
@property (readonly, copy, nonatomic) NSString *key;

+ (id)_valueFromDictionary:(nullable NSDictionary *)dictionary forBagKey:(id)key;

- (void)loadWithCompletion:(UnknownBlock)completion;
- (nonnull instancetype)initWithDataSource:(id)source key:(id)key valueType:(unsigned long long)type account:(id)account;
- (id)_processedDefaultValuePromise:(id)promise;
- (void)processedDefaultValueWithCompletion:(UnknownBlock)completion;

@end
