//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSAccountCachedServerDataServiceInterface-Protocol.h"

@class v24@?0@";

@interface AMSBagUnderlyingDataPersistence : NSObject { // (Swift)
	v24@?0@"<AMSAccountCachedServerDataServiceInterface>"8@"NSError"16 directoryURL;
}

+ (id)persistenceWithDefaultDirectory;

- (nonnull instancetype)init;
- (nonnull instancetype)initWithDirectoryURL:(nullable NSURL *)url;
- (BOOL)persist:(id)persist error:(id *)error;
- (BOOL)removeUnderlyingDataFor:(id)_for error:(id *)error;
- (id)underlyingDataFor:(id)_for error:(id *)error;

@end
