//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSAccountCachedServerDataServiceInterface-Protocol.h"

@class v24@?0@";

@interface AMSBagURLQueryItemsBuilder : NSObject { // (Swift)
	v24@?0@"<AMSAccountCachedServerDataServiceInterface>"8@"NSError"16 clientInfo;
	v24@?0@"<AMSAccountCachedServerDataServiceInterface>"8@"NSError"16 profile;
	v24@?0@"<AMSAccountCachedServerDataServiceInterface>"8@"NSError"16 profileVersion;
	v24@?0@"<AMSAccountCachedServerDataServiceInterface>"8@"NSError"16 operatingSystem;
	v24@?0@"<AMSAccountCachedServerDataServiceInterface>"8@"NSError"16 operatingSystemVersion;
	v24@?0@"<AMSAccountCachedServerDataServiceInterface>"8@"NSError"16 deviceClass;
	v24@?0@"<AMSAccountCachedServerDataServiceInterface>"8@"NSError"16 buildVariant;
}

+ (id)storefrontFromQueryItems:(id)items;

- (nonnull instancetype)init;
- (nonnull instancetype)initWithClientInfo:(id)info profile:(id)profile profileVersion:(id)version;
- (nonnull instancetype)initWithClientInfo:(id)info profile:(id)profile profileVersion:(id)version operatingSystem:(id)system operatingSystemVersion:(id)version deviceClass:(id)_class buildVariant:(id)variant;
- (id)queryItemsWithCookies:(id)cookies storefront:(id)storefront;

@end
