//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSBiometricsSignatureRequest.h"
#include "AMSTask.h"

@interface AMSBiometricsSignatureTask : AMSTask

@property (readonly) AMSBiometricsSignatureRequest *request;

+ (struct __SecKey { struct __CFRuntimeBase { unsigned long long x0; _Atomic unsigned long long x1; } x0; struct __SecKeyDescriptor *x1; void *x2; } *)copyPrivateKeyWithStyle:(unsigned long long)style context:(id)context account:(id)account options:(id)options error:(id *)error;
+ (id)fetchDataToSignWithPublicKeyData:(id)data challenge:(id)challenge error:(id *)error;
+ (id)fetchPublicKeyDataFromPrivateKey:(struct __SecKey { struct __CFRuntimeBase { unsigned long long x0; _Atomic unsigned long long x1; } x0; struct __SecKeyDescriptor *x1; void *x2; } *)key error:(id *)error;
+ (id)signDataWithPrivateKey:(struct __SecKey { struct __CFRuntimeBase { unsigned long long x0; _Atomic unsigned long long x1; } x0; struct __SecKeyDescriptor *x1; void *x2; } *)key dataToSign:(id)sign error:(id *)error;

- (nonnull instancetype)initWithRequest:(id)request;
- (id)_performSignatureInProcess;
- (id)_performSignatureOutOfProcess;
- (id)performSignature;
- (id)performSignatureFromService;
- (void)regenerateAttestationKeys;
- (id)signWithPrivateKey:(struct __SecKey { struct __CFRuntimeBase { unsigned long long x0; _Atomic unsigned long long x1; } x0; struct __SecKeyDescriptor *x1; void *x2; } *)key error:(id *)error;

@end
