//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSMutablePromise.h"

@interface AMSBinaryPromise : NSObject

@property (retain, nonatomic, nullable) AMSBinaryPromise *retainedSelf;
@property (readonly, nonatomic) AMSMutablePromise *backingPromise;

+ (id)promiseWithAny:(id)any;
+ (id)promiseWithSuccess;
+ (id)promiseWithAll:(id)all;
+ (id)promiseWithFlattenedPromises:(id)promises;
+ (id)promiseWithPromise:(id)promise;
+ (id)promiseWithError:(nullable NSError *)error;

- (void)addFinishBlock:(UnknownBlock)block;
- (BOOL)resultWithError:(id *)error;
- (void)addErrorBlock:(UnknownBlock)block;
- (void)addSuccessBlock:(UnknownBlock)block;
- (void)waitUntilFinishedWithTimeout:(double)timeout;
- (id)promiseAdapter;
- (BOOL)resultWithTimeout:(double)timeout error:(id *)error;
- (void)waitUntilFinished;
- (void)resultWithCompletion:(UnknownBlock)completion;
- (UnknownBlock)completionHandlerAdapter;
- (id)catchWithBlock:(UnknownBlock)block;
- (BOOL)cancel;
- (BOOL)finishWithError:(nullable NSError *)error;
- (BOOL)finishWithSuccess;
- (id)continueWithBlock:(UnknownBlock)block;
- (BOOL)finishWithSuccess:(BOOL)success error:(nullable NSError *)error;
- (void)resultWithTimeout:(double)timeout completion:(UnknownBlock)completion;
- (void)stopRetainingSelf;
- (nonnull instancetype)init;
- (BOOL)finishWithPromise:(id)promise;
- (id)thenWithBlock:(UnknownBlock)block;
- (id)thenWithPromiseBlock:(UnknownBlock)block;
- (nonnull instancetype)initWithBackingPromise:(id)promise;
- (id)continueWithPromiseBlock:(UnknownBlock)block;
- (id)catchWithPromiseBlock:(UnknownBlock)block successValue:(id)value;

@end
