//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSBagCachedValueUpdateHandlers.h"
#include "AMSBagDataSourceProtocol-Protocol.h"
#include "AMSBagProtocol-Protocol.h"
#include "AMSBagUnderlyingData.h"
#include "AMSBagUnderlyingDataPersistence.h"
#include "AMSProcessInfo.h"

@protocol OS_dispatch_queue;

@interface AMSBag : NSObject <AMSBagProtocol>

@property (readonly) dispatch_queue_t changeNotificationQueue;
@property (readonly) dispatch_queue_t persistenceQueue;
@property (readonly) AMSBagUnderlyingDataPersistence *persistence;
@property (retain, nullable) AMSBagUnderlyingData *temporaryPreloadedBagData;
@property BOOL persistenceAPIWasCalled;
@property struct os_unfair_lock_s { unsigned int x0; } updateHandlerConsistencyLock;
@property (readonly) BOOL persistenceIsEnabled;
@property (retain, nullable) id <AMSBagDataSourceProtocol> dataSource;
@property (copy, nullable) AMSProcessInfo *processInfo;
@property (readonly) AMSBagCachedValueUpdateHandlers *updateHandlers;
@property (readonly) NSString *descriptionExtended;
@property (readonly) BOOL expired;
@property (readonly) NSDate *expirationDate;
@property (readonly, copy) NSString *profile;
@property (readonly, copy) NSString *profileVersion;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)bagForProfile:(id)profile profileVersion:(id)version;
+ (id)_bagForProfile:(id)profile profileVersion:(id)version processInfo:(id)info accountProvider:(id)provider loadURLOverlay:(nullable NSURL *)urloverlay;
+ (id)bagCache;
+ (id)bagForProfile:(id)profile profileVersion:(id)version processInfo:(id)info;
+ (id)bagForProfile:(id)profile profileVersion:(id)version processInfo:(id)info account:(id)account;
+ (id)bagForProfile:(id)profile profileVersion:(id)version processInfo:(id)info account:(id)account loadURLOverlay:(nullable NSURL *)urloverlay;
+ (id)bagForProfile:(id)profile profileVersion:(id)version processInfo:(id)info loadURLOverlay:(nullable NSURL *)urloverlay;
+ (void)resetBagCache;
+ (id)sharedPersistenceQueue;
+ (id)sharedPersistenceWithDefaultDirectory;
+ (unsigned long long)uninitializedToken;

- (void)setDefaultValue:(id)value forKey:(id)key;
- (BOOL)isLoaded;
- (nonnull instancetype)initWithDataSource:(id)source;
- (id)arrayForKey:(id)key;
- (BOOL)isExpired;
- (id)integerForKey:(id)key;
- (id)boolForKey:(id)key;
- (id)doubleForKey:(id)key;
- (id)stringForKey:(id)key;
- (void)createSnapshotWithCompletion:(UnknownBlock)completion;
- (id)URLForKey:(id)key;
- (nullable NSDictionary *)dictionaryForKey:(id)key;
- (id)URLForKey:(id)key account:(id)account;
- (id)URLFromURLString:(nullable NSURL *)urlstring;
- (id)URLFromURLString:(nullable NSURL *)urlstring account:(id)account;
- (id)_availableValuesFromCachedData:(id)data keys:(id)keys partialIdentifier:(id)identifier expirationDate:(id)date updateHandler:(UnknownBlock)handler outToken:(unsigned long long *)token;
- (id)_availableValuesFromPersistedBagData:(id)data error:(nullable NSError *)error keys:(id)keys partialIdentifier:(id)identifier updateHandler:(UnknownBlock)handler outToken:(unsigned long long *)token;
- (void)_configureDataSourceHandlers;
- (id)_initWithDataSource:(id)source persistence:(id)persistence persistenceQueue:(id)queue updateHandlers:(id)handlers shouldConfigureDataSourceHandlers:(BOOL)handlers;
- (void)_loadAndPersistBag;
- (void)_persistBagDictionary:(nullable NSDictionary *)dictionary withIdentifier:(id)identifier partialIdentifier:(id)identifier expirationDate:(id)date onlyIfPreExisting:(BOOL)existing;
- (id)_temporaryDictionary;
- (id)cachedValuesForKeys:(id)keys observationToken:(unsigned long long *)token updateHandler:(UnknownBlock)handler;
- (nonnull instancetype)initWithDataSource:(id)source persistenceDirectoryURL:(nullable NSURL *)url persistenceQueue:(id)queue changeHandlerQueue:(id)queue shouldConfigureDataSourceHandlers:(BOOL)handlers;
- (nonnull instancetype)initWithDataSource:(id)source shouldConfigureDataSourceHandlers:(BOOL)handlers;
- (void)removeObserverWithToken:(unsigned long long)token;
- (void)waitUntilPersistenceWorkComplete;

@end
