//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@interface AMSBlinder : NSObject // (Swift)

+ (id)unblindedInputWithPrivateInput:(id)input;
+ (id)finalizeBlindedDataWithPrivateInput:(id)input timeStamp:(id)stamp adamId:(id)id publicInput:(id)input signatureType:(id)type serverData:(id)data error:(id *)error;
+ (id)generateRandomPrivateInput;
+ (id)generateTimestamp;
+ (id)makeBlindedDataWithPrivateInputData:(id)data;
+ (id)publicInputWithComponents:(id)components adamID:(id)id isRedownload:(BOOL)redownload priceType:(id)type timestamp:(id)timestamp;
+ (void)removeCachedClientForPrivateInput:(id)input;

- (nonnull instancetype)init;

@end
