//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSBagAccountProvider-Protocol.h"
#include "AMSMetricsActivity.h"
#include "AMSMetricsLoadURLOverlay.h"
#include "AMSProcessInfo.h"
#include "AMSTask.h"

@interface AMSBagNetworkTask : AMSTask {
	AMSMetricsActivity *_activity;
}

@property (readonly, nonatomic) id <AMSBagAccountProvider> accountProvider;
@property (readonly, nonatomic) NSString *logKey;
@property (readonly, nonatomic) AMSMetricsLoadURLOverlay *loadURLOverlay;
@property (retain, nullable) AMSProcessInfo *clientInfo;
@property (retain, nullable) NSString *profile;
@property (retain, nullable) NSString *profileVersion;

+ (id)_queryItemsForClientInfo:(id)info profile:(id)profile profileVersion:(id)version cookieNames:(id)names accountProvider:(id)provider;
+ (id)_requestIdentifierForQueryItems:(id)items;
+ (id)_defaultURLCookieNames;
+ (BOOL)_shouldReloadDataForOriginalCookies:(id)cookies newCookies:(id)cookies;
+ (id)requestPartialIdentifierForClientInfo:(id)info profile:(id)profile profileVersion:(id)version;
+ (id)_cookiesForNames:(id)names clientInfo:(id)info account:(id)account;
+ (id)_setStorefrontFromURLResponse:(nullable NSURL *)urlresponse bagData:(id)data;
+ (id)_bagDataByApplyingOverridesToBagData:(id)data;
+ (id)_URLCookieNamesForProfile:(id)profile;
+ (id)_bagDataByApplyingOverridesToBagData:(id)data overrides:(id)overrides ignoredKeys:(id)keys inserts:(id)inserts;
+ (id)_queryItemsForClientInfo:(id)info profile:(id)profile profileVersion:(id)version cookieNames:(id)names account:(id)account storefront:(id)storefront;
+ (void)_setURLCookieNames:(id)names forProfile:(id)profile;
+ (id)_requestIdentifierForQueryItems:(id)items prefix:(id)prefix;

- (void)_updateStorefrontSuffixIfNecessaryWithBagData:(id)data;
- (id)activity;
- (id)performFetch;
- (nonnull instancetype)initWithClientInfo:(id)info profile:(id)profile profileVersion:(id)version accountProvider:(id)provider loadURLOverlay:(nullable NSURL *)urloverlay;
- (id)_performFetchWithAttemptedCount:(unsigned long long)count account:(id)account storefront:(id)storefront;
- (void)setActivity:(id)activity;
- (id)_createRequestWithQueryItems:(id)items;
- (BOOL)_shouldRetryForResult:(id)result cookieNames:(id)names urlCookies:(id)cookies responseStorefront:(id)storefront;

@end
