//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSAccountCachedServerDataServiceInterface-Protocol.h"
#include "AMSResponseDecoding-Protocol.h"

@class v24@?0@";

@interface AMSCodableResponseDecoder : NSObject <AMSResponseDecoding> { // (Swift)
	v24@?0@"<AMSAccountCachedServerDataServiceInterface>"8@"NSError"16 rootClass;
}

- (id)resultFromResult:(id)result error:(id *)error;
- (nonnull instancetype)init;
- (nonnull instancetype)initWithRootClass:(Class)_class;

@end
