//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSSQLiteConnection.h"
#include "AMSSQLiteConnectionDelegate-Protocol.h"

@interface AMSCookieDatabase : NSObject <AMSSQLiteConnectionDelegate>

@property (readonly) AMSSQLiteConnection *connection;
@property (readonly, copy) NSString *dbPath;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)cookieDatabaseForIdentifiers:(id)identifiers error:(id *)error;
+ (void)_cleanUpProtectionClassAtPath:(id)path fileManager:(id)manager;
+ (id)_databasePathForIdentifier:(id)identifier error:(id *)error;
+ (id)_cleanUpCookieDatabaseUsingFileManager:(id)manager defaults:(id)defaults;
+ (id)_dataVaultPathForIdentifier:(id)identifier error:(id *)error;
+ (id)cleanUpCookieDatabasesWithValidIdentifiers:(id)identifiers fileManager:(id)manager defaults:(id)defaults;
+ (id)cookieDatabaseForIdentifiers:(id)identifiers error:(id *)error fileManager:(id)manager;
+ (id)_databasePathForIdentifiers:(id)identifiers fileManager:(id)manager error:(id *)error;
+ (id)cookieDatabaseForIdentifier:(id)identifier error:(id *)error;
+ (id)databasePathForIdentifiers:(id)identifiers error:(id *)error;
+ (id)_rootDataVaultPathWithError:(id *)error;

- (BOOL)_removeCookieProperties:(id)properties error:(id *)error;
- (void)_bindCookieProperties:(id)properties column:(unsigned long long)column position:(int)position using:(id)_using;
- (id)_cookieDictionaryForCursor:(id)cursor;
- (BOOL)connection:(id)connection needsResetForCorruptionError:(nullable NSError *)error error:(out id *)error;
- (void)close;
- (nonnull instancetype)initWithConnection:(id)connection path:(id)path;
- (id)cookiePropertiesWithError:(id *)error;
- (BOOL)_executeStatement:(id)statement columns:(id)columns forCookieProperties:(id)properties error:(id *)error;
- (void)dealloc;
- (BOOL)updateCookiesWithCookiePropertiesToAdd:(id)add cookiePropertiesToRemove:(id)remove error:(id *)error;
- (BOOL)_addCookieProperties:(id)properties error:(id *)error;

@end
