//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSBagConsumer-Protocol.h"
#include "AMSBagProtocol-Protocol.h"
#include "AMSProcessInfo.h"
#include "AMSPromise.h"
#include "AMSTask.h"
#include "AMSURLRequestEncoder.h"
#include "AMSURLSession.h"

@class ACAccount;

@interface AMSCarrierOfferRegistrationTask : AMSTask <AMSBagConsumer>

@property (readonly) NSArray *carriers;
@property (readonly) AMSURLRequestEncoder *checkOfferRequestEncoder;
@property (readonly) NSString *deviceGUID;
@property (readonly) NSString *msisdn;
@property (readonly) AMSURLRequestEncoder *registrationRequestEncoder;
@property (readonly) AMSURLSession *urlSession;
@property (readonly) AMSPromise *pacTokenPromise;
@property (readonly) Class privacyMappingResolver;
@property (readonly) ACAccount *account;
@property (readonly) id <AMSBagProtocol> bag;
@property (retain, nullable) AMSProcessInfo *clientInfo;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)createBagForSubProfile;
+ (id)bagSubProfileVersion;
+ (id)bagSubProfile;
+ (id)bagKeySet;
+ (id)pollingIntervalFromBag:(id)bag;
+ (id)invalidParameterError:(nullable NSError *)error;

- (id)perform;
- (id)_allowedServiceIdentifiersFromPrivacyMapping:(id)mapping;
- (id)_checkOffersBodyLimitedByAllowedServiceIdentifiers:(id)identifiers;
- (id)_checkOffersRequestLimitedByAllowedServiceIdentifiers:(id)identifiers;
- (id)_evaluationRequiredPrivacyMappingPair;
- (id)_hasOffersLimitedByAllowedServiceIdentifiers:(id)identifiers;
- (id)_includesAllowedCarrier;
- (id)_pacToken;
- (id)_parseCheckOffersResult:(id)result;
- (id)_performRegistrationFlowLimitedByAllowedServiceIdentifiers:(id)identifiers;
- (id)_registerCarrierOffersToAccountLimitedByAllowedServiceIdentifiers:(id)identifiers;
- (id)_registrationBodyLimitedByAllowedServiceIdentifiers:(id)identifiers;
- (id)_registrationRequestLimitedByAllowedServiceIdentifiers:(id)identifiers;
- (nonnull instancetype)initWithAccount:(id)account bag:(id)bag;
- (nonnull instancetype)initWithAccount:(id)account bag:(id)bag carriers:(id)carriers checkOfferRequestEncoder:(id)encoder deviceGUID:(id)guid msisdn:(id)msisdn pacTokenPromise:(id)promise privacyMappingResolver:(Class)resolver registrationRequestEncoder:(id)encoder urlSession:(id)session;
- (nonnull instancetype)initWithAccount:(id)account bag:(id)bag carriers:(id)carriers deviceGUID:(id)guid msisdn:(id)msisdn;

@end
