//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSCarrierLinkParams.h"

@interface AMSCarrierLinkResult : NSObject <NSSecureCoding>

@property (readonly) NSError *error;
@property (readonly) NSDictionary *response;
@property (readonly) NSNumber *statusCode;
@property (readonly) NSString *channelCustomerId;
@property (readonly) AMSCarrierLinkParams *linkParams;
@property (readonly) NSString *productCode;

+ (BOOL)supportsSecureCoding;

- (void)encodeWithCoder:(nullable NSCoder *)coder;
- (nonnull instancetype)initWithCoder:(nullable NSCoder *)coder;
- (nonnull instancetype)initWithChannelLinkResult:(id)result;
- (nonnull instancetype)initWithLinkParams:(id)params channelCustomerId:(id)id productCode:(id)code statusCode:(id)code error:(nullable NSError *)error;
- (nonnull instancetype)initWithResponse:(id)response linkParams:(id)params;

@end
