//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSBagConsumer-Protocol.h"
#include "AMSBagProtocol-Protocol.h"
#include "AMSCampaignAttributor.h"
#include "AMSProcessInfo.h"
#include "AMSTask.h"
#include "AMSURLSession.h"

@class ACAccount;

@interface AMSCampaignAttributionTask : AMSTask <AMSBagConsumer>

@property (readonly) AMSURLSession *URLSession;
@property (retain, nonatomic, nullable) AMSCampaignAttributor *campaignAttributor;
@property (retain, nullable) ACAccount *account;
@property (readonly) id <AMSBagProtocol> bag;
@property (retain, nullable) AMSProcessInfo *clientInfo;
@property (copy, nullable) NSArray *additionalQueryItems;
@property (readonly) NSURL *URL;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)createBagForSubProfile;
+ (id)bagSubProfileVersion;
+ (id)bagSubProfile;
+ (id)bagKeySet;

- (id)perform;
- (nonnull instancetype)initWithURL:(nullable NSURL *)url bag:(id)bag;
- (nonnull instancetype)initWithURL:(nullable NSURL *)url bag:(id)bag URLSession:(nullable NSURL *)urlsession;

@end
