//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSCookieServiceInterface-Protocol.h"

@interface AMSCookieService : NSObject <NSCacheDelegate, AMSCookieServiceInterface>

@property (readonly) struct os_unfair_lock_s { unsigned int x0; } inMemoryStorageLock;
@property (readonly) NSCache *inMemoryStorage;
@property BOOL isObservingNotifications;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)sharedService;
+ (BOOL)_currentUserIsSystemSetupUser;
+ (BOOL)_isEntitledForDirectCookieAccess;

- (void)cache:(id)cache willEvictObject:(id)object;
- (id)getCookiePropertiesForAccount:(id)account cookieDatabaseOnly:(BOOL)only error:(id *)error;
- (void)_unregisterFromCookieChangeNotifications;
- (void)getCookiePropertiesForAccount:(id)account cookieDatabaseOnly:(BOOL)only withCompletion:(UnknownBlock)completion;
- (BOOL)_useInMemoryCacheForAccount:(id)account;
- (id)_cachedCookiePropertiesForAccount:(id)account;
- (void)getCookiePropertiesForAccount:(id)account withCompletion:(UnknownBlock)completion;
- (void)clearDanglingCookieDatabasesWithCompletion:(UnknownBlock)completion;
- (void)_registerForCookieChangeNotifications;
- (nonnull instancetype)init;
- (void)clearCookiePropertyCacheForAccount:(id)account;
- (void)updateCookiesWithCookiePropertiesToAdd:(id)add cookiePropertiesToRemove:(id)remove forAccount:(id)account withCompletion:(UnknownBlock)completion;
- (void)getCookieDatabasePathForAccount:(id)account withCompletion:(UnknownBlock)completion;
- (void)clearCookiePropertyCache;
- (void)_cacheCookieProperties:(id)properties forAccount:(id)account;
- (id)getCookiePropertiesForAccount:(id)account error:(id *)error;

@end
