//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@interface AMSCookieStorage : NSObject

+ (id)updateCookiesWithCookiesToAdd:(id)add cookiesToRemove:(id)remove forAccount:(id)account;
+ (id)cookiesForAccount:(id)account error:(id *)error;
+ (BOOL)updateCookiesWithCookiesToAdd:(id)add cookiesToRemove:(id)remove forAccount:(id)account error:(id *)error;
+ (id)cookiesForAccount:(id)account cookieDatabaseOnly:(BOOL)only error:(id *)error;

@end
