//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSBagConsumer-Protocol.h"
#include "AMSBagProtocol-Protocol.h"
#include "AMSCarrierLinkParams.h"
#include "AMSEngagement.h"
#include "AMSMetrics.h"
#include "AMSProcessInfo.h"
#include "AMSPromise.h"
#include "AMSTask.h"
#include "AMSURLProtocolDelegate-Protocol.h"
#include "AMSURLRequestEncoder.h"
#include "AMSURLSession.h"

@class ACAccount;
@protocol AMSCarrierLinkTaskDelegate;

@interface AMSCarrierLinkTask : AMSTask <AMSURLProtocolDelegate, NSURLSessionDelegate, AMSBagConsumer>

@property (retain, nullable) ACAccount *account;
@property (readonly) AMSEngagement *engagementHandler;
@property (readonly) NSString *guid;
@property (readonly) AMSMetrics *metrics;
@property (readonly) NSString *msisdn;
@property (readonly) AMSURLRequestEncoder *requestEncoder;
@property (readonly) AMSURLSession *urlSession;
@property (readonly) AMSPromise *pacTokenPromise;
@property (retain, nullable) NSDictionary *additionalLinkingParameters;
@property (readonly) id <AMSBagProtocol> bag;
@property (retain, nullable) AMSProcessInfo *clientInfo;
@property (weak) id <AMSCarrierLinkTaskDelegate> delegate;
@property (readonly) AMSCarrierLinkParams *linkParams;
@property (copy, nullable) NSDictionary *metricsOverlay;
@property (readonly) NSString *productCode;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)createBagForSubProfile;
+ (id)bagSubProfileVersion;
+ (id)bagSubProfile;
+ (id)bagKeySet;

- (void)AMSURLSession:(id)amsurlsession task:(id)task handleEngagementRequest:(id)request completion:(UnknownBlock)completion;
- (void)AMSURLSession:(id)amsurlsession task:(id)task handleAuthenticateRequest:(id)request completion:(UnknownBlock)completion;
- (id)perform;
- (void)AMSURLSession:(id)amsurlsession task:(id)task handleDialogRequest:(id)request completion:(UnknownBlock)completion;
- (id)_linkParameters;
- (id)_performLinking;
- (id)_linkURLRequest;
- (void)_delegateHandleEngagementRequest:(id)request completion:(UnknownBlock)completion;
- (id)_linkFailureFromResult:(id)result;
- (id)_metricsEventFromCarrierLinkResult:(id)result error:(nullable NSError *)error;
- (id)_pacToken;
- (void)_performDelegateAuthenticationWithRequest:(id)request completion:(UnknownBlock)completion;
- (id)_performLinkingWithValidations;
- (id)_promptForAccount;
- (id)_recordEngagementMetricsEvent:(id)event;
- (id)_resultDecodingURLResult:(nullable NSURL *)urlresult;
- (nonnull instancetype)initWithAccount:(id)account bag:(id)bag engagementHandler:(id)handler guid:(id)guid linkParams:(id)params metrics:(id)metrics msisdn:(id)msisdn pacTokenPromise:(id)promise productCode:(id)code requestEncoder:(id)encoder urlSession:(id)session;
- (nonnull instancetype)initWithAccount:(id)account bag:(id)bag linkParams:(id)params productCode:(id)code;

@end
