//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSAccountCachedServerDataServiceInterface-Protocol.h"

@class v24@?0@";

@interface AMSContiguousActionPerformer : NSObject { // (Swift)
	v24@?0@"<AMSAccountCachedServerDataServiceInterface>"8@"NSError"16 lock;
	v24@?0@"<AMSAccountCachedServerDataServiceInterface>"8@"NSError"16 queue;
	v24@?0@"<AMSAccountCachedServerDataServiceInterface>"8@"NSError"16 suspendableQueue;
}

- (void)sync:(UnknownBlock)sync;
- (nonnull instancetype)init;
- (void)async:(UnknownBlock)async;
- (nonnull instancetype)initWithQueue:(id)queue;
- (void)dealloc;
- (void)continueContiguousActionWithIdentifier:(unsigned long long)identifier withBlock:(UnknownBlock)block;
- (void)finishContiguousActionWithIdentifier:(unsigned long long)identifier;
- (unsigned long long)performInitialContiguousActionWithBlock:(UnknownBlock)block;

@end
