//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSBagProtocol-Protocol.h"
#include "AMSTask.h"
#include "AMSURLProtocolDelegate-Protocol.h"

@class ACAccount;

@interface AMSChildAccountStorefrontTask : AMSTask

@property (nonatomic, readonly) ACAccount *parentAccount;
@property (nonatomic, readonly) NSNumber *childDSID;
@property (nonatomic, readonly) id <AMSBagProtocol> bag;
@property (nonatomic, weak) id <AMSURLProtocolDelegate, NSURLSessionDelegate> delegate;

- (id)perform;
- (nonnull instancetype)init;
- (nonnull instancetype)initWithParentAccount:(id)account childDSID:(nullable NSNumber *)dsID bag:(id)bag;

@end
