//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@interface AMSChannelLinkRequestParametersBuilder : NSObject // (Swift)

+ (void)linkRequestParametersWithGuid:(NSString *)guid linkParams:(NSString *)params productCode:(NSString *)code additionalParameters:(NSDictionary *)parameters customerID:(NSString *)id pacPromise:(id)promise completionHandler:(UnknownBlock)handler;

- (nonnull instancetype)init;

@end
