//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSChannelLinkParams.h"

@interface AMSChannelLinkResult : NSObject <NSSecureCoding>

@property (readonly) NSError *error;
@property (readonly) NSDictionary *response;
@property (readonly) NSNumber *statusCode;
@property (readonly) NSString *channelCustomerId;
@property (readonly) AMSChannelLinkParams *linkParams;
@property (readonly) NSString *productCode;
@property (readonly) NSSet *postLinkingFields;
@property (readonly) NSString *subscriptionId;
@property (readonly) NSSet *supplementaryFields;

+ (BOOL)supportsSecureCoding;

- (void)encodeWithCoder:(nullable NSCoder *)coder;
- (nonnull instancetype)initWithCoder:(nullable NSCoder *)coder;
- (nonnull instancetype)initWithCarrierLinkResult:(id)result;
- (nonnull instancetype)initWithResponse:(id)response linkParams:(id)params;
- (nonnull instancetype)initWithResponse:(id)response linkParams:(id)params supplementaryFields:(id)fields;

@end
