//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@interface AMSCommerceMigrator : NSObject

+ (id)_cookiesFromURL:(nullable NSURL *)url;
+ (id)_createAccountFromKnownAccountsDictionary:(nullable NSDictionary *)dictionary accountTypeIdentifier:(id)identifier;
+ (void)_migrateAppStoreInformationIntoAccounts:(id)accounts;
+ (void)_migrateBiometricsStateIntoAccounts:(id)accounts;
+ (void)_migrateBooksInformationIntoAccounts:(id)accounts;
+ (id)_migrateCommerceAccounts;
+ (void)_migrateConfiguratorInformationIntoAccounts:(id)accounts;
+ (void)_migrateCookiesIntoAccounts:(id)accounts;
+ (id)_migrateLegacyCommerceAccounts;
+ (void)_migratePrivacyAcknowledgementIntoAccounts:(id)accounts;
+ (void)_migrateiTunesInformation;
+ (id)_primaryDSIDFromLegacyPreferencesDomain:(id)domain clientType:(id)type serverType:(id)type;
+ (void)_removeAccountRelatedDefaultsUsingAccounts:(id)accounts;
+ (void)migrateCommerceAccountsWithOptions:(id)options;

@end
