//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSBagProtocol-Protocol.h"
#include "AMSTask.h"

@interface AMSCardEnrollmentEligibilityTask : AMSTask

@property (retain, nullable) id <AMSBagProtocol> bag;
@property (readonly, copy) NSString *countryCode;

- (nonnull instancetype)initWithBag:(id)bag;
- (nonnull instancetype)initWithCountryCode:(id)code;
- (unsigned long long)_cardTypeForPassTypeIdentifier:(id)identifier serialNumber:(id)number;
- (id)_checkForCombinediTunesAccount;
- (id)_checkThatSilentEnrollmentIsEnabled;
- (id)_createEligibilityRequestWithBag:(id)bag iTunesAccount:(id)account iCloudAccount:(id)account cardType:(unsigned long long)type;
- (id)_mediaType;
- (id)_performSilentEnrollmentCheckWithRequest:(id)request;
- (void)canWriteBillingInfoWithPassTypeIdentifier:(id)identifier serialNumber:(id)number completion:(UnknownBlock)completion;
- (nonnull instancetype)initWithBag:(id)bag countryCode:(id)code;
- (id)performCanWriteBillingInfoQueryWithPassTypeIdentifier:(id)identifier serialNumber:(id)number;

@end
