//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSBagConsumer-Protocol.h"
#include "AMSBagProtocol-Protocol.h"
#include "AMSProcessInfo.h"
#include "AMSTask.h"

@interface AMSClipMediaTask : AMSTask <AMSBagConsumer>

@property (retain, nullable) id <AMSBagProtocol> bag;
@property (retain, nullable) NSString *bundleID;
@property (retain, nullable) NSString *clientID;
@property (retain, nullable) AMSProcessInfo *clientInfo;
@property (retain, nullable) NSNumber *externalVersionID;
@property (retain, nullable) NSURL *URL;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)createBagForSubProfile;
+ (id)bagSubProfileVersion;
+ (id)bagSubProfile;
+ (id)bagKeySet;

- (id)perform;
- (id)_componentsPromise;
- (id)_performJourneysLookup;
- (id)_performNetworkLookup;
- (nonnull instancetype)initWithClientID:(id)id bundleID:(id)id URL:(nullable NSURL *)url bag:(id)bag;
- (nonnull instancetype)initWithClientID:(id)id bundleID:(id)id bag:(id)bag;

@end
