//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSBagProtocol-Protocol.h"
#include "AMSProcessInfo.h"

@interface AMSContractBagShim : NSObject <AMSBagProtocol>

@property (readonly, nonatomic) NSObject *bagContract;
@property (readonly) BOOL expired;
@property (readonly) NSDate *expirationDate;
@property (readonly, copy) NSString *profile;
@property (readonly, copy) NSString *profileVersion;
@property (readonly, copy, nonatomic) AMSProcessInfo *processInfo;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)_callSelector:(SEL)selector onBagContract:(id)contract;

- (nonnull instancetype)initWithBagContract:(id)contract;
- (BOOL)isLoaded;
- (id)arrayForKey:(id)key;
- (BOOL)isExpired;
- (id)integerForKey:(id)key;
- (id)boolForKey:(id)key;
- (id)doubleForKey:(id)key;
- (id)stringForKey:(id)key;
- (void)createSnapshotWithCompletion:(UnknownBlock)completion;
- (id)URLForKey:(id)key;
- (nullable NSDictionary *)dictionaryForKey:(id)key;
- (id)_bagValueForBagKey:(id)key bagValueType:(unsigned long long)type;
- (SEL)_selectorForBagKey:(id)key;

@end
