//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSDialogAction.h"
#include "AMSMetricsEvent.h"

@interface AMSDialogRequest : NSObject <NSSecureCoding, NSCopying>

@property BOOL allowsNativeWatchCancelPlacement;
@property (readonly) NSDictionary *appearanceInfo;
@property (copy, nullable) NSArray *buttonActions;
@property (retain, nullable) AMSDialogAction *cancelAction;
@property (copy, nullable) NSDictionary *clickstreamMetricsEvent;
@property (retain, nullable) AMSDialogAction *defaultAction;
@property (copy, nullable) NSURL *iconBundleURL;
@property (copy, nullable) NSURL *iconURL;
@property (copy, nullable) NSString *identifier;
@property (copy, nullable) NSString *logKey;
@property (copy, nullable) NSString *message;
@property (copy, nullable) NSString *messageAccessibilityLabel;
@property (copy, nullable) AMSMetricsEvent *metricsEvent;
@property (copy, nullable) NSString *preferredButtonActionIdentifier;
@property BOOL preventsCancelButtonStyle;
@property long long style;
@property (copy, nullable) NSString *systemSymbolName;
@property (copy, nullable) NSArray *textFields;
@property (copy, nullable) NSString *title;
@property (copy, nullable) NSString *titleAccessibilityLabel;
@property (copy, nullable) NSDictionary *userInfo;

+ (BOOL)supportsSecureCoding;
+ (id)requestWithTitle:(id)title message:(id)message;

- (nonnull instancetype)initWithError:(nullable NSError *)error;
- (nonnull instancetype)copyWithZone:(nullable struct _NSZone *)zone;
- (void)encodeWithCoder:(nullable NSCoder *)coder;
- (nonnull instancetype)init;
- (nonnull NSString *)description;
- (nonnull instancetype)initWithCoder:(nullable NSCoder *)coder;
- (nonnull instancetype)initWithTitle:(id)title message:(id)message;
- (void)addTextField:(id)field;
- (void)addButtonAction:(id)action;
- (nonnull instancetype)initWithTitle:(id)title message:(id)message appearanceInfo:(id)info;
- (id)locateActionWithIdentifier:(id)identifier;
- (void)replaceAction:(id)action;

@end
