//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSDialogRequest.h"
#include "AMSMetricsEvent.h"

@class NSURLRequest;

@interface AMSDialogAction : NSObject <NSSecureCoding, NSCopying>

@property BOOL ams_commerceUIURL;
@property long long ams_actionType;
@property (retain, nullable) NSString *ams_buyParams;
@property (retain, nullable) NSDictionary *ams_formData;
@property (retain, nullable) NSDictionary *ams_buttonDictionary;
@property (retain, nullable) NSDictionary *ams_expandableInfoDictionary;
@property (retain, nullable) NSDictionary *ams_metricsDictionary;
@property (retain, nullable) NSURL *ams_rawURL;
@property BOOL ams_resolvedInterruption;
@property BOOL ams_shouldRetry;
@property (retain, nullable) NSString *ams_subtarget;
@property BOOL ams_tidContinue;
@property long long ams_URLType;
@property (copy, nullable) NSDictionary *clickstreamMetricsEvent;
@property (copy, nullable) NSURL *deepLink;
@property (copy, nullable) NSString *identifier;
@property BOOL inferLinkDestination;
@property (retain, nullable) NSString *kind;
@property (copy, nullable) AMSMetricsEvent *metricsEvent;
@property (copy, nullable) NSURLRequest *request;
@property long long style;
@property (copy, nullable) AMSDialogRequest *dialogRequest;
@property (copy, nullable) NSString *title;
@property (copy, nullable) NSURL *iconURL;
@property (copy, nullable) NSDictionary *parameters;
@property BOOL requiresDelegate;
@property (retain, nullable) NSMutableDictionary *userInfo;
@property (copy, nullable) NSString *accessibilityIdentifier;
@property BOOL shouldRetry;

+ (BOOL)supportsSecureCoding;
+ (id)actionWithTitle:(id)title;
+ (id)actionWithTitle:(id)title identifier:(id)identifier;
+ (id)actionWithTitle:(id)title style:(long long)style;

- (nonnull instancetype)copyWithZone:(nullable struct _NSZone *)zone;
- (void)encodeWithCoder:(nullable NSCoder *)coder;
- (nonnull instancetype)init;
- (nonnull NSString *)description;
- (nonnull instancetype)initWithCoder:(nullable NSCoder *)coder;
- (void)ams_setURLType:(long long)urltype;
- (void)ams_setActionType:(long long)type;
- (void)ams_setButtonDictionary:(nullable NSDictionary *)dictionary;
- (void)ams_setBuyParams:(id)params;
- (void)ams_setCommerceUIURL:(BOOL)uiurl;
- (void)ams_setExpandableInfoDictionary:(nullable NSDictionary *)dictionary;
- (void)ams_setFormData:(id)data;
- (void)ams_setMetricsDictionary:(nullable NSDictionary *)dictionary;
- (void)ams_setRawURL:(nullable NSURL *)url;
- (void)ams_setResolvedInterruption:(BOOL)interruption;
- (void)ams_setShouldRetry:(BOOL)retry;
- (void)ams_setSubtarget:(id)subtarget;
- (void)ams_setTidContinue:(BOOL)_continue;

@end
