//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSDoubleLinkedListNode.h"

@interface AMSDoubleLinkedList : NSObject

@property (retain, nullable) NSString *listIdentifier;
@property (readonly) NSArray *allNodes;
@property (readonly) unsigned long long count;
@property (retain, nullable) AMSDoubleLinkedListNode *head;
@property (retain, nullable) AMSDoubleLinkedListNode *tail;

- (id)insertObject:(id)object;
- (void)removeNode:(id)node;
- (void)appendNode:(id)node;
- (void)insertNode:(id)node;
- (nonnull instancetype)init;
- (nonnull NSString *)description;
- (void)removeAllNodes;
- (id)appendObject:(id)object;

@end
