//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSBagProtocol-Protocol.h"
#include "AMSTask.h"

@class ACAccount;

@interface AMSDeveloperSilentAuthTokenUpdateTask : AMSTask

@property (readonly, copy) NSString *bundleId;
@property (readonly) ACAccount *account;
@property (readonly) id <AMSBagProtocol> bag;
@property (readonly) NSString *mediaType;

- (nonnull instancetype)initWithBundleId:(id)id account:(id)account bag:(id)bag;
- (nonnull instancetype)initWithBundleId:(id)id account:(id)account mediaType:(id)type bag:(id)bag;
- (id)performWithToken:(id)token;

@end
