//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@interface AMSDeveloperSilentAuthToken : NSObject

@property (nonatomic, readonly) NSString *token;
@property (nonatomic, readonly) unsigned long long consentStatus;
@property (nonatomic, readonly) BOOL hasConsented;

- (nonnull instancetype)init;
- (nonnull instancetype)initWithConsentStatus:(unsigned long long)status token:(id)token;

@end
