//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSBiometricsSignatureRequest.h"
#include "AMSDelegateAuthenticateTask.h"
#include "AMSDelegatePaymentSheetTask.h"
#include "AMSDelegatePurchaseRequest.h"
#include "AMSPaymentSheetResult.h"
#include "AMSURLResult.h"
#include "AMSURLTaskInfo.h"

@interface AMSDelegatePurchaseTask : AMSDelegateAuthenticateTask

@property (retain, nullable) AMSBiometricsSignatureRequest *biometricsRequest;
@property (retain, nullable) AMSURLResult *delegateAuthResult;
@property (retain, nullable) AMSURLTaskInfo *delegateAuthTaskInfo;
@property (retain, nullable) AMSPaymentSheetResult *paymentSheetResult;
@property (retain, nullable) AMSDelegatePaymentSheetTask *paymentSheetTask;
@property (readonly) AMSDelegatePurchaseRequest *request;

- (BOOL)cancel;
- (void)AMSURLSession:(id)amsurlsession task:(id)task handleAuthenticateRequest:(id)request completion:(UnknownBlock)completion;
- (id)_fetchDelegateAuthResultWithRequest:(id)request error:(id *)error;
- (id)_finishWithDelegateAuthenticateResult:(id)result resultError:(nullable NSError *)error outError:(id *)error;
- (void)_parseBiometricsSignatureRequestFromTask:(id)task;
- (id)_performAuthenticateTaskWithPaymentSheet;
- (id)_performAuthenticateTaskWithPaymentSheetResult:(id)result;
- (id)_performPaymentSheetTask;
- (id)_urlRequestForDelegateAuthWithError:(id *)error;
- (id)_urlRequestParameters;
- (id)delegateAuthenticateUrl;
- (nonnull instancetype)initWithDelegatePurchaseRequest:(id)request bag:(id)bag account:(id)account;
- (id)performDelegatePurchase;

@end
