//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSBag.h"
#include "AMSBagConsumer-Protocol.h"
#include "AMSTask.h"
#include "AMSURLProtocolDelegate-Protocol.h"

@class ACAccount;

@interface AMSDelegateAuthenticateRequestTask : AMSTask <AMSURLProtocolDelegate, NSURLSessionDelegate, AMSBagConsumer>

@property (readonly) AMSBag *bag;
@property (readonly) ACAccount *account;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)createBagForSubProfile;
+ (id)bagSubProfileVersion;
+ (id)bagSubProfile;

- (nonnull instancetype)initWithAccount:(id)account;
- (id)perform;
- (id)_encodedURLRequest;
- (nonnull instancetype)initWithAccount:(id)account bag:(id)bag;

@end
