//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSBagProtocol-Protocol.h"
#include "AMSURLSession.h"

@interface AMSDeviceOfferEligibilityTask : NSObject

@property (retain, nullable) id <AMSBagProtocol> bag;
@property (readonly) NSString *deviceGUID;
@property (retain, nullable) AMSURLSession *urlSession;
@property (readonly) NSString *masterSerialNumber;

- (id)_accountEligibilityEncoderWithBag:(id)bag account:(id)account clientInfo:(id)info;
- (id)_accountEligibilityRequestParametersWithIdentifiers:(id)identifiers;
- (id)_deviceEligibilityEncoderWithBag:(id)bag clientInfo:(id)info;
- (id)_deviceEligibilityRequestParametersWithGroups:(id)groups;
- (id)_eligibilityRequest;
- (id)_offersDecodedFromResult:(id)result;
- (nonnull instancetype)initWithBag:(id)bag deviceGUID:(id)guid masterSerialNumber:(id)number urlSession:(id)session;
- (id)performAccountEligibility:(id)eligibility forOffers:(id)offers clientInfo:(id)info;
- (id)performAnonymousDeviceEligibility:(id)eligibility clientInfo:(id)info;

@end
