//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSDaemonConnection.h"
#include "AMSDeviceMessengerClientInterface-Protocol.h"
#include "AMSDeviceMessengerServiceInterface-Protocol.h"

@protocol OS_dispatch_queue;

@interface AMSDeviceMessenger : NSObject <AMSDeviceMessengerClientInterface> {
	id <AMSDeviceMessengerServiceInterface> _proxyObject;
}

@property (retain, nullable) AMSDaemonConnection *connection;
@property (retain, nullable) dispatch_queue_t queue;
@property (retain, nullable) NSMutableArray *updateHandlers;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (nonnull instancetype)init;
- (void)deviceMessengerDidReceiveReply:(id)reply;
- (id)_getProxyObject;
- (void)deviceMessengerDidClearMessage:(id)message;
- (void)deviceMessengerDidUpdateDevices;
- (id)_identifierFromDialogRequest:(id)request;
- (void)_sendDelegateUpdateForMessage:(id)message;
- (void)addUpdateHandlerForType:(long long)type filter:(id)filter handler:(UnknownBlock)handler;
- (void)deviceMessengerDidReceiveMessage:(id)message;
- (id)sendDialog:(id)dialog account:(id)account;

@end
