//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSBagConsumer-Protocol.h"
#include "AMSBagProtocol-Protocol.h"
#include "AMSDeviceOfferEligibilityTask.h"
#include "AMSDeviceOfferRegistrationPrivacyValidator.h"
#include "AMSDeviceOffersTracking-Protocol.h"
#include "AMSProcessInfo.h"
#include "AMSTask.h"
#include "AMSURLSession.h"

@class ACAccount;

@interface AMSDeviceOfferRegistrationTask : AMSTask <AMSBagConsumer>

@property (retain, nullable) ACAccount *account;
@property (retain, nullable) id <AMSBagProtocol> bag;
@property (readonly) AMSDeviceOfferEligibilityTask *eligibilityTask;
@property (readonly) NSString *deviceGUID;
@property (readonly) NSString *masterSerialNumber;
@property (readonly) id <AMSDeviceOffersTracking> deviceOffersStore;
@property (readonly) AMSDeviceOfferRegistrationPrivacyValidator *privacyValidator;
@property (retain, nullable) AMSURLSession *urlSession;
@property BOOL ignoreRegistrationDenyList;
@property BOOL lightweightCheckOnly;
@property (retain, nullable) AMSProcessInfo *clientInfo;
@property (retain, nullable) NSSet *offerIdentifiers;
@property (retain, nullable) NSArray *registrationGroups;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)createBagForSubProfile;
+ (id)bagSubProfileVersion;
+ (id)bagSubProfile;
+ (id)bagKeySet;

- (id)perform;
- (id)_accountEligibleSerialsFromDeviceOffers:(id)offers accountOffers:(id)offers;
- (id)_bucketedOffers:(id)offers;
- (id)_companionSerialNumbers;
- (id)_deviceOffersURL;
- (id)_eligibilityQualifiedRegistrationGroupsWithAccount:(id)account pendingRegistrationGroups:(id)groups;
- (id)_filteredRegistrationGroups:(id)groups;
- (id)_handleRegistrationResult:(id)result;
- (BOOL)_isDeviceGroupRegistrationAllowed;
- (BOOL)_isEligibilityCallsAllowed;
- (BOOL)_isRegistrationAllowed;
- (id)_latestDeviceGroups;
- (id)_latestOffersWithFetchedDeviceOffers:(id)offers offersStore:(id)store;
- (id)_lightweightDeviceOffersURL;
- (id)_offersDecodedFromResult:(id)result;
- (id)_performLightweightRequestWithAccount:(id)account;
- (id)_performRegistrationRequestWithAccount:(id)account;
- (id)_registrationEndpointPOSTCompanionBodyWithDeviceGroups:(id)groups companionSerialNumbers:(id)numbers;
- (id)_registrationEndpointPOSTDeviceGroupsBody:(id)body;
- (id)_registrationEndpointPOSTParametersWithRegistrationGroups:(id)groups companionSerialNumbers:(id)numbers;
- (id)_registrationGroupsFrom:(id)from matching:(id)matching;
- (id)_registrationRequestEncoderWithAccount:(id)account;
- (id)_sanitizedResultPromise:(id)promise;
- (id)_serialNumberDenyList;
- (void)_updateWithDeviceOffers:(id)offers;
- (id)_urlRequestWithBagURL:(nullable NSURL *)url;
- (nonnull instancetype)initWithAccount:(id)account bag:(id)bag;
- (nonnull instancetype)initWithAccount:(id)account bag:(id)bag deviceGUID:(id)guid deviceOffersStore:(id)store eligibilityTask:(id)task masterSerialNumber:(id)number privacyValidator:(id)validator urlSession:(id)session;

@end
