//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@protocol AMSDaemonConnectionProtocol <NSObject>

@required

- (void)getAccountCachedServerDataServiceProxyWithReplyHandler:(UnknownBlock)handler;
- (void)getAccountManagementServiceProxyWithReplyHandler:(UnknownBlock)handler;
- (void)getAccountPostSignInServiceProxyWithReplyHandler:(UnknownBlock)handler;
- (void)getAccountSignOutServiceProxyWithReplyHandler:(UnknownBlock)handler;
- (void)getAutoBugCaptureServiceProxyWithReplyHandler:(UnknownBlock)handler;
- (void)getCookieServiceProxyWithReplyHandler:(UnknownBlock)handler;
- (void)getDeviceMessengerServiceProxyWithDelegate:(id)delegate replyHandler:(UnknownBlock)handler;
- (void)getDismissQRDialogServiceProxyWithReplyHandler:(UnknownBlock)handler;
- (void)getEligibilityServiceProxyWithReplyHandler:(UnknownBlock)handler;
- (void)getFraudReportServiceProxyWithReplyHandler:(UnknownBlock)handler;
- (void)getKeychainServiceProxyWithReplyHandler:(UnknownBlock)handler;
- (void)getOnDeviceDataServiceProxyWithReplyHandler:(UnknownBlock)handler;
- (void)getPaymentConfirmationServiceProxyWithReplyHandler:(UnknownBlock)handler;
- (void)getPaymentValidationServiceProxyWithReplyHandler:(UnknownBlock)handler;
- (void)getPurchaseServiceProxyWithReplyHandler:(UnknownBlock)handler;
- (void)getPushNotificationServiceProxyWithReplyHandler:(UnknownBlock)handler;
- (void)getSafariDataUpdateServiceProxyWithReplyHandler:(UnknownBlock)handler;
- (void)getSecurityServiceProxyWithDelegate:(id)delegate replyHandler:(UnknownBlock)handler;

@optional

@end
