//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@class ACAccount;

@interface AMSDeviceOfferRegistrationPrivacyValidator : NSObject

@property (readonly) ACAccount *account;

+ (id)_identifiersForValidationOptions:(unsigned long long)options;
+ (BOOL)_isPrivacyAcknowledgementForIdentifier:(id)identifier satisfiedOnAccount:(id)account;
+ (BOOL)_isPrivacyAcknowledgementForIdentifiers:(id)identifiers satisfiedOnAccount:(id)account;
+ (id)_masterEligibilityPrivacyOptionsIdentifiers;
+ (id)_minimumAcknowledgementVersionForIdentifier:(id)identifier;
+ (id)_privacyVersionMap;

- (nonnull instancetype)initWithAccount:(id)account;
- (BOOL)canMasterDevicePerformRegistration;
- (BOOL)isPrivacyRequirementMetForOptions:(unsigned long long)options;

@end
