//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@interface AMSDialogTextField : NSObject <NSSecureCoding>

@property long long keyboardType;
@property (copy, nullable) NSString *placeholder;
@property BOOL secure;
@property long long tag;
@property (copy, nullable) NSString *text;

+ (BOOL)supportsSecureCoding;
+ (id)textFieldWithPlaceholder:(id)placeholder secure:(BOOL)secure;

- (void)encodeWithCoder:(nullable NSCoder *)coder;
- (nonnull instancetype)initWithCoder:(nullable NSCoder *)coder;

@end
