//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSDServiceBrokerProtocol-Protocol.h"

@protocol OS_dispatch_queue;

@interface AMSDaemonConnection : NSObject <AMSDServiceBrokerProtocol>

@property (retain, nonatomic, nullable) NSXPCConnection *sharedConnection;
@property (readonly) dispatch_queue_t sharedConnectionAccessQueue;
@property (readonly) NSMutableArray *interruptionHandlers;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (id)_serviceInterfaceForSelector:(SEL)selector;
- (id)autoBugCaptureServiceProxySyncWithError:(id *)error;
- (id)paymentValidationServiceProxy;
- (id)deviceMessengerProxyWithDelegate:(id)delegate;
- (id)accountCachedServerDataService;
- (void)_connectionSyncProxyWithAccessBlock:(UnknownBlock)block;
- (id)paymentConfirmationProxy;
- (id)cookieServiceProxySyncWithError:(id *)error;
- (void)_handleInvalidation;
- (id)pushNotificationService;
- (void)_errorForwardingProxyForServiceProxy:(id)proxy proxyReplyError:(nullable NSError *)error interface:(id)interface proxyPromise:(id)promise;
- (void)_handleInterruption;
- (id)purchaseServiceProxy;
- (void)attemptResumeIfRequired;
- (id)safariDataUpdateServiceProxy;
- (id)fraudReportServiceProxy;
- (id)accountSignOutServiceProxy;
- (id)onDeviceDataServiceProxy;
- (id)_connectionProxyWithAccessBlock:(UnknownBlock)block;
- (id)accountManagementServiceProxySyncWithError:(id *)error;
- (void)addInterruptionHandler:(UnknownBlock)handler;
- (id)callService:(id)service then:(UnknownBlock)then;
- (id)eligibilityServiceProxy;
- (nonnull instancetype)init;
- (id)autoBugCaptureServiceProxy;
- (id)cookieServiceProxy;
- (void)_initializeConnection;
- (id)accountManagementServiceProxy;
- (id)keychainServiceProxy;
- (id)accountPostSignInServiceProxy;
- (id)securityServiceProxyWithDelegate:(id)delegate;
- (void)dealloc;
- (id)dismissQRDialogServiceProxy;

@end
