//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@class NSImage;
@protocol OS_dispatch_queue;

@interface AMSDialog : NSObject {
	dispatch_queue_t _systemDialogQueue;
}

@property (copy, nullable) NSArray *buttons;
@property (copy, nullable) UnknownBlock completionHandler;
@property (copy, nullable) NSImage *icon;
@property (copy, nullable) NSString *message;
@property long long selectedButtonIndex;
@property long long style;
@property (copy, nullable) NSArray *textFields;
@property (copy, nullable) NSString *title;

+ (id)dialogWithTitle:(id)title message:(id)message;
+ (id)dialogWithTitle:(id)title message:(id)message style:(long long)style;

- (void)present;
- (void)addButton:(id)button;
- (void)addTextField:(id)field;
- (nonnull instancetype)initWithTitle:(id)title message:(id)message style:(long long)style;
- (void)presentFromViewController:(id)controller;
- (void)presentSheetFromWindow:(id)window;
- (void)presentSystemDialog;

@end
