//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSDelegateAuthenticateTask.h"
#include "AMSProcessInfo.h"
#include "AMSURLResult.h"
#include "AMSURLTaskInfo.h"

@interface AMSDelegateTokenTask : AMSDelegateAuthenticateTask

@property (retain, nullable) AMSURLTaskInfo *taskInfo;
@property (retain, nullable) AMSURLResult *urlResult;
@property (retain, nullable) AMSProcessInfo *processInfo;

- (void)AMSURLSession:(id)amsurlsession task:(id)task handleAuthenticateRequest:(id)request completion:(UnknownBlock)completion;
- (id)_parseBiometricsSignatureRequestFromTask:(id)task;
- (id)_performFallbackAuthentication;
- (id)authenticateTaskWithRequest:(id)request;
- (id)delegateAuthenticateUrl;
- (nonnull instancetype)initWithDelegateAuthenticateRequest:(id)request bag:(id)bag processInfo:(id)info account:(id)account;
- (id)performRetrieveDelegateToken;

@end
