//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@interface AMSDatabaseHelper : NSObject

+ (id)_cachesURLForCachePath:(id)path;
+ (BOOL)removeDatabaseAtURL:(nullable NSURL *)url error:(out id *)error;
+ (id)databasePathForDataVaultPath:(id)path type:(long long)type;
+ (id)databasePathForCachePath:(id)path type:(long long)type;
+ (id)databaseFolderNameForType:(long long)type;
+ (BOOL)removeDatabaseForCachePath:(id)path error:(out id *)error;
+ (id)dataVaultURLForDataVaultPath:(id)path;
+ (BOOL)_addSkipBackupAttribute:(BOOL)attribute forURL:(nullable NSURL *)url;
+ (void)_applyProtectionClassForDirectoryAtURL:(nullable NSURL *)url;
+ (BOOL)removeDatabaseForDataVaultPath:(id)path error:(out id *)error;
+ (id)databaseURLForDataVaultPath:(id)path type:(long long)type;
+ (id)databaseURLForCachePath:(id)path type:(long long)type;
+ (id)_databaseNameForType:(long long)type;

@end
