//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@protocol AMSDeviceClass <NSObject>

@required

@property (readonly) BOOL deviceIsAppleTV;
@property (readonly) BOOL deviceIsAppleTVSimulator;
@property (readonly) BOOL deviceIsAppleWatch;
@property (readonly) BOOL deviceIsAppleWatchSimulator;
@property (readonly) BOOL deviceIsAudioAccessory;
@property (readonly) BOOL deviceIsComputeModule;
@property (readonly) BOOL deviceIsiPad;
@property (readonly) BOOL deviceIsiPadSimulator;
@property (readonly) BOOL deviceIsiPhone;
@property (readonly) BOOL deviceIsiPhoneSimulator;
@property (readonly) BOOL deviceIsMac;
@property (readonly) BOOL deviceIsRealityDevice;
@property (readonly) BOOL deviceIsRealityDeviceSimulator;

@optional

@end
