//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@interface AMSData : NSObject

+ (id)objectWithData:(id)data encoding:(long long)encoding error:(id *)error;
+ (id)dataWithObject:(id)object encoding:(long long)encoding error:(id *)error;
+ (long long)_dataEncodingFromResponse:(id)response;
+ (id)objectWithData:(id)data response:(id)response error:(id *)error;
+ (id)decompressedDataWithGzippedData:(id)data;
+ (id)compressedGzippedDataWithData:(id)data;
+ (long long)dataEncodingFromContentType:(id)type;

@end
