//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSDeviceClass-Protocol.h"
#include "AMSPromise.h"

@class AMSPhoneNumberContextInfo;

@protocol AMSDeviceInfo <AMSDeviceClass>

@required

@property (readonly) NSString *buildVersion;
@property (readonly) NSString *compatibleProductType;
@property (readonly) NSString *deviceGUID;
@property (readonly) NSString *deviceName;
@property (readonly) NSString *hardwarePlatform;
@property (readonly) NSString *localIPAddress;
@property (readonly) NSString *macAddress;
@property (readonly) NSData *macAddressData;
@property (readonly) NSString *MLBSerialNumber;
@property (readonly) NSString *modelPartNumber;
@property (readonly) NSString *operatingSystem;
@property (readonly) NSString *productType;
@property (readonly) NSString *productVersion;
@property (readonly) NSString *regionCode;
@property (readonly) NSString *ROMAddress;
@property (readonly) BOOL runningInStoreDemoMode;
@property (readonly) NSNumber *screenScale;
@property (readonly) NSNumber *screenHeight;
@property (readonly) NSNumber *screenWidth;
@property (readonly) BOOL secureElementAvailable;
@property (readonly) NSString *serialNumber;
@property (readonly) NSString *uniqueDeviceId;
@property (readonly) BOOL deviceIsBundle;
@property (readonly) NSArray *carrierNames;
@property (readonly) NSString *name;
@property (readonly) NSString *phoneNumber;
@property (readonly) AMSPromise *carrierNamesPromise;
@property (readonly) AMSPhoneNumberContextInfo *voicePreferredPhoneNumberContextInfo;
@property (readonly) AMSPromise *voicePreferredPACToken;

- (BOOL)isRunningInStoreDemoMode;
- (BOOL)isSecureElementAvailable;

@optional

@end
