//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSDelegateAuthenticateRequest.h"
#include "AMSPurchaseResult.h"

@interface AMSDelegatePurchaseRequest : AMSDelegateAuthenticateRequest <NSSecureCoding>

@property (copy, nullable) NSString *deviceName;
@property (retain, nullable) AMSPurchaseResult *purchaseResult;
@property (retain, nullable) NSString *cacheKey;
@property BOOL requiresDelegateToken;

+ (BOOL)supportsSecureCoding;

- (void)encodeWithCoder:(nullable NSCoder *)coder;
- (nonnull instancetype)initWithCoder:(nullable NSCoder *)coder;
- (nonnull instancetype)initWithCacheKey:(id)key challenge:(id)challenge;
- (nonnull instancetype)initWithChallenge:(id)challenge userAgent:(id)agent;
- (nonnull instancetype)initWithPurchaseResult:(id)result challenge:(id)challenge userAgent:(id)agent;

@end
