//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSBagConsumer-Protocol.h"
#include "AMSBagProtocol-Protocol.h"
#include "AMSBiometricsSignatureResult.h"
#include "AMSDelegateAuthenticateRequest.h"
#include "AMSTask.h"
#include "AMSURLProtocolDelegate-Protocol.h"
#include "AMSURLSession.h"

@class ACAccount;

@interface AMSDelegateAuthenticateTask : AMSTask <AMSURLProtocolDelegate, NSURLSessionDelegate, AMSBagConsumer>

@property (retain, nullable) ACAccount *account;
@property (readonly) AMSURLSession *session;
@property (readonly) id <AMSBagProtocol> bag;
@property (retain, nullable) NSDictionary *formData;
@property (readonly) AMSDelegateAuthenticateRequest *request;
@property (retain, nullable) AMSBiometricsSignatureResult *signatureResult;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)createBagForSubProfile;
+ (id)bagSubProfileVersion;
+ (id)bagSubProfile;
+ (id)bagKeySet;

- (void)_init;
- (id)_delegateAuthenticateResultFromUrlResult:(id)result;
- (id)_encodedURLRequestWithError:(id *)error;
- (id)_parseFormDataAsStringFromResult:(id)result;
- (id)_parseFormDataFromResult:(id)result;
- (id)_performDelegateAuthenticationWithError:(id *)error;
- (id)_urlRequestParameters;
- (id)delegateAuthenticateUrl;
- (nonnull instancetype)initWithBag:(id)bag account:(id)account;
- (nonnull instancetype)initWithDelegateAuthenticateRequest:(id)request bag:(id)bag account:(id)account;
- (id)performDelegateAuthentication;

@end
