//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@class ACAccount;

@interface AMSEngagementRequest : NSObject <NSSecureCoding>

@property (retain, nullable) NSData *modelData;
@property (retain, nullable) ACAccount *account;
@property BOOL anonymousMetrics;
@property (retain, nullable) NSDictionary *clientData;
@property (retain, nullable) NSString *mediaClientIdentifier;
@property (retain, nullable) NSString *logKey;
@property BOOL failOnDismiss;
@property (retain, nullable) NSDictionary *metricsOverlay;
@property (retain, nullable) NSURL *originatingURL;
@property long long presentationStyle;
@property (retain, nullable) NSURL *URL;
@property BOOL silentlyCheckURL;
@property long long destinationStyle;
@property BOOL suppressInteractiveModalDismissal;

+ (BOOL)supportsSecureCoding;

- (nonnull instancetype)initWithModel:(id)model;
- (void)encodeWithCoder:(nullable NSCoder *)coder;
- (nonnull instancetype)init;
- (nonnull instancetype)initWithCoder:(nullable NSCoder *)coder;
- (id)exportObject;
- (nonnull instancetype)initWithJSONDictionary:(id)jsondictionary;
- (nonnull instancetype)initWithModel:(id)model destinationStyle:(long long)style;
- (id)_accountFromDictionary:(nullable NSDictionary *)dictionary;
- (long long)_engagementPresentationStyleFromDictionary:(nullable NSDictionary *)dictionary;
- (void)applyOverlayMetrics:(id)metrics;
- (nonnull instancetype)initWithRequestDictionary:(nullable NSDictionary *)dictionary;
- (id)modelForClass:(Class)_class error:(id *)error;
- (void)replaceOverlayMetrics:(id)metrics;

@end
