//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSProcessInfo.h"

@interface AMSEngagementEnqueueRequest : NSObject <NSSecureCoding>

@property (retain, nullable) AMSProcessInfo *clientInfo;
@property (retain, nullable) NSArray *destinations;
@property (retain, nullable) NSArray *events;
@property (retain, nullable) NSString *logKey;
@property int processIdentifier;
@property double timeout;

+ (BOOL)supportsSecureCoding;
+ (id)archiveClasses;

- (void)encodeWithCoder:(nullable NSCoder *)coder;
- (nonnull instancetype)initWithCoder:(nullable NSCoder *)coder;

@end
