//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@interface AMSEphemeralDefaults : NSObject

+ (BOOL)suppressEngagement;
+ (BOOL)processAssertionsEnabled;
+ (void)setPurchaseAccountFallback:(BOOL)fallback;
+ (void)setPreferEphemeralImageLoader:(BOOL)loader;
+ (void)setHTTPAlternativeServicesStorageDisabled:(BOOL)disabled;
+ (BOOL)preferEphemeralURLSessions;
+ (BOOL)bagKeyRegistrationEnabled;
+ (long long)HARLoggingItemLimit;
+ (void)setHARLoggingItemLimit:(long long)limit;
+ (void)setPreferEphemeralURLSessions:(BOOL)urlsessions;
+ (void)setSuppressEngagement:(BOOL)engagement;
+ (void)setForceLoadUrlMetrics:(long long)metrics;
+ (BOOL)HARLoggingEnabled;
+ (BOOL)preferEphemeralImageLoader;
+ (long long)forceLoadUrlMetrics;
+ (BOOL)purchaseAccountFallback;
+ (void)setProcessAssertionsEnabled:(BOOL)enabled;
+ (void)_accessDataStoreUsingBlock:(UnknownBlock)block;
+ (id)_propertyForKey:(id)key defaultValue:(id)value expectedType:(Class)type;
+ (void)_setProperty:(id)property forKey:(id)key;
+ (BOOL)HTTPAlternativeServicesStorageDisabled;
+ (void)setHARLoggingEnabled:(BOOL)enabled;
+ (void)setBagKeyRegistrationEnabled:(BOOL)enabled;

@end
