//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSEngagementClientProtocol-Protocol.h"
#include "AMSEngagementServiceProtocol-Protocol.h"

@protocol OS_dispatch_queue;

@interface AMSEngagementConnection : NSObject <AMSEngagementClientProtocol, AMSEngagementServiceProtocol>

@property (retain, nullable) NSXPCConnection *connection;
@property (retain, nullable) NSNotificationCenter *notificationCenter;
@property (readonly) dispatch_queue_t queue;
@property (copy, nullable) UnknownBlock errorHandler;

- (id)_newRemoteConnection;
- (void)notifyBlockedMessages:(id)messages;
- (id)serviceInterfaceForSelector:(SEL)selector;
- (id)_makeRemoteConnectionInterface;
- (oneway void)fetchMetricsIdentifiers;
- (id)proxy;
- (id)_makeExportedClientConnectionInterface;
- (void)treatmentsDidSyncronize;
- (void)manualSyncMetricsIdentifiers;
- (void)_removeRemoteConnection;
- (oneway void)syncMetricsIdentifiers;
- (void)contentInfoForApp:(id)app cacheKey:(id)key version:(id)version reply:(UnknownBlock)reply;
- (void)syncWithRequest:(id)request completion:(UnknownBlock)completion;
- (void)handlePushedEvent:(id)event;
- (void)beginObservingMessages;
- (nonnull instancetype)initWithNotificationCenter:(id)center;
- (void)dealloc;
- (void)treatmentStoreServiceWithReply:(UnknownBlock)reply;
- (void)enqueueWithRequest:(id)request completion:(UnknownBlock)completion;

@end
