//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSBagConsumer-Protocol.h"
#include "AMSBagProtocol-Protocol.h"
#include "AMSEngagementConnection.h"
#include "AMSEngagementMessageCache.h"

@protocol OS_dispatch_queue;

@interface AMSEngagement : NSObject <AMSBagConsumer> {
	dispatch_queue_t _callbackQueue;
}

@property (retain, nullable) NSMapTable *observerInfo;
@property (retain, nullable) NSMutableSet *runningPromises;
@property (retain, nullable) id <AMSBagProtocol> bag;
@property (retain, nullable) AMSEngagementConnection *connection;
@property (readonly) AMSEngagementMessageCache *cacheInfo;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)createBagForSubProfile;
+ (id)notificationCenter;
+ (id)bagSubProfileVersion;
+ (id)_connection;
+ (id)bagSubProfile;
+ (void)_recordLoggingEventWithBag:(id)bag enqueueData:(id)data eventType:(id)type userInfo:(id)info destinations:(id)destinations error:(nullable NSError *)error;
+ (id)_notifyQueue;
+ (double)_enqueueTimeout;
+ (id)_engagementQueue;

- (void)_scheduleSyncIfNeeded:(id)needed;
- (nonnull instancetype)initWithBag:(id)bag;
- (id)enqueueEvent:(id)event;
- (void)handlePushEvent:(id)event;
- (void)handleDialogResult:(id)result;
- (id)sync;
- (id)_enqueueWithContext:(id)context;
- (id)_parseActions:(id)actions;
- (id)enqueueData:(id)data to:(id)to;
- (id)enqueueMessageEvent:(id)event;
- (void)removeObserver:(id)observer placement:(id)placement serviceType:(id)type;
- (void)_manageRunningPromise:(id)promise;
- (id)enqueueData:(id)data;
- (void)addObserver:(id)observer placements:(id)placements serviceType:(id)type queue:(id)queue;
- (void)_connectionErrorNotification;
- (id)fetchMetricsIdentifiers;
- (void)_failAllRunningPromisesWithError:(nullable NSError *)error;
- (nonnull instancetype)initWithoutBag;
- (id)_createCombinedLogKey;
- (id)syncDestinations:(id)destinations;
- (id)manualSyncMetricsIdentifiers;
- (void)_handleServiceResponse:(id)response;
- (void)addCachePolicy:(long long)policy forPlacements:(id)placements serviceType:(id)type;
- (void)_pushEventReceived:(id)received;
- (void)_removeRunningPromise:(id)promise;
- (id)syncWithRequest:(id)request;
- (void)addObserver:(id)observer placement:(id)placement serviceType:(id)type;
- (void)addObserver:(id)observer placement:(id)placement serviceType:(id)type queue:(id)queue;
- (nonnull instancetype)init;
- (id)syncMetricsIdentifiers;
- (void)addObserver:(id)observer placements:(id)placements serviceType:(id)type;
- (id)_enqueue:(id)_enqueue;
- (long long)dismissActionFromPresentationAction:(long long)action;
- (id)contentInfoForApp:(id)app cacheKey:(id)key version:(id)version;
- (void)dealloc;
- (void)_observeNotifications;
- (id)treatmentStoreService;

@end
