//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSEngagementEvent-Protocol.h"

@interface AMSEngagementMessageEvent : NSObject <AMSEngagementEvent>

@property (copy, nullable) NSArray *placementInfo;
@property (copy, nullable) NSString *serviceType;
@property (readonly) NSDictionary *engagementData;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (nonnull instancetype)initWithServiceType:(id)type placementInfo:(id)info;
- (nonnull instancetype)initWithServiceType:(id)type placements:(id)placements;

@end
