//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSEngagementRequest.h"

@interface AMSEngagementEnqueueResult : NSObject <NSSecureCoding>

@property (retain, nullable) NSDictionary *data;
@property (retain, nullable) NSArray *actions;
@property (retain, nullable) AMSEngagementRequest *request;

+ (BOOL)supportsSecureCoding;
+ (id)archiveClasses;

- (void)encodeWithCoder:(nullable NSCoder *)coder;
- (nonnull instancetype)initWithCoder:(nullable NSCoder *)coder;

@end
