//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSAccountCachedServerDataServiceInterface-Protocol.h"

@class v24@?0@";

@interface AMSEngagementMessageCache : NSObject { // (Swift)
	v24@?0@"<AMSAccountCachedServerDataServiceInterface>"8@"NSError"16 cacheInfo;
}

- (nonnull instancetype)init;
- (void)addWithCachePolicy:(long long)policy placement:(id)placement serviceType:(id)type;
- (id)filterWithMessage:(id)message;
- (BOOL)isBlockedWithMessageRequest:(id)request placement:(id)placement serviceType:(id)type;

@end
