//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSSQLiteConnection.h"
#include "AMSSQLiteConnectionDelegate-Protocol.h"

@interface AMSEngagementCacheDatabase : NSObject <AMSSQLiteConnectionDelegate>

@property (retain, nullable) AMSSQLiteConnection *connection;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (BOOL)openAtPath:(id)path error:(id *)error;
- (BOOL)closeWithError:(id *)error;
- (BOOL)connection:(id)connection needsResetForCorruptionError:(nullable NSError *)error error:(out id *)error;
- (void)_performTransaction:(UnknownBlock)transaction;
- (BOOL)collectGarbageWithError:(id *)error;
- (BOOL)insertResponseData:(id)data filterData:(id)data expiration:(id)expiration error:(id *)error;
- (BOOL)selectWithExpirationDate:(id)date handler:(UnknownBlock)handler error:(id *)error;

@end
