//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSMetricsEvent.h"

@interface AMSEngagementMessageAction : NSObject

@property (copy, nullable) NSDictionary *clickstreamMetricsEvent;
@property (retain, nullable) NSURL *deepLink;
@property (retain, nullable) NSString *identifier;
@property (retain, nullable) NSURL *iconURL;
@property (retain, nullable) NSString *kind;
@property (copy, nullable) AMSMetricsEvent *metricsEvent;
@property (copy, nullable) NSDictionary *parameters;
@property BOOL requiresDelegate;
@property long long style;
@property (retain, nullable) NSString *title;

- (id)exportObject;
- (nonnull instancetype)initWithJSObject:(id)jsobject;
- (id)makeDialogAction;

@end
