//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSEngagementMessageAction.h"
#include "AMSEngagementRequest.h"
#include "AMSMetricsEvent.h"

@interface AMSEngagementMessageRequest : NSObject

@property (retain, nullable) NSArray *debugInfo;
@property (retain, nullable) NSArray *actions;
@property (retain, nullable) NSDictionary *appearanceInfo;
@property (copy, nullable) NSDictionary *clickstreamMetricsEvent;
@property (retain, nullable) AMSEngagementMessageAction *defaultAction;
@property (retain, nullable) AMSEngagementRequest *engagementRequest;
@property (retain, nullable) NSURL *iconURL;
@property (copy, nullable) NSString *identifier;
@property BOOL isMessageCached;
@property (copy, nullable) NSString *messageIdentifier;
@property (copy, nullable) AMSMetricsEvent *metricsEvent;
@property long long presentationAction;
@property long long style;
@property (copy, nullable) NSString *subtitle;
@property (copy, nullable) NSString *subtitleAccessibilityLabel;
@property (copy, nullable) NSString *title;
@property (copy, nullable) NSString *titleAccessibilityLabel;

- (id)exportObject;
- (nonnull instancetype)initWithJSObject:(id)jsobject;
- (id)makeDialogRequest;

@end
