//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@interface AMSEligibilityResponse : NSObject <NSSecureCoding>

@property (readonly) unsigned long long answer;
@property (readonly) unsigned long long source;
@property (readonly) NSDictionary *status;
@property (readonly) NSDictionary *context;

+ (BOOL)supportsSecureCoding;
+ (id)convertFromXPC:(id)xpc;
+ (id)stringifiedAnswer:(unsigned long long)answer;
+ (id)stringifiedAnswerSource:(unsigned long long)source;
+ (id)stringifiedInputStatus:(unsigned long long)status;
+ (id)stringifiedInputStatusFromInt:(unsigned long long)_int;

- (void)encodeWithCoder:(nullable NSCoder *)coder;
- (nonnull instancetype)initWithCoder:(nullable NSCoder *)coder;
- (nonnull instancetype)initWithAnswer:(unsigned long long)answer source:(unsigned long long)source status:(id)status context:(id)context;

@end
