//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@interface AMSEngagementAppData : NSObject <NSCopying>

@property (retain, nullable) NSArray *cachedResponses;
@property (retain, nullable) NSArray *eventFilters;
@property (readonly) NSString *identifier;
@property (retain, nullable) NSString *lastSyncedBuild;

- (nonnull instancetype)copyWithZone:(nullable struct _NSZone *)zone;
- (nonnull instancetype)initWithIdentifier:(id)identifier cacheObject:(id)object;
- (id)exportObject;

@end
