//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@protocol OS_dispatch_queue;

@interface AMSEngagementObserverInfo : NSObject

@property (retain, nullable) NSMutableSet *underlyingPlacements;
@property (retain, nullable) NSMutableSet *underlyingServiceTypes;
@property (readonly) NSSet *placements;
@property (readonly) NSSet *serviceTypes;
@property (retain, nullable) dispatch_queue_t dispatchQueue;

- (void)removePlacement:(id)placement;
- (void)addServiceType:(id)type;
- (void)removeServiceType:(id)type;
- (nonnull instancetype)initWithQueue:(id)queue;
- (void)addPlacements:(id)placements;

@end
