//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@interface AMSFinalizedBlind : NSObject

@property (nonatomic, readonly) NSData *finalizedData;
@property (nonatomic, readonly) NSData *privateInput;
@property (nonatomic, readonly) NSString *timestamp;
@property (nonatomic, readonly) NSString *adamId;
@property (nonatomic, readonly) NSData *publicKey;
@property (nonatomic, copy) NSString *certificate;

- (nonnull instancetype)init;
- (nonnull instancetype)initWithFinalizedData:(id)data privateInput:(id)input timestamp:(id)timestamp adamId:(id)id publicKey:(id)key certificate:(id)certificate;

@end
