//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@interface AMSFairPlayDeviceIdentitySession : NSObject {
	void * _fpdiSession;
	void * _attributes;
}

@property (readonly, nonatomic) NSDate *creationDate;

+ (BOOL)reset:(id *)reset;
+ (id)stringForStage:(unsigned long long)stage;
+ (id)errorForFPDIStatus:(int)fpdistatus stage:(unsigned long long)stage;

- (void)dealloc;
- (id)creationDataWithError:(id *)error;
- (unsigned long long)fpdiSessionId;
- (nonnull instancetype)initWithExistingSession:(unsigned long long)session creationDate:(id)date error:(id *)error;
- (nonnull instancetype)initWithLevel:(long long)level error:(id *)error;
- (nonnull instancetype)initializationDataWithCreationResponseData:(id)data error:(id *)error;
- (BOOL)setupSessionWithInitializationResponseData:(id)data error:(id *)error;
- (id)signatureForData:(id)data error:(id *)error;

@end
