//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSMutablePromise.h"

@interface AMSFinishedPromise : AMSMutablePromise

+ (BOOL)_errorIsCanceledError:(nullable NSError *)error;
+ (BOOL)_errorIsTimeOutError:(nullable NSError *)error;
+ (id)promiseWithResult:(id)result;
+ (id)promiseWithPromiseResult:(id)result;
+ (id)promiseWithError:(nullable NSError *)error;
+ (void)logUnavailableInitWithSelector:(SEL)selector;

- (void)addFinishBlock:(UnknownBlock)block;
- (void)addBlock:(UnknownBlock)block orCallWithResult:(UnknownBlock)result;
- (id)resultWithError:(id *)error;
- (void)addErrorBlock:(UnknownBlock)block;
- (void)addSuccessBlock:(UnknownBlock)block;
- (void)waitUntilFinishedWithTimeout:(double)timeout;
- (id)resultBeforeDate:(id)date error:(id *)error;
- (BOOL)isCancelled;
- (id)resultWithTimeout:(double)timeout error:(id *)error;
- (void)waitUntilFinished;
- (void)resultWithCompletion:(UnknownBlock)completion;
- (BOOL)isFinished;
- (UnknownBlock)completionHandlerAdapter;
- (id)continueWithBlock:(UnknownBlock)block;
- (nonnull instancetype)initWithTimeout:(double)timeout;
- (id)condition;
- (void)resultWithTimeout:(double)timeout completion:(UnknownBlock)completion;
- (void)stopRetainingSelf;
- (id)valueFromAddingBlock:(UnknownBlock)block orCallWithResult:(UnknownBlock)result;
- (nonnull instancetype)init;
- (id)binaryPromiseAdapterForClass:(Class)_class;
- (UnknownBlock)boolCompletionHandlerAdapter;
- (void)flushCompletionBlocksWithResult:(id)result;
- (BOOL)isFinishedWithLock;
- (UnknownBlock)nilValueCompletionHandlerAdapter;
- (void)resultBeforeDate:(id)date completion:(UnknownBlock)completion;

@end
