//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSDialogRequest.h"
#include "AMSFinancePerformable-Protocol.h"
#include "AMSURLTaskInfo.h"

@interface AMSFinanceVerifyPurchaseResponse : NSObject <AMSFinancePerformable>

@property (retain, nullable) AMSDialogRequest *dialogRequest;
@property (retain, nullable) NSDictionary *responseDictionary;
@property (retain, nullable) AMSURLTaskInfo *taskInfo;
@property long long verifyType;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)_dialogRequestForCVVFromPayload:(id)payload verifyType:(long long)type;
+ (BOOL)isVerifyPurchasePayload:(id)payload;
+ (id)_dialogRequestForCarrierFromPayload:(id)payload verifyType:(long long)type;
+ (long long)_verifyTypeFromPayload:(id)payload;

- (id)_handleCVVDialogResult:(id)result shouldReattempt:(BOOL *)reattempt;
- (id)_handleCarrierDialogResult:(id)result shouldReattempt:(BOOL *)reattempt;
- (id)_runCVVRequestForCode:(id)code error:(id *)error;
- (id)_runCarrierNewCodeWithError:(id *)error;
- (id)_runCarrierVerifyCode:(id)code error:(id *)error;
- (nonnull instancetype)initWithPayload:(id)payload taskInfo:(id)info;
- (id)performWithTaskInfo:(id)info;

@end
