//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSFinanceAuthenticateResponse.h"
#include "AMSFinancePerformable-Protocol.h"
#include "AMSPaymentSheetRequest.h"

@interface AMSFinancePaymentSheetResponse : NSObject <AMSFinancePerformable>

@property (readonly) AMSFinanceAuthenticateResponse *authenticateResponse;
@property (readonly) NSDictionary *metricsDictionary;
@property (readonly) AMSPaymentSheetRequest *paymentSheetRequest;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)_attributedListDictionaryForValues:(id)values account:(id)account;
+ (id)_attributedStringForAttributedArray:(id)array account:(id)account;
+ (id)_attributedStringForAttributedDictionary:(nullable NSDictionary *)dictionary account:(id)account;
+ (id)_attributedStringForSalableInfoStringArray:(id)array account:(id)account shouldUppercase:(BOOL)uppercase;
+ (id)_attributedStringForSalableInfoStyledStringArray:(id)array account:(id)account shouldUppercase:(BOOL)uppercase;
+ (id)_attributedStringForStringArray:(id)array useGrey:(BOOL)grey account:(id)account shouldUppercase:(BOOL)uppercase;
+ (long long)_confirmationTitleForString:(id)string;
+ (id)_createMerchantSessionFromDictionary:(nullable NSDictionary *)dictionary;
+ (id)_flexListDictionaryForValues:(id)values styles:(id)styles account:(id)account shouldUppercaseText:(BOOL)text designVersion:(id)version;
+ (id)_flexListLeadingItemForValues:(id)values styles:(id)styles;
+ (id)_greyAttributedStringForAttributedString:(id)string range:(struct _NSRange { unsigned long long x0; unsigned long long x1; })range;
+ (long long)_payeeInferredFromEnumeratedTitle:(id)title;
+ (long long)_salableIconForString:(id)string;
+ (id)_salableInfoDictionaryForValues:(id)values styles:(id)styles account:(id)account shouldUppercaseText:(BOOL)text designVersion:(id)version;
+ (id)_salableInfoForKey:(id)key inDictionary:(nullable NSDictionary *)dictionary shouldUppercase:(BOOL)uppercase;
+ (id)_styleDictionaryWithName:(id)name styles:(id)styles;
+ (id)attributedStringWithString:(id)string styles:(id)styles;
+ (id)createRequestFromDictionary:(nullable NSDictionary *)dictionary confirmationOnly:(BOOL)only delegateAuthenticationRequired:(BOOL)required biometricSignatureRequired:(BOOL)required authenticateResponse:(id)response taskInfo:(id)info account:(id)account;
+ (id)fallbackTitleFromResponse:(id)response;

- (id)_createUpdatedBodyFromFormData:(id)data;
- (id)_enrichedMetricsDictionaryWithFinanceDictionary:(nullable NSDictionary *)dictionary;
- (id)_performAuthorizationDialogProxyWithTaskInfo:(id)info;
- (void)_performPaymentSheetWithTaskInfo:(id)info completionHandler:(UnknownBlock)handler;
- (nonnull instancetype)initWithResponseDictionary:(nullable NSDictionary *)dictionary confirmationOnly:(BOOL)only delegateAuthenticationRequired:(BOOL)required biometricSignatureRequired:(BOOL)required taskInfo:(id)info;
- (id)performWithTaskInfo:(id)info;
- (void)performWithTaskInfo:(id)info completionHandler:(UnknownBlock)handler;

@end
