//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSDialogRequest.h"
#include "AMSFinancePerformable-Protocol.h"
#include "AMSURLTaskInfo.h"

@interface AMSFinanceDialogResponse : NSObject <AMSFinancePerformable>

@property (readonly) BOOL containsCommerceUIURL;
@property (readonly, copy) NSDictionary *dialogDictionary;
@property long long kind;
@property (readonly, copy) NSDictionary *responseDictionary;
@property (copy, nullable) AMSURLTaskInfo *taskInfo;
@property (readonly) AMSDialogRequest *dialogRequest;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (long long)dialogKindForTaskInfo:(id)info withResponseDictionary:(nullable NSDictionary *)dictionary;
+ (id)_serviceActionFromButton:(id)button taskInfo:(id)info;
+ (id)_presentIDSDialog:(id)idsdialog taskInfo:(id)info;
+ (BOOL)_credentialSource:(unsigned long long)source satisfiesAuthenticationType:(unsigned long long)type;
+ (id)_handleAskPermissionRequestWithURL:(nullable NSURL *)url account:(id)account;
+ (id)performFinanceDialog:(id)dialog taskInfo:(id)info;
+ (id)handleDialogResult:(id)result taskInfo:(id)info;
+ (BOOL)_shouldSendOverIDS:(id)ids taskInfo:(id)info;
+ (id)_presentDialog:(id)dialog taskInfo:(id)info;

- (long long)_actionTypeFromButtonDictionary:(nullable NSDictionary *)dictionary;
- (id)_createActionFromButtonDictionary:(nullable NSDictionary *)dictionary title:(id)title;
- (id)_createDialogRequest;
- (id)_createRequestButtonsFromDialogDictionary:(nullable NSDictionary *)dictionary;
- (id)_enrichedMetricsDictionaryWithFinanceDictionary:(nullable NSDictionary *)dictionary;
- (BOOL)_isCommerceUIURL:(id)uiurl actionType:(long long)type URLType:(long long)urltype;
- (nonnull instancetype)initWithResponseDictionary:(nullable NSDictionary *)dictionary kind:(long long)kind taskInfo:(id)info;
- (id)performWithTaskInfo:(id)info;

@end
