//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSFDSOptions.h"

@class ACAccount;

@interface AMSFDSRequest : NSObject <NSCopying, NSSecureCoding>

@property (readonly) ACAccount *account;
@property (readonly) unsigned long long accountType;
@property (copy, nullable) NSString *logKey;
@property (readonly) AMSFDSOptions *options;
@property (readonly, copy) NSNumber *purchaseIdentifier;

+ (BOOL)supportsSecureCoding;

- (nonnull instancetype)copyWithZone:(nullable struct _NSZone *)zone;
- (void)encodeWithCoder:(nullable NSCoder *)coder;
- (nonnull instancetype)initWithCoder:(nullable NSCoder *)coder;
- (nonnull instancetype)initWithPurchaseIdentifier:(id)identifier account:(id)account options:(id)options;

@end
