//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSFinancePerformable-Protocol.h"
#include "AMSURLTaskInfo.h"

@interface AMSFinanceDelegateAuthenticateChallengeResponse : NSObject <AMSFinancePerformable>

@property (retain, nullable) NSDictionary *responseDictionary;
@property (retain, nullable) AMSURLTaskInfo *taskInfo;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (BOOL)isDelegateAuthChallengeForTaskInfo:(id)info;

- (nonnull instancetype)initWithResponseDictionary:(nullable NSDictionary *)dictionary taskInfo:(id)info;
- (id)performWithTaskInfo:(id)info;

@end
