//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@interface AMSFeatureFlagGroup : NSObject

@property (retain, nonatomic, nullable) NSMutableArray *mutableFlags;
@property (copy, nonatomic, nullable) NSString *name;
@property (readonly, nonatomic) NSArray *flags;

+ (id)fetchFlagGroupWithName:(id)name;
+ (id)_normalizedFlagGroupsFromFlagGroups:(id)groups;
+ (id)groupsFromDomainData:(id)data domain:(id)domain mutableFeatures:(id)features profileFeatures:(id)features includesHidden:(BOOL)hidden;
+ (id)allFlagGroups;
+ (id)allFlagGroupsIncludingHidden:(BOOL)hidden;
+ (id)allFlagGroupsIncludingHidden:(BOOL)hidden searchDirectory:(id)directory;
+ (id)flagGroupWithName:(id)name includingHidden:(BOOL)hidden;
+ (void)resetAllFlagGroups;
+ (BOOL)disableFlagGroupWithName:(id)name error:(id *)error;
+ (BOOL)setFlagGroupWithName:(id)name enabled:(BOOL)enabled error:(id *)error;
+ (id)groupsFromDomainData:(id)data domain:(id)domain;
+ (BOOL)enableFlagGroupWithName:(id)name error:(id *)error;

- (BOOL)isGroupTypeEnabled:(long long)enabled;
- (id)allITFEs;
- (BOOL)isDevelopmentPhaseEnabled:(long long)enabled;
- (void)setGroupType:(long long)type enabled:(BOOL)enabled;
- (id)_testableFlags;
- (id)developmentFlags;
- (id)activateFlagsIfNeededForType:(long long)type;
- (void)activateITFEs;
- (id)completedFlags;
- (id)_developmentFlags;
- (id)fetchAllGroupKeys;
- (void)appendFlag:(id)flag;
- (void)setFlagsForDevelopmentPhase:(long long)phase enabled:(BOOL)enabled;
- (id)flagsForType:(long long)type;
- (id)testableFlags;
- (nonnull instancetype)initWithName:(id)name;
- (id)_groupKeyForDevelopmentPhase:(long long)phase;
- (nonnull instancetype)initWithName:(id)name domain:(id)domain;
- (id)_groupKeyForType:(long long)type;
- (id)activateFlagsIfNeededForDevelopmentPhase:(long long)phase;
- (id)flagsForDevelopmentPhase:(long long)phase;
- (id)_completedFlags;
- (void)reset;

@end
