//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@interface AMSFamilyAccountPair : NSObject

@property (readonly, nonatomic) unsigned long long downloaderAccountID;
@property (readonly, nonatomic) unsigned long long familyID;
@property (readonly, nonatomic) unsigned long long purchaserAccountID;

- (nonnull instancetype)initWithDownloaderAccountID:(unsigned long long)id purchaserAccountID:(unsigned long long)id familyID:(unsigned long long)id;

@end
