//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSFollowUpNotification.h"
#include "AMSMetricsEvent.h"

@class ACAccount;
@protocol OS_dispatch_queue;

@interface AMSFollowUpItem : NSObject

@property (retain, nullable) dispatch_queue_t internalQueue;
@property (retain, nullable) dispatch_queue_t metricsQueue;
@property (retain, nullable) ACAccount *account;
@property (retain, nullable) AMSFollowUpNotification *notification;
@property (retain, nullable) NSArray *actions;
@property (readonly) BOOL active;
@property (readonly) NSString *backingIdentifier;
@property (retain, nullable) NSString *bundleIconName;
@property BOOL disableGrouping;
@property long long displayStyle;
@property (retain, nullable) NSDate *expirationDate;
@property BOOL expirationDateHidden;
@property (retain, nullable) NSString *footer;
@property (readonly) NSString *groupIdentifier;
@property BOOL hardwareOffer;
@property (retain, nullable) NSString *identifier;
@property (retain, nullable) NSString *informativeText;
@property (retain, nullable) NSString *logKey;
@property BOOL keepNotificationOnLockscreen;
@property (copy, nullable) AMSMetricsEvent *metricsEvent;
@property BOOL newDeviceOutreach;
@property long long priority;
@property BOOL shouldPostNotification;
@property (retain, nullable) NSString *title;
@property (retain, nullable) NSMutableDictionary *userInfo;

+ (id)_dateFromString:(id)string;
+ (id)backingIdentifierForIdentifier:(id)identifier DSID:(nullable NSNumber *)dsID;
+ (id)backingIdentifierForIdentifier:(id)identifier account:(id)account;
+ (id)componentsFromBackingIdentifier:(id)identifier;

- (BOOL)isHardwareOffer;
- (id)generateItem;
- (nonnull instancetype)initWithFollowUpItem:(id)item;
- (nonnull instancetype)initWithIdentifier:(id)identifier account:(id)account priority:(long long)priority;
- (nonnull instancetype)initWithIdentifier:(id)identifier jsonDictionary:(nullable NSDictionary *)dictionary account:(id)account priority:(long long)priority logKey:(id)key;
- (BOOL)isExpirationDateHidden;
- (BOOL)isNewDeviceOutreach;
- (id)postMetricsWithBag:(id)bag;
- (id)postMetricsWithBagContract:(id)contract;
- (BOOL)shouldOverwriteItem:(id)item;

@end
