//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSFollowUpAction.h"

@interface AMSFollowUpNotification : NSObject

@property (retain, nullable) AMSFollowUpAction *activateAction;
@property (retain, nullable) NSSet *options;
@property (retain, nullable) NSString *informativeText;
@property (retain, nullable) NSString *title;

+ (id)defaultOptions;
+ (id)optionForString:(id)string;

- (nonnull instancetype)init;
- (id)generateNotification;
- (nonnull instancetype)initWithJSONDictionary:(id)jsondictionary parentIdentifier:(id)identifier logKey:(id)key;

@end
