//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSFinancePerformable-Protocol.h"
#include "AMSURLTaskInfo.h"

@class ACAccount;

@interface AMSFinanceActionResponse : NSObject <AMSFinancePerformable>

@property (retain, nullable) ACAccount *account;
@property (retain, nullable) NSString *creditString;
@property long long kind;
@property BOOL shouldRetry;
@property (retain, nullable) AMSURLTaskInfo *taskInfo;
@property BOOL tidContinue;
@property (retain, nullable) NSURL *URL;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (void)handleExternalGotoURL:(nullable NSURL *)url taskInfo:(id)info;
+ (id)_URLForCommerceUIFromURL:(nullable NSURL *)url taskInfo:(id)info tidContinue:(BOOL)_continue;
+ (id)_bodyObjectFromRequest:(id)request;
+ (id)_deepLinkForURL:(nullable NSURL *)url taskInfo:(id)info gotoType:(long long)type isAccountURL:(BOOL)url tidContinue:(BOOL)_continue;
+ (BOOL)_isModernURL:(nullable NSURL *)url taskInfo:(id)info;
+ (id)_presentEngagementForURL:(nullable NSURL *)url taskInfo:(id)info;
+ (BOOL)_stashTIDContinueHeadersForTaskInfo:(id)info;
+ (id)actionWithActionDictionary:(nullable NSDictionary *)dictionary taskInfo:(id)info;
+ (id)actionWithUpdatedCreditString:(id)string account:(id)account taskInfo:(id)info;
+ (void)handleExternalGotoURL:(nullable NSURL *)url;
+ (id)handleGotoURL:(nullable NSURL *)url taskInfo:(id)info gotoType:(long long)type accountURL:(BOOL)url tidContinue:(BOOL)_continue retryOnSuccess:(BOOL)success;

- (id)_performGotoURL;
- (id)_handleGotoAction;
- (id)_performCreditDisplayUpdate;
- (id)_performOpenStandardURL;
- (nonnull instancetype)initWithTaskInfo:(id)info;
- (id)performWithTaskInfo:(id)info;

@end
