//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@interface AMSFeatureFlag : NSObject

@property (nonatomic) BOOL codeComplete;
@property (copy, nonatomic, nullable) NSString *ITFE;
@property (nonatomic) BOOL testable;
@property (nonatomic) BOOL hidden;
@property (copy, nonatomic, nullable) NSString *associatedGroup;
@property (nonatomic) BOOL defaultEnabled;
@property (nonatomic) long long developmentPhase;
@property (nonatomic) BOOL enabled;
@property (copy, nonatomic, nullable) NSString *feature;
@property (retain, nonatomic, nullable) NSDictionary *flagData;
@property (copy, nonatomic, nullable) NSString *displayName;
@property (copy, nonatomic, nullable) NSString *domain;
@property (copy, nonatomic, nullable) NSString *featureDescription;
@property (copy, nonatomic, nullable) NSString *flagGroup;
@property (retain, nonatomic, nullable) NSArray *itfes;
@property (nonatomic) BOOL userEnabled;
@property (readonly, nonatomic) BOOL remote;

+ (id)allFlagGroups;
+ (BOOL)disableFlagForFeature:(id)feature domain:(id)domain error:(id *)error;
+ (BOOL)disableFlagGroup:(id)group error:(id *)error;
+ (BOOL)enableFlagForFeature:(id)feature domain:(id)domain error:(id *)error;
+ (BOOL)enableFlagGroup:(id)group error:(id *)error;
+ (id)flagForFeature:(id)feature domain:(id)domain;
+ (id)flagForFeature:(id)feature domain:(id)domain searchDirectory:(id)directory;
+ (id)flagGroupWithName:(id)name;

- (long long)groupType;
- (id)itfesFromString:(id)string mutableFeatures:(id)features profileFeatures:(id)features;
- (void)_disableITFEs;
- (BOOL)isDefaultEnabled;
- (BOOL)hasITFEs;
- (BOOL)isHidden;
- (void)activateITFEs;
- (long long)_developmentPhaseFromGroupType:(long long)type;
- (BOOL)isTestable;
- (void)_updateInternalEnabledState;
- (nonnull instancetype)initWithFlagData:(id)data mutableFeatures:(id)features profileFeatures:(id)features feature:(id)feature domain:(id)domain;
- (BOOL)isUserEnabled;
- (void)_enableITFEs;
- (BOOL)isRemote;
- (BOOL)isEnabled;
- (BOOL)isCodeComplete;
- (BOOL)hasITFEWithName:(id)name;
- (void)_updateDevelopmentPhase;
- (void)_activateFlag;
- (void)_updateUserEnabled:(BOOL)enabled;

@end
