//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSAccountCachedServerDataServiceInterface-Protocol.h"
#include "AMSFairPlayDeviceIdentityNetworkProviderProtocol-Protocol.h"
#include "AMSSendableBag.h"

@class v24@?0@";

@interface AMSFairPlayDeviceIdentityNetworkProvider : NSObject <AMSFairPlayDeviceIdentityNetworkProviderProtocol> { // (Swift)
	v24@?0@"<AMSAccountCachedServerDataServiceInterface>"8@"NSError"16 session;
}

- (nonnull instancetype)initWithSession:(id)session;
- (nonnull instancetype)init;
- (void)fpdiNetworkResponseFor:(NSURL *)_for data:(NSData *)data bag:(AMSSendableBag *)bag completionHandler:(UnknownBlock)handler;
- (void)fpdiNetworkResponseFor:(NSURL *)_for data:(NSData *)data completionHandler:(UnknownBlock)handler;

@end
