//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSFraudReportStateStorage-Protocol.h"
#include "AMSStorageDatabase.h"

@interface AMSFraudReportDatabaseStateStorage : NSObject <AMSFraudReportStateStorage> {
	AMSStorageDatabase *_storageDatabase;
}

@property (retain, nonatomic, nullable) NSDate *lastCleanupDate;
@property (readonly, nonatomic) NSArray *allKeys;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)new;

- (nonnull instancetype)init;
- (id)objectForKeyedSubscript:(id)subscript;
- (void)setObject:(id)object forKeyedSubscript:(id)subscript;

@end
