//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@interface AMSFamilyMember : NSObject

@property BOOL currentSignedInUser;
@property (readonly) NSDictionary *dictionaryRepresentation;
@property (readonly) BOOL askToBuyEnabled;
@property (readonly) NSString *firstName;
@property (readonly) NSNumber *iCloudDSID;
@property (readonly) NSString *iCloudUsername;
@property (readonly) NSNumber *iTunesDSID;
@property (readonly) NSString *iTunesUsername;
@property (readonly) NSString *lastName;
@property (readonly) BOOL sharingPurchases;

- (nonnull instancetype)initWithDictionaryRepresentation:(id)representation;
- (nonnull NSString *)description;
- (BOOL)isAskToBuyEnabled;
- (BOOL)isSharingPurchases;
- (BOOL)isCurrentSignedInUser;

@end
