//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSAuthenticateRequest.h"
#include "AMSFinanceDialogResponse.h"
#include "AMSFinancePerformable-Protocol.h"

@interface AMSFinanceAuthenticateResponse : NSObject <AMSFinancePerformable>

@property (retain, nullable) NSDictionary *dialogDictionary;
@property (readonly) AMSFinanceDialogResponse *dialogResponse;
@property (readonly) AMSAuthenticateRequest *authenticateRequest;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)_authenticateRequestWithAuthType:(unsigned long long)type taskInfo:(id)info dialogResponse:(id)response serviceIdentifier:(id)identifier;
+ (id)_handleAuthResult:(id)result authError:(nullable NSError *)error originalRequest:(id)request actionResult:(id)result redirectURL:(nullable NSURL *)url taskInfo:(id)info;
+ (void)_handleDialogFromAuthError:(nullable NSError *)error taskInfo:(id)info;
+ (id)_performAuthRequest:(id)request actionResult:(id)result redirectURL:(nullable NSURL *)url taskInfo:(id)info;
+ (id)_presentAuthRequest:(id)request taskInfo:(id)info;
+ (id)_serviceIdentifierForResponse:(id)response taskInfo:(id)info;
+ (void)_updateTaskWithAuthedAccount:(id)account taskInfo:(id)info;
+ (void)_updateTaskWithLastCredentialSource:(id)source taskInfo:(id)info;
+ (unsigned long long)authenticationTypeForResponse:(id)response responseDictionary:(nullable NSDictionary *)dictionary;
+ (id)performAuthFromResponse:(id)response taskInfo:(id)info;

- (id)_locateActionableButtonUsingDialogResponse:(id)response;
- (nonnull instancetype)initWithResponseDictionary:(nullable NSDictionary *)dictionary taskInfo:(id)info;
- (id)performWithTaskInfo:(id)info;
- (void)performWithTaskInfo:(id)info completionHandler:(UnknownBlock)handler;

@end
