//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSAccountCachedServerDataServiceInterface-Protocol.h"
#include "AMSFairPlayDeviceIdentityNetworkProviderProtocol-Protocol.h"
#include "AMSSendableBag.h"

@class NSURLRequest, v24@?0@";

@interface AMSFairPlayDeviceIdentity : NSObject { // (Swift)
	v24@?0@"<AMSAccountCachedServerDataServiceInterface>"8@"NSError"16 persistentSessionCache;
	v24@?0@"<AMSAccountCachedServerDataServiceInterface>"8@"NSError"16 sessionType;
	v24@?0@"<AMSAccountCachedServerDataServiceInterface>"8@"NSError"16 queue;
}

+ (id)shared;

- (nonnull instancetype)init;
- (void)fpdiLevelFor:(NSURL *)_for bag:(AMSSendableBag *)bag buyParams:(NSDictionary *)params completionHandler:(UnknownBlock)handler;
- (void)headersFor:(NSURLRequest *)_for bag:(AMSSendableBag *)bag buyParams:(NSDictionary *)params networkProvider:(<AMSFairPlayDeviceIdentityNetworkProviderProtocol> *)provider completionHandler:(UnknownBlock)handler;
- (void)initializeSessionFor:(NSURL *)_for buyParams:(NSDictionary *)params networkProvider:(<AMSFairPlayDeviceIdentityNetworkProviderProtocol> *)provider bag:(AMSSendableBag *)bag completionHandler:(UnknownBlock)handler;
- (void)reinitializeSessionWithLevel:(long long)level completionHandler:(UnknownBlock)handler;
- (void)resetSessionFor:(NSURL *)_for buyParams:(NSDictionary *)params bag:(AMSSendableBag *)bag completionHandler:(UnknownBlock)handler;
- (void)resetSessionWithLevel:(long long)level completionHandler:(UnknownBlock)handler;

@end
