//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSHTTPArchiveMetrics.h"

@class NSURLSessionTaskMetrics;

@interface AMSHTTPArchiveTaskInfo : NSObject <NSSecureCoding>

@property (readonly) AMSHTTPArchiveMetrics *taskMetrics;
@property (readonly) NSData *HTTPBody;
@property (readonly) NSData *responseData;
@property (readonly) NSURLSessionTaskMetrics *metrics;

+ (BOOL)supportsSecureCoding;

- (void)encodeWithCoder:(nullable NSCoder *)coder;
- (nonnull instancetype)initWithCoder:(nullable NSCoder *)coder;
- (nonnull instancetype)initWithURLTaskInfo:(id)info;

@end
