//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSBagProtocol-Protocol.h"
#include "AMSDialogRequest.h"
#include "AMSDialogResult.h"
#include "AMSProcessInfo.h"
#include "AMSTask.h"

@class ACAccount;

@interface AMSHandleDialogResultTask : AMSTask

@property (copy, nullable) ACAccount *account;
@property (readonly) id <AMSBagProtocol> bag;
@property (retain, nullable) AMSProcessInfo *clientInfo;
@property (copy, nullable) NSString *proxyBundleId;
@property (readonly) AMSDialogRequest *request;
@property (readonly) AMSDialogResult *result;
@property (readonly, copy) NSError *error;

- (id)perform;
- (nonnull instancetype)initWithRequest:(id)request result:(id)result error:(nullable NSError *)error bag:(id)bag;
- (nonnull instancetype)initWithResult:(id)result bag:(id)bag;

@end
