//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@protocol OS_dispatch_queue;

@interface AMSKeychainStore : NSObject

@property (retain, nullable) dispatch_queue_t keychainQueue;
@property (readonly, nonatomic) void * /* function */ storeSecItemAddFunc;
@property (readonly, nonatomic) void * /* function */ storeSecItemCopyMatchingFunc;
@property (readonly, nonatomic) void * /* function */ storeSecItemDeleteFunc;
@property (readonly, copy, nonatomic) NSString *identifier;
@property (readonly, copy, nonatomic) NSString *service;
@property (copy, nonatomic, nullable) NSString *keychainAccessGroup;

+ (BOOL)processIsEntitledToUse:(id)use;

- (struct __CFDictionary *)_copyKeychainQuery;
- (BOOL)_removeDataFromKeychain;
- (id)_retrieveData;
- (BOOL)_storeData:(id)data;
- (BOOL)deleteData;
- (id)deleteDataPromise;
- (nonnull instancetype)initWithIdentifier:(id)identifier service:(id)service keychainAccessGroup:(id)group;
- (nonnull instancetype)initWithIdentifier:(id)identifier service:(id)service keychainAccessGroup:(id)group keychainAddFunc:(void * /* function */)func keychainCopyFunc:(void * /* function */)func keychainDeleteFunc:(void * /* function */)func;
- (id)retrieveData;
- (id)retrieveDataPromise;
- (BOOL)storeData:(id)data;
- (id)storeDataPromise:(id)promise;

@end
