//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSFairPlayContext.h"

@protocol OS_dispatch_queue;

@interface AMSKeybag : NSObject

@property (retain, nullable) dispatch_queue_t dispatchQueue;
@property (retain, nullable) AMSFairPlayContext *fairPlayContext;

+ (id)sharedInstance;

- (nonnull instancetype)init;
- (unsigned int)fairplayContextWithError:(id *)error;
- (unsigned int)fairplayContextWithErrorForSwift:(id *)swift;
- (BOOL)importDiversityBagWithData:(id)data error:(id *)error;
- (BOOL)importKeybagData:(id)data outError:(id *)error;
- (BOOL)importKeybagWithData:(id)data error:(id *)error;
- (id)keybagSyncData:(id)data transactionType:(unsigned int)type outError:(id *)error;
- (id)keybagSyncDataWithAccountID:(id)id transactionType:(unsigned int)type error:(id *)error;
- (id)keybagSyncDataWithAccountID:(id)id transactionType:(unsigned int)type errorForSwift:(id *)swift;
- (void)resetContext;

@end
