//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@interface AMSKeychain : NSObject

+ (struct __SecKey { struct __CFRuntimeBase { unsigned long long x0; _Atomic unsigned long long x1; } x0; struct __SecKeyDescriptor *x1; void *x2; } *)copyPrivateKeyWithContext:(id)context account:(id)account options:(id)options error:(id *)error;
+ (struct __SecKey { struct __CFRuntimeBase { unsigned long long x0; _Atomic unsigned long long x1; } x0; struct __SecKeyDescriptor *x1; void *x2; } *)copyPrivateKeyWithContext:(id)context options:(id)options error:(id *)error;
+ (BOOL)storePublicCert:(struct __SecCertificate *)cert intermediateCert:(struct __SecCertificate *)cert privateKey:(struct __SecKey { struct __CFRuntimeBase { unsigned long long x0; _Atomic unsigned long long x1; } x0; struct __SecKeyDescriptor *x1; void *x2; } *)key options:(id)options error:(id *)error;
+ (id)keychainLabelForOptions:(id)options;
+ (void)setSecItemAddFunc:(void * /* function */)func;
+ (id)legacyAttestationForOptions:(id)options error:(id *)error;
+ (struct __SecKey { struct __CFRuntimeBase { unsigned long long x0; _Atomic unsigned long long x1; } x0; struct __SecKeyDescriptor *x1; void *x2; } *)_copyLegacyPrivateKeyForOptions:(id)options error:(id *)error;
+ (struct __SecKey { struct __CFRuntimeBase { unsigned long long x0; _Atomic unsigned long long x1; } x0; struct __SecKeyDescriptor *x1; void *x2; } *)_copyLegacyPublicKeyForOptions:(id)options error:(id *)error;
+ (id)_legacyAttestationForOptions:(id)options error:(id *)error;
+ (BOOL)deleteKeyPairWithOptions:(id)options error:(id *)error;
+ (id)_certificatePrivateKeyLabelForOptions:(id)options;
+ (struct __SecKey { struct __CFRuntimeBase { unsigned long long x0; _Atomic unsigned long long x1; } x0; struct __SecKeyDescriptor *x1; void *x2; } *)copyPublicKeyForAccount:(id)account options:(id)options error:(id *)error;
+ (void)setSecItemCopyMatchingFunc:(void * /* function */)func;
+ (void)stashResumptionHeaders:(id)headers;
+ (id)certificateChainStringsForOptions:(id)options error:(id *)error;
+ (struct __SecAccessControl *)copyAccessControlRefWithAccount:(id)account options:(id)options error:(id *)error;
+ (id)certificateKeychainLabelsForOptions:(id)options;
+ (id)_resumptionHeadersQuery;
+ (id)_primaryConstraintsWithOptions:(id)options;
+ (void * /* function */)secItemCopyMatchingFunc;
+ (BOOL)deleteCertificateChainWithOptions:(id)options error:(id *)error;
+ (struct __SecKey { struct __CFRuntimeBase { unsigned long long x0; _Atomic unsigned long long x1; } x0; struct __SecKeyDescriptor *x1; void *x2; } *)copyPublicKeyForOptions:(id)options error:(id *)error;
+ (void * /* function */)secItemAddFunc;
+ (id)publicKeyHeaderWithAccount:(id)account options:(id)options signatureResult:(id)result;
+ (id)resumptionHeaders;
+ (void)_deleteResumptionHeaders;
+ (BOOL)performForwardKeyMigrationForDSID:(nullable NSNumber *)dsID forceMigration:(BOOL)migration;
+ (BOOL)_generateLegacyKeypairForOptions:(id)options error:(id *)error;
+ (struct __SecKey { struct __CFRuntimeBase { unsigned long long x0; _Atomic unsigned long long x1; } x0; struct __SecKeyDescriptor *x1; void *x2; } *)copyCertificatePrivateKeyWithContext:(id)context account:(id)account options:(id)options error:(id *)error;
+ (id)_extendedConstraintsWithOptions:(id)options;
+ (struct __SecAccessControl *)createAccessControlRefWithOptions:(id)options error:(id *)error;
+ (BOOL)stashResumptionHeaders:(id)headers error:(id *)error;

@end
