//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@interface AMSLookupItemArtwork : NSObject

@property (readonly, nonatomic) NSDictionary *artworkDictionary;
@property (readonly, nonatomic) double height;
@property (readonly, nonatomic) NSString *URLString;
@property (readonly, nonatomic) double width;

- (id)URLWithHeight:(long long)height width:(long long)width cropStyle:(id)style format:(id)format;
- (id)colorWithKind:(id)kind;
- (nonnull instancetype)initWithArtworkDictionary:(nullable NSDictionary *)dictionary;

@end
