//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@interface AMSLookupItem : NSObject <NSCopying, NSSecureCoding>

@property (readonly, copy) NSString *artistName;
@property (readonly, copy) NSArray *artwork;
@property (readonly, copy) NSString *bundleIdentifier;
@property (readonly, copy) NSArray *categoryNames;
@property (readonly, copy) NSString *displayName;
@property (readonly, copy) NSString *itemKind;
@property (readonly, copy) NSNumber *iTunesStoreIdentifier;
@property (readonly, copy) NSString *offerName;
@property (readonly, copy) NSArray *offers;
@property (readonly) BOOL POIBased;
@property (readonly, copy) NSURL *productPageURL;
@property (readonly) long long numberOfUserRatings;
@property (readonly) float userRating;
@property (readonly) long long numberOfUserRatingsForCurrentVersion;
@property (readonly) float userRatingForCurrentVersion;
@property (readonly) NSDictionary *itemDictionary;

+ (BOOL)supportsSecureCoding;

- (nonnull instancetype)initWithLookupDictionary:(nullable NSDictionary *)dictionary;
- (nonnull instancetype)copyWithZone:(nullable struct _NSZone *)zone;
- (void)encodeWithCoder:(nullable NSCoder *)coder;
- (nonnull instancetype)initWithCoder:(nullable NSCoder *)coder;
- (BOOL)isPOIBased;

@end
