//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@interface AMSLocalizations : NSObject

+ (id)localizedStringForKey:(id)key bundle:(id)bundle table:(id)table bag:(id)bag;
+ (id)localizedStringPromiseForKey:(id)key bundle:(id)bundle table:(id)table languageCode:(id)code;
+ (id)localizedStringForKey:(id)key bundle:(id)bundle table:(id)table languageCode:(id)code;
+ (id)localizedStringPromiseForKey:(id)key bundle:(id)bundle table:(id)table bag:(id)bag;

@end
