//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@protocol OS_os_log;

@interface AMSLogConfig : NSObject <NSCopying, NSMutableCopying>

@property (copy, nullable) NSString *category;
@property (copy, nullable) NSString *subsystem;
@property (retain, nullable) NSObject<OS_os_log> *OSLogObject;
@property (readonly) BOOL debugLogsEnabled;

+ (id)sharedMessagingUIConfig;
+ (id)sharedActionConfig;
+ (id)sharedRegulatoryEligibilityConfig;
+ (id)sharedAnisetteConfig;
+ (id)sharedWebUIPageConfig;
+ (id)sharedPushNotificationConfig;
+ (id)sharedDeviceOffersConfig;
+ (id)sharedTSDataSyncConfig;
+ (id)sharedURLLoadingConfig;
+ (id)sharedPromiseConfig;
+ (id)sharedAccountsDaemonConfig;
+ (id)sharedConfig;
+ (id)sharedHARLoggingConfig;
+ (id)sharedAccountsMigrationConfig;
+ (id)sharedServerDataCacheConfig;
+ (id)sharedAccountsCookiesConfig;
+ (id)sharedFollowUpConfig;
+ (id)sharedBagConfig;
+ (id)sharedTreatmentsConfig;
+ (id)sharedAccountsNotificationPluginConfig;
+ (id)sharedAccountsOversizeConfig;
+ (id)sharedPurchaseOversizeConfig;
+ (id)sharedMarketingItemConfig;
+ (id)sharedBagCacheConfig;
+ (id)sharedAccountsMultiUserConfig;
+ (id)sharedKeychainConfig;
+ (id)sharedAttestationConfig;
+ (id)sharedMediaConfig;
+ (id)sharedAccountsAuthenticationPluginConfig;
+ (BOOL)_debugLogsEnabled:(id)enabled;
+ (id)sharedDataMigrationConfig;
+ (id)sharedAccountsConfig;
+ (id)sharedEngagementConfig;
+ (id)sharedMetricsConfig;
+ (id)sharedWebUIConfig;
+ (id)sharedAccountsStorefrontConfig;
+ (id)sharedAccountsSyncPluginConfig;
+ (id)sharedUserNotificationConfig;
+ (id)sharedPrivacyConfig;
+ (id)sharedRatingsProviderConfig;
+ (id)sharedMediaServiceOwnerConfig;
+ (id)sharedFraudReportConfig;
+ (id)sharedBiometricsConfig;
+ (id)sharedAccountsMigrationConfigOversize;
+ (id)sharedAccountsLogoutConfig;
+ (id)sharedConfigOversize;
+ (id)sharedPurchaseConfig;

- (nonnull instancetype)copyWithZone:(nullable struct _NSZone *)zone;
- (BOOL)isEqual:(nullable id)object;
- (id)mutableCopyWithZone:(struct _NSZone *)zone;
- (unsigned long long)hash;
- (nonnull NSString *)description;
- (nonnull instancetype)initWithCategory:(id)category backingLog:(id)log;

@end
