//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSURLResult.h"

@interface AMSLookupResult : AMSURLResult {
	NSDictionary *_response;
}

@property (copy, nonatomic, nullable) NSDate *expirationDate;
@property (readonly, nonatomic) NSArray *allItems;

- (void)_enumerateItemsWithBlock:(UnknownBlock)block;
- (nonnull instancetype)initWithResult:(id)result dictionary:(nullable NSDictionary *)dictionary;
- (id)itemForKey:(id)key;
- (id)appStoreURLWithReason:(long long)reason initialIndex:(long long)index;
- (id)valueForProperty:(id)property;

@end
