//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSBagConsumer-Protocol.h"
#include "AMSBagProtocol-Protocol.h"
#include "AMSProcessInfo.h"
#include "AMSTask.h"

@interface AMSLookup : AMSTask <AMSBagConsumer>

@property (retain, nullable) id <AMSBagProtocol> bag;
@property (retain, nullable) NSString *caller;
@property (retain, nullable) AMSProcessInfo *clientInfo;
@property (retain, nullable) NSString *imageProfile;
@property (retain, nullable) NSString *keyProfile;
@property (retain, nullable) NSString *platform;
@property long long signatureType;
@property long long version;
@property (retain, nullable) NSString *language;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)createBagForSubProfile;
+ (id)bagSubProfileVersion;
+ (id)bagSubProfile;
+ (id)bagKeySet;

- (nonnull instancetype)initWithBagContract:(id)contract;
- (nonnull instancetype)initWithBag:(id)bag caller:(id)caller keyProfile:(id)profile;
- (id)_compileQueryParametersWithBundleIds:(id)ids itemIds:(id)ids;
- (void)setContract:(id)contract;
- (id)contract;
- (void)_addJSSignatureToRequest:(id)request;
- (nonnull instancetype)initWithBagContract:(id)contract caller:(id)caller keyProfile:(id)profile;
- (id)performLookupWithBundleIdentifiers:(id)identifiers itemIdentifiers:(id)identifiers;

@end
