//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@protocol AMSLocalAuthHeaderNames

@required

@property (nonatomic, readonly) NSString *action;
@property (nonatomic, readonly) NSString *challenge;
@property (nonatomic, readonly) NSString *publicKey;
@property (nonatomic, readonly) NSString *signature;
@property (nonatomic, readonly) NSString *signatureVersion;
@property (nonatomic, readonly) NSString *state;

@optional

@end
