//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSPromise.h"

@interface AMSLazyPromise : AMSPromise

@property (copy, nullable) UnknownBlock block;
@property (nonatomic) BOOL executedBlock;
@property (nonatomic) double timeout;

- (BOOL)_runBlock;
- (void)addFinishBlock:(UnknownBlock)block;
- (void)addBlock:(UnknownBlock)block orCallWithResult:(UnknownBlock)result;
- (nonnull instancetype)initWithTimeout:(double)timeout block:(UnknownBlock)block;
- (id)resultWithError:(id *)error;
- (void)addErrorBlock:(UnknownBlock)block;
- (void)addSuccessBlock:(UnknownBlock)block;
- (id)resultBeforeDate:(id)date error:(id *)error;
- (id)resultWithTimeout:(double)timeout error:(id *)error;
- (nonnull instancetype)initWithBlock:(UnknownBlock)block;
- (nonnull instancetype)initWithPromiseResult:(id)result;
- (id)valueFromAddingBlock:(UnknownBlock)block orCallWithResult:(UnknownBlock)result;

@end
