//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@interface AMSMetricsFigaroEventModifier : NSObject

@property (readonly, nonatomic) NSDictionary *fieldFilters;
@property (readonly, nonatomic) NSDictionary *metricsDictionary;
@property (readonly, nonatomic) NSDictionary *overrideDictionary;
@property (readonly, nonatomic) NSString *sampleSessionKey;
@property (readonly, nonatomic) double flushInterval;

- (BOOL)shouldSkipEvent:(id)event;
- (BOOL)shouldDropEvent:(id)event;
- (id)_fieldFiltersFromOverrides:(id)overrides;
- (BOOL)fieldFiltersMatchEvent:(id)event;
- (id)_createSampleSessionKey;
- (id)reportingURLForEvent:(id)event;
- (BOOL)_shouldSampleEvent:(id)event;
- (void)prepareEvent:(id)event regexCache:(id)cache;
- (nonnull instancetype)initWithMetricsDictionary:(nullable NSDictionary *)dictionary overrideDictionary:(nullable NSDictionary *)dictionary;
- (id)_overridePropertyForKey:(id)key;

@end
