//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@interface AMSMediaToken : NSObject <NSCopying, NSSecureCoding>

@property (readonly) NSDate *expirationDate;
@property (readonly) double lifetime;
@property (readonly, copy) NSString *tokenString;
@property (readonly) BOOL valid;

+ (BOOL)supportsSecureCoding;

- (BOOL)isExpired;
- (nonnull instancetype)copyWithZone:(nullable struct _NSZone *)zone;
- (double)percentageOfLifetimeRemaining;
- (BOOL)willExpireWithin:(double)within;
- (void)encodeWithCoder:(nullable NSCoder *)coder;
- (BOOL)isEqual:(nullable id)object;
- (nonnull instancetype)initWithString:(id)string expirationDate:(id)date lifetime:(double)lifetime;
- (BOOL)isValid;
- (id)invalidCopy;
- (nonnull NSString *)description;
- (nonnull instancetype)initWithCoder:(nullable NSCoder *)coder;
- (nonnull instancetype)initWithString:(id)string expirationDate:(id)date lifetime:(double)lifetime valid:(BOOL)valid;

@end
