//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSMediaRestrictionsRatingItem.h"
#include "AMSURLResult.h"

@interface AMSMediaRestrictionsResult : NSObject

@property (nonatomic, readonly) AMSURLResult *rawResult;
@property (nonatomic, readonly) BOOL isSuccess;
@property (nonatomic, readonly) NSString *message;
@property (nonatomic, readonly) NSDictionary *responseData;
@property (nonatomic, readonly) AMSMediaRestrictionsRatingItem *tvRestriction;
@property (nonatomic, readonly) AMSMediaRestrictionsRatingItem *movieRestriction;
@property (nonatomic, readonly) NSNumber *allowPurchasesValue;
@property (nonatomic, readonly) NSNumber *isProfileLockSetValue;
@property (nonatomic, readonly) BOOL hasRestrictionKeys;
@property (nonatomic, readonly) NSString *description;

- (nonnull instancetype)init;
- (nonnull instancetype)initWithResult:(id)result;

@end
