//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSMetricsDataSource-Protocol.h"
#include "AMSMetricsDatabase.h"

@protocol OS_dispatch_queue;

@interface AMSMetricsDatabaseDataSource : NSObject <AMSMetricsDataSource>

@property (readonly, nonatomic) AMSMetricsDatabase *database;
@property (copy, nonatomic, nullable) NSString *currentLockKey;
@property (readonly, nonatomic) dispatch_queue_t queue;
@property (readonly, nonatomic) dispatch_queue_t callbackQueue;
@property (readonly, nonatomic) NSString *containerIdentifier;
@property (readonly, nonatomic) long long eventCount;

- (void)removeAllEvents;
- (id)enqueueEvents:(id)events;
- (void)cancel;
- (void)enumerateSortedEventsForTopic:(id)topic block:(UnknownBlock)block;
- (nonnull instancetype)initWithContainerIdentifier:(id)identifier;
- (BOOL)removeEvents:(id)events error:(id *)error;
- (void)didFinishBatching;
- (BOOL)willStartBatchingWithLogKey:(id)key error:(id *)error;
- (BOOL)skipEvents:(id)events error:(id *)error;

@end
