//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSBagConsumer-Protocol.h"
#include "AMSBagProtocol-Protocol.h"
#include "AMSMediaToken.h"
#include "AMSMediaTokenServicePrivateAccessTokenProtocol-Protocol.h"
#include "AMSMediaTokenServiceProtocol-Protocol.h"
#include "AMSMediaTokenServiceStoreProtocol-Protocol.h"
#include "AMSMediaTokenServiceThrottler.h"
#include "AMSProcessInfo.h"
#include "AMSPromise.h"
#include "AMSPromiseSerialQueue.h"
#include "AMSURLSession.h"

@class ACAccount;
@protocol OS_dispatch_queue;

@interface AMSMediaTokenService : NSObject <AMSMediaTokenServicePrivateAccessTokenProtocol, AMSBagConsumer, AMSMediaTokenServiceProtocol>

@property (readonly) AMSMediaTokenServiceThrottler *throttler;
@property (readonly) AMSPromiseSerialQueue *tokenFetchPromiseSerialQueue;
@property (readonly) id <AMSMediaTokenServiceStoreProtocol> tokenStore;
@property (readonly) id <AMSMediaTokenServiceStoreProtocol> patBasedtokenStore;
@property (retain, nullable) NSString *privateAcessTokenChallenge;
@property (readonly) Class privateAccessTokenFetcherClass;
@property (readonly) dispatch_queue_t patTokenFetchQueue;
@property BOOL URLKnownToBeTrusted;
@property (retain, nullable) ACAccount *account;
@property (retain, nullable) id <AMSBagProtocol> bag;
@property (readonly) AMSPromise *cachedMediaTokenPromise;
@property long long clientType;
@property (readonly) NSString *clientIdentifier;
@property (retain, nullable) AMSProcessInfo *clientInfo;
@property (retain, nullable) NSString *keychainAccessGroup;
@property (weak) AMSURLSession *session;
@property (readonly) AMSMediaToken *cachedMediaToken;
@property (readonly) NSString *clientVersion;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)createBagForSubProfile;
+ (id)bagSubProfileVersion;
+ (id)bagSubProfile;
+ (id)bagKeySet;
+ (id)_overrideOrClientIdentifier:(id)identifier;

- (void)setCachedMediaToken:(id)token store:(id)store;
- (id)cachedMediaToken:(id)token;
- (nonnull instancetype)initWithClientIdentifier:(id)identifier clientVersion:(id)version bag:(id)bag;
- (void)_refreshMediaTokenIfNeeded:(id)needed store:(id)store bagProperties:(id)properties;
- (nonnull instancetype)initWithClientIdentifier:(id)identifier bag:(id)bag;
- (void)invalidateMediaToken:(id)token;
- (void)invalidatePATMediaToken;
- (id)getCachedMediaToken:(BOOL)token;
- (id)_fetchTokenPromise:(id)promise store:(id)store;
- (id)_tokenRequestPromiseWithPrivateAccessToken:(id)token;
- (id)fetchMediaToken;
- (id)_fetchPATTokenPromiseWithFallack:(id)fallack store:(id)store finishBlock:(UnknownBlock)block;
- (void)invalidateMediaToken;
- (BOOL)_shouldRefreshMediaToken:(id)token bagProperties:(id)properties;
- (BOOL)_shouldReturnMediaToken:(id)token;
- (nonnull instancetype)initWithClientIdentifier:(id)identifier tokenStore:(id)store patBasedTokenStore:(id)store bag:(id)bag fetcherClass:(Class)_class;
- (void)_fetchPatBasedToken:(id)token cachedMediaToken:(id)token privateAccessTokenChallenge:(id)challenge finishBlock:(UnknownBlock)block;
- (id)getPrivateAccessToken:(id)token;
- (id)_fetchToken:(id)token privateAccessTokenChallenge:(id)challenge;
- (nonnull instancetype)initWithClientIdentifier:(id)identifier keychainAccessGroup:(id)group bag:(id)bag;
- (void)setCachedMediaToken:(id)token patBasedToken:(BOOL)token;
- (id)_fetchBagProperties;

@end
