//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSMetricsEvent.h"

@interface AMSMetricsLoadURLEvent : AMSMetricsEvent

@property (copy, nullable) NSString *appleTimingApp;
@property BOOL apsRelayAttempted;
@property BOOL apsRelayDidFallback;
@property BOOL apsRelaySucceeded;
@property (copy, nullable) NSString *buildVariant;
@property (copy, nullable) NSString *cellularDataBearerTechnology;
@property (copy, nullable) NSString *clientCorrelationKey;
@property (copy, nullable) NSString *clientError;
@property double connectionEndTime;
@property (copy, nullable) NSString *connectionInterface;
@property BOOL connectionReused;
@property unsigned long long connectionStartNStatRXBytes;
@property unsigned long long connectionStartNStatTXBytes;
@property unsigned long long connectionStopNStatRXBytes;
@property unsigned long long connectionStopNStatTXBytes;
@property double connectionStartTime;
@property (copy, nullable) NSString *connectionType;
@property double domainLookupEndTime;
@property double domainLookupStartTime;
@property BOOL DNUSubmissionAllowed;
@property (copy, nullable) NSString *DNSServers;
@property (copy, nullable) NSString *edgeNodeCacheStatus;
@property (copy, nullable) NSNumber *edgeRelayWasUsed;
@property (copy, nullable) NSString *environmentDataCenter;
@property double fetchStartTime;
@property BOOL cachedResponse;
@property (copy, nullable) NSString *networkProtocolName;
@property (copy, nullable) NSArray *networkQualityReports;
@property (copy, nullable) NSString *originalApp;
@property (copy, nullable) NSString *appBuildNumber;
@property (copy, nullable) NSString *clientApp;
@property (copy, nullable) NSString *osMajorVersion;
@property (copy, nullable) NSString *radioType;
@property (copy, nullable) NSString *radioTechnology;
@property unsigned long long redirectCount;
@property double redirectEndTime;
@property double redirectStartTime;
@property unsigned long long requestMessageSize;
@property (copy, nullable) NSString *requestMethod;
@property double requestStartTime;
@property (copy, nullable) NSString *requestURL;
@property (copy, nullable) NSString *resolvedIPAddress;
@property (copy, nullable) NSString *responseDate;
@property double responseEndTime;
@property unsigned long long responseMessageSize;
@property unsigned long long responseMessageSizeUncompressed;
@property double responseStartTime;
@property double secureConnectionStartTime;
@property long long statusCode;
@property (copy, nullable) NSString *storeFrontHeader;
@property (copy, nullable) NSString *TIDState;
@property BOOL TFOEnabled;
@property BOOL TLSSessionTickets;
@property unsigned long long urlCacheDiskCapacity;
@property unsigned long long urlCacheMemoryCapacity;
@property double urlCacheMaxCacheableEntrySizeRatio;
@property (copy, nullable) NSString *wt;
@property double xpSessionDuration;
@property BOOL xpSamplingForced;
@property double xpSamplingPercentageUsers;
@property double xpSamplingPercentageCachedResponses;
@property (copy, nullable) NSString *xxdc;

+ (id)_removeDateStringSeconds:(id)seconds;
+ (BOOL)isPerHostLoadURLSamplingEnabled:(id)enabled;
+ (BOOL)shouldCollectMetricsForContext:(id)context;
+ (id)_fetchNetworkQualityReportsPromise;
+ (double)_clampTimestamp:(double)timestamp;
+ (id)_buildVariant;
+ (id)_resolvedIPAddressFromTask:(id)task;
+ (id)_edgeRelayWasUsedFor:(id)_for domains:(id)domains;
+ (unsigned long long)_roundTransferBytesToNearestTens:(unsigned long long)tens;
+ (id)_radioTypeStringValueFromRadioType:(int)type;
+ (id)loadURLTopicFromContext:(id)context;
+ (double)_timingDataMetricToServerTimeInterval:(id)interval;
+ (id)_propertyValueClassesForKnownProperties;
+ (id)_isAnEdgeRelayServer:(id)server domains:(id)domains;
+ (id)shouldCollectMetricsPromiseForContext:(id)context;
+ (id)_hostnameFrom:(id)from;
+ (id)loadURLEventPromiseWithContext:(id)context;
+ (BOOL)isPerHostLoadURLSamplingEnabled:(id)enabled perHostSamplingSuppressed:(out BOOL *)suppressed featureFlagEnabled:(out BOOL *)enabled;
+ (id)_edgeRelayWasUsed:(id)used edgeRelayDomains:(id)domains;
+ (id)loadURLEventWithTopic:(id)topic context:(id)context;
+ (double)_samplingPercentageForURLSessionTask:(id)task performanceDictionary:(nullable NSDictionary *)dictionary;
+ (id)_DNSServerIPAddresses;

- (id)hardwareModel;
- (void)setHardwareModel:(id)model;
- (void)setOsBuildNumber:(id)number;
- (nonnull instancetype)initWithContext:(id)context;
- (void)setDecodedBodySize:(unsigned long long)size;
- (void)_forceLoadURLMetricsAlways;
- (BOOL)isDNUSubmissionAllowed;
- (void)_forceLoadURLMetricsDisabled;
- (unsigned long long)transferSize;
- (void)_addSharedURLCacheProperties;
- (void)setEncodedBodySize:(unsigned long long)size;
- (id)osBuildNumber;
- (unsigned long long)decodedBodySize;
- (void)applyPurchaseMetricsOverlay:(id)overlay;
- (void)setTransferSize:(unsigned long long)size;
- (id)_prepareEventPromiseWithContext:(id)context;
- (unsigned long long)encodedBodySize;

@end
