//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSAccountCachedServerDataServiceInterface-Protocol.h"
#include "AMSBagProtocol-Protocol.h"

@class v24@?0@";

@interface AMSMescalFairplaySession : NSObject { // (Swift)
	v24@?0@"<AMSAccountCachedServerDataServiceInterface>"8@"NSError"16 mescalType;
	v24@?0@"<AMSAccountCachedServerDataServiceInterface>"8@"NSError"16 cachedCertificateProvider;
	v24@?0@"<AMSAccountCachedServerDataServiceInterface>"8@"NSError"16 certificateCacher;
	v24@?0@"<AMSAccountCachedServerDataServiceInterface>"8@"NSError"16 queue;
}

- (nonnull instancetype)init;
- (nonnull instancetype)initWithMescalType:(long long)type cachedCertificateProvider:(UnknownBlock)provider certificateCacher:(UnknownBlock)cacher;
- (void)primeSignatureForData:(NSData *)data bag:(<AMSBagProtocol> *)bag logKey:(NSString *)key completionHandler:(UnknownBlock)handler;
- (void)signData:(NSData *)data bag:(<AMSBagProtocol> *)bag logKey:(NSString *)key completionHandler:(UnknownBlock)handler;
- (void)verifyData:(NSMutableData *)data signature:(NSData *)signature bag:(<AMSBagProtocol> *)bag logKey:(NSString *)key completionHandler:(UnknownBlock)handler;
- (void)verifyPrimeSignature:(NSData *)signature completionHandler:(UnknownBlock)handler;

@end
