//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSMetricsDatabase.h"
#include "AMSProcessInfo.h"

@class ACAccount;

@interface AMSMetricsIdentifierStore : NSObject {
	AMSMetricsDatabase *_database;
}

@property (retain, nonatomic, nullable) AMSMetricsIdentifierStore *debugUserIdStore;
@property (retain, nullable) ACAccount *account;
@property (retain, nullable) AMSProcessInfo *clientInfo;
@property (retain, nullable) NSString *domain;
@property BOOL includeAccountMatchStatus;
@property BOOL isActiveITunesAccountRequired;
@property double resetInterval;
@property BOOL shouldEmitDiagnosticFields;
@property BOOL shouldEmitPreviousUserId;

+ (id)identifierForAccount:(id)account bag:(id)bag bagNamespace:(id)_namespace keyName:(id)name;
+ (id)performUserResetForStoresInBag:(id)bag forAccount:(id)account;
+ (id)_parametersForBag:(id)bag bagNamespace:(id)_namespace;
+ (id)identifierStoreWithAccount:(id)account bagNamespace:(id)_namespace bag:(id)bag;
+ (id)_promiseOfListOfStoresInNamespaceList:(id)list forAccount:(id)account bag:(id)bag;
+ (id)_generateStoreKeyForAccount:(id)account domain:(id)domain clientInfo:(id)info;
+ (id)removeIdentifiersForStore:(id)store;
+ (void)removeIdentifiersForAccount:(id)account;
+ (void)cleanupIdentifiers;
+ (id)_identifierStoreWithAccount:(id)account parameters:(id)parameters;
+ (id)_identifierStoreInfoForKeys:(id)keys inDatabase:(id)database date:(id)date needsToSync:(BOOL *)sync account:(id)account clientInfo:(id)info domain:(id)domain resetInterval:(double)interval error:(id *)error;
+ (id)_promiseOfListOfNamespacesFromBag:(id)bag;
+ (id)_generateIdentifierKey:(id)key storeInfo:(id)info period:(long long)period resetInterval:(double)interval;
+ (id)_removeStoreForNamespace:(id)_namespace accountID:(id)id bag:(id)bag;
+ (id)_setConsumerIdentifier:(id)identifier forKey:(id)key inNamespace:(id)_namespace accountID:(id)id bag:(id)bag at:(id)at serverProvidedAt:(id)at skipSync:(BOOL)sync linkedKey:(id)key linkedNamespace:(id)_namespace;
+ (id)_database;
+ (BOOL)_isResetEnabledForList:(id)list;
+ (long long)_periodFrom:(double)from storeInfoStarted:(id)started now:(id)now;
+ (id)_accountIdentifierForAccount:(id)account;
+ (id)_applyExpiryForKey:(id)key inNamespace:(id)_namespace accountID:(id)id bag:(id)bag at:(id)at consumerIDResetInterval:(double)interval;
+ (id)_sync;
+ (id)_sharedQueue;
+ (id)shouldEnableResetUIFromBag:(id)bag;
+ (id)_promiseToRotateIdentifiersForAccount:(id)account bag:(id)bag namespaceList:(id)list;

- (nonnull instancetype)init;
- (void)reset;
- (id)generateEventFieldsForKeys:(id)keys;
- (id)_generateEventFieldsForKeys:(id)keys date:(id)date;
- (void)_generateFutureIdentifiersIfNeededForKeys:(id)keys storeInfo:(id)info afterPeriod:(long long)period inDatabase:(id)database date:(id)date;
- (id)_identifierInfoForKey:(id)key storeInfo:(id)info period:(long long)period inDatabase:(id)database date:(id)date setValue:(id)value lastSyncDate:(id)date needsToSync:(BOOL *)sync error:(id *)error;
- (id)_identifiersForKeys:(id)keys currentDate:(id)date;
- (void)_setIdentifier:(id)identifier withStartedDate:(id)date forKey:(id)key;
- (void)_setIdentifier:(id)identifier withStartedDate:(id)date lastSyncDate:(id)date forKey:(id)key;
- (id)generateEventFieldsForKeys:(id)keys date:(id)date;
- (id)identifierForKey:(id)key;
- (id)identifierIfExistsForKey:(id)key;
- (BOOL)isAccountValidForKey:(id)key activeItunesAccountDSID:(inout id *)dsid;
- (id)resetForcingStoreSync;
- (void)setIdentifier:(id)identifier forKey:(id)key;

@end
