//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSMetricsFlushStrategy-Protocol.h"
#include "AMSMetricsOperation.h"
#include "AMSMutablePromise.h"

@interface AMSMetricsFlushOperation : AMSMetricsOperation

@property (readonly) id <AMSMetricsFlushStrategy> strategy;
@property (readonly) AMSMutablePromise *promise;

- (nonnull instancetype)initWithStrategy:(id)strategy promise:(id)promise;

@end
