//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSMockURLResponse.h"
#include "AMSObservable.h"

@interface AMSMockURLOverride : NSObject <NSCopying>

@property (retain, nullable) NSMutableArray *comparators;
@property (retain, nullable) AMSObservable *executedObservable;
@property (retain, nullable) AMSMockURLResponse *response;

+ (id)overrideWithHost:(id)host usingResponse:(id)response;
+ (id)overrideWithPathComponent:(id)component usingResponse:(id)response;
+ (id)overrideWithURLRegex:(nullable NSURL *)urlregex usingResponse:(id)response;

- (nonnull instancetype)copyWithZone:(nullable struct _NSZone *)zone;
- (nonnull instancetype)init;
- (void)_withURLMatchingHost:(id)host containingPath:(id)path queryItems:(id)items;
- (BOOL)shouldOverrideURLRequest:(nullable NSURL *)urlrequest;
- (void)withHTTPBodyValidation:(UnknownBlock)validation encoding:(long long)encoding;
- (void)withHTTPHeaderValidation:(UnknownBlock)validation;
- (void)withResponse:(id)response;
- (void)withURLContainingPath:(id)path;
- (void)withURLMatchingHost:(id)host;
- (void)withURLQueryItems:(id)items;
- (void)withURLRegexValidation:(id)validation;

@end
