//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSMediaRestrictionsRatingItem.h"

@interface AMSMediaRestrictionsValue : NSObject {
	void * /* unknown */ _value;
}

@property (nonatomic, readonly) long long valueType;
@property (nonatomic, readonly) id _value;
@property (nonatomic, readonly) AMSMediaRestrictionsRatingItem *ratingItem;
@property (nonatomic, readonly) BOOL boolValue;
@property (nonatomic, readonly) NSString *stringValue;
@property (nonatomic, readonly) long long integerValue;
@property (nonatomic, readonly) id dictionaryValue;

+ (id)withString:(id)string;
+ (id)withRatingItem:(id)item;
+ (id)withBool:(BOOL)_bool;
+ (id)withInt:(long long)_int;

- (nonnull instancetype)init;
- (nonnull instancetype)initWithBoolValue:(BOOL)value;
- (nonnull instancetype)initWithStringValue:(id)value;
- (nonnull instancetype)initWithIntValue:(long long)value;
- (nonnull instancetype)initWithRatingItem:(id)item;

@end
