//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSMetricsEvent.h"

@interface AMSMetricsLoggingEvent : AMSMetricsEvent <NSMutableCopying>

@property (copy, nullable) NSDictionary *breadcrumbs;
@property (readonly) NSString *category;
@property (copy, nullable) NSString *clientApp;
@property (copy, nullable) NSString *clientBuildType;
@property (copy, nullable) NSString *currentProcess;
@property (copy, nullable) NSString *engagementEventType;
@property (readonly) NSError *error;
@property long long errorCode;
@property (copy, nullable) NSString *errorDomain;
@property (copy, nullable) NSString *errorMessage;
@property (copy, nullable) NSString *errorTitle;
@property long long errorUserInfoCryptoCode;
@property BOOL errorUserInfoEngagementPresented;
@property long long errorUserInfoServerErrorCode;
@property long long errorUserInfoStatusCode;
@property (copy, nullable) NSArray *eventDestinations;
@property double eventEndTime;
@property BOOL eventInlineInterruption;
@property (copy, nullable) NSString *eventParamEventType;
@property (copy, nullable) NSString *eventParamItemId;
@property (copy, nullable) NSString *eventParamProductType;
@property (copy, nullable) NSString *eventParamSource;
@property (copy, nullable) NSString *eventParamSuccess;
@property (copy, nullable) NSString *eventPlacement;
@property (copy, nullable) NSString *eventServiceType;
@property double eventStartTime;
@property (copy, nonatomic, nullable) NSDictionary *jsVersions;
@property (copy, nullable) NSArray *jsVersionMap;
@property (readonly) NSString *lastBreadcrumb;
@property (readonly) double lastBreadcrumbDuration;
@property long long logLevel;
@property (copy, nullable) NSString *originatingURL;
@property (copy, nullable) NSString *originatingURLParamBagProfile;
@property (copy, nullable) NSString *originatingURLParamBagProfileVersion;
@property (copy, nullable) NSString *releaseVersion;
@property (readonly) NSString *subsystem;
@property (readonly) NSMutableDictionary *underlyingDictionaryForSentry;
@property long long underlyingErrorCode;
@property (copy, nullable) NSString *underlyingErrorDomain;
@property (copy, nullable) NSString *underlyingErrorMessage;
@property (copy, nullable) NSString *underlyingErrorTitle;
@property long long underlyingErrorUserInfoCryptoCode;
@property BOOL underlyingErrorUserInfoEngagementPresented;
@property long long underlyingErrorUserInfoServerErrorCode;
@property long long underlyingErrorUserInfoStatusCode;
@property (copy, nullable) NSString *url;
@property (copy, nullable) NSString *urlParamBagProfile;
@property (copy, nullable) NSString *urlParamBagProfileVersion;

+ (id)_propertyValueClassesForKnownProperties;
+ (id)shouldSampleErrorsWithBag:(id)bag;

- (id)getBuildType;
- (nonnull instancetype)copyWithZone:(nullable struct _NSZone *)zone;
- (id)mutableCopyWithZone:(struct _NSZone *)zone;
- (id)cleanURL:(nullable NSURL *)url;
- (nonnull instancetype)initWithSubsystem:(id)subsystem category:(id)category error:(nullable NSError *)error;
- (void)prepareEvent;
- (id)stringForLogLevel:(long long)level;
- (id)underlyingDictionaryOverride;

@end
