//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSBagConsumer-Protocol.h"
#include "AMSBagProtocol-Protocol.h"
#include "AMSMediaTokenServiceProtocol-Protocol.h"
#include "AMSMetricsLoadURLOverlay.h"
#include "AMSProcessInfo.h"
#include "AMSRequestEncoding-Protocol.h"
#include "AMSResponseDecoding-Protocol.h"
#include "AMSURLRequestEncoder.h"

@class ACAccount;

@interface AMSMediaRequestEncoder : NSObject <AMSBagConsumer, AMSRequestEncoding> {
	AMSURLRequestEncoder *_requestEncoder;
}

@property BOOL URLKnownToBeTrusted;
@property (retain, nullable) ACAccount *account;
@property BOOL alwaysIncludeAuthKitHeaders;
@property BOOL alwaysIncludeMMeClientInfoAndDeviceHeaders;
@property (readonly) id <AMSBagProtocol> bag;
@property (retain, nullable) AMSProcessInfo *clientInfo;
@property BOOL compressRequestBody;
@property BOOL disableResponseDecoding;
@property (retain, nullable) NSString *gsTokenIdentifier;
@property BOOL excludeIdentifierHeadersForAccount;
@property (retain, nullable) NSString *logKey;
@property long long requestEncoding;
@property (retain, nullable) id <AMSResponseDecoding> responseDecoder;
@property (readonly) id <AMSMediaTokenServiceProtocol> tokenService;
@property (retain, nullable) AMSMetricsLoadURLOverlay *loadURLOverlay;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)createBagForSubProfile;
+ (id)bagSubProfileVersion;
+ (id)bagSubProfile;

- (id)requestByEncodingRequest:(id)request parameters:(id)parameters;
- (id)requestWithComponents:(id)components;
- (nonnull instancetype)initWithTokenService:(id)service bag:(id)bag;
- (id)requestWithURL:(nullable NSURL *)url;

@end
