//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSMetricsFlushStrategy-Protocol.h"

@protocol AMSMetricsFlushTask <AMSMetricsFlushStrategy>

@required

- (nonnull instancetype)initWithDataSource:(id)source bag:(id)bag maxRequestCount:(unsigned long long)count maxEventsPerBatch:(unsigned long long)batch topic:(id)topic regexCache:(id)cache includeMMeClientInfoAndDeviceHeaders:(BOOL)headers metricsSigningFlavour:(unsigned long long)flavour urlSession:(id)session;

@optional

@end
