//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSPromise.h"

@interface AMSMutablePromise : AMSPromise

+ (id)promiseWithAll:(id)all timeout:(double)timeout;
+ (void)startTimeoutForPromise:(id)promise timeout:(double)timeout;
+ (BOOL)_finishPromise:(id)promise withResult:(id)result error:(nullable NSError *)error logDuplicateFinishes:(BOOL)finishes;
+ (id)promiseWithAny:(id)any;
+ (id)promiseWithAny:(id)any timeout:(double)timeout;
+ (BOOL)finishPromise:(id)promise withPromise:(id)promise;
+ (BOOL)finishPromise:(id)promise withResult:(id)result;
+ (BOOL)finishPromise:(id)promise withError:(nullable NSError *)error;
+ (BOOL)finishPromise:(id)promise withResult:(id)result error:(nullable NSError *)error;
+ (BOOL)cancelPromise:(id)promise;
+ (id)promiseWithAll:(id)all;
+ (id)promiseWithFlattenedPromises:(id)promises;

- (BOOL)finishWithResult:(id)result;
- (BOOL)finishWithResult:(id)result error:(nullable NSError *)error;
- (id)_mutablePromiseWrappingPromise:(id)promise;
- (id)catchWithBlock:(UnknownBlock)block;
- (BOOL)cancel;
- (BOOL)finishWithResult:(id)result error:(nullable NSError *)error logDuplicateFinishes:(BOOL)finishes;
- (id)continueWithBinaryPromiseBlock:(UnknownBlock)block;
- (BOOL)finishWithError:(nullable NSError *)error;
- (id)continueWithBlock:(UnknownBlock)block;
- (nonnull instancetype)initWithTimeout:(double)timeout;
- (BOOL)finishWithPromiseResult:(id)result;
- (id)catchWithBinaryPromiseBlock:(UnknownBlock)block;
- (BOOL)finishWithPromise:(id)promise;
- (id)thenWithBlock:(UnknownBlock)block;
- (id)_mutableBinaryPromiseWrappingBinaryPromise:(id)promise;
- (id)thenWithBinaryPromiseBlock:(UnknownBlock)block;
- (id)promiseWithTimeout:(double)timeout;
- (void)startTimeout:(double)timeout;

@end
