//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@interface AMSMetricsIdentifierCore : NSObject

+ (id)_removeU13Identifier:(id)identifier account:(id)account;
+ (BOOL)_shouldReplaceInfo:(id)info withInfo:(id)info isServerRecord:(BOOL)record;
+ (BOOL)_shouldUpdateDatabaseFor:(id)_for consumerIDResetInterval:(double)interval;

@end
