//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSMediaTokenServicePATFetcherProtocol-Protocol.h"

@interface AMSMediaTokenServicePATFetcher : NSObject <AMSMediaTokenServicePATFetcherProtocol>

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)challengeDictFor:(id)_for;
+ (id)fetchToken:(id)token dispatchQueue:(id)queue;
+ (id)fetchTokenWithChallenge:(id)challenge dispatchQueue:(id)queue;
+ (id)fetcherWithChallenge:(id)challenge tokenKey:(id)key;
+ (id)tokenChallengeWith:(id)with redemptionNonce:(id)nonce originName:(id)name;

@end
