//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSPromise.h"

@interface AMSMediaInvokeAuthenticationCoordinator : NSObject

@property (readonly) struct os_unfair_lock_s { unsigned int x0; } queueLock;
@property (readonly) NSMutableArray *invokeAuthQueue;
@property (retain, nullable) AMSPromise *inflightAuthPromise;

+ (id)sharedInstance;

- (nonnull instancetype)init;
- (void)_finishQueueWithAuthResult:(id)result queuedObjects:(id)objects;
- (id)addToQueueAndPerformAuthFromResponseIfNeeded:(id)needed taskInfo:(id)info;
- (id)performAuthFromResponse:(id)response taskInfo:(id)info;
- (void)updateQueueIfNeeded;

@end
