//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSMediaTokenServiceProtocol-Protocol.h"
#include "AMSURLSession.h"

@interface AMSMediaSharedProperties : NSObject

@property (readonly, copy, nonatomic) NSString *clientIdentifier;
@property long long activeTaskCount;
@property (retain, nullable) NSTimer *cleanupTimer;
@property (retain, nullable) NSDate *lastAccessTime;
@property double timeout;
@property (readonly) AMSURLSession *session;
@property (readonly) id <AMSMediaTokenServiceProtocol> tokenService;

+ (id)accessQueue;
+ (id)propertiesForMarketingItemTask:(id)task;
+ (id)_propertiesForClientIdentifier:(id)identifier account:(id)account bag:(id)bag clientInfo:(id)info URLKnownToBeTrusted:(BOOL)trusted URLSessionConfiguration:(id)configuration task:(id)task;
+ (id)_propertiesForClientIdentifier:(id)identifier account:(id)account bag:(id)bag clientInfo:(id)info URLKnownToBeTrusted:(BOOL)trusted task:(id)task;
+ (id)propertiesForMediaTask:(id)task;
+ (id)propertiesForMercuryCacheFetchTask:(id)task;
+ (id)propertiesForNotificationSettingsTask:(id)task;
+ (id)propertiesForRatingsTask:(id)task;
+ (id)propertiesForStorefrontsTask:(id)task;
+ (id)propertiesForUserNotificationSettingsTask:(id)task;
+ (id)sharedPropertiesMapTable;

- (void)_performCleanup;
- (id)getTokenService;
- (void)_cancelCleanupTimer;
- (id)_initWithClientIdentifier:(id)identifier account:(id)account bag:(id)bag clientInfo:(id)info URLKnownToBeTrusted:(BOOL)trusted URLSessionConfiguration:(id)configuration;
- (void)_scheduleCleanupWithTimeout:(double)timeout;
- (void)_taskDidFinish;
- (void)_taskDidStart;
- (id)getSession;

@end
