//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSAccountCachedServerDataServiceInterface-Protocol.h"
#include "OS_nw_activity-Protocol.h"

@class v24@?0@";

@interface AMSMetricsActivity : NSObject { // (Swift)
	v24@?0@"<AMSAccountCachedServerDataServiceInterface>"8@"NSError"16 activity;
}

@property (nonatomic, readonly) id <OS_nw_activity> nwActivity;

- (nonnull instancetype)initWithLabel:(long long)label;
- (void)activate;
- (nonnull instancetype)init;
- (nonnull instancetype)initWithActivity:(id)activity;
- (void)completeAfter:(id)after;
- (nonnull instancetype)initWithLabel:(long long)label parent:(id)parent;

@end
