//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSEngagementEvent-Protocol.h"

@class ACAccount;

@interface AMSMetricsEvent : NSObject <NSCopying, NSSecureCoding, AMSEngagementEvent> {
	struct os_unfair_lock_s { unsigned int _os_unfair_lock_opaque; } _internalStateLock;
}

@property (readonly, nonatomic) NSDate *clientOnlyEventDate;
@property (copy, nonatomic, nullable) NSString *enqueueTimeAccountIdentifier;
@property (nonatomic) BOOL enqueueTimeAccountUnderThirteen;
@property (copy, nonatomic, nullable) NSString *clientEventID;
@property (readonly, nonatomic) NSDictionary *databaseEventBody;
@property (readonly, nonatomic) NSNumber *databasePID;
@property (readonly, nonatomic) BOOL engagementEvent;
@property (readonly, nonatomic) NSDictionary *engagementMetrics;
@property (nonatomic) BOOL checkDiagnosticsAndUsageSetting;
@property (copy, nonatomic, nullable) NSString *diagnosticsSubmissionBugType;
@property (readonly, nonatomic) NSDictionary *dictionaryForPosting;
@property (nonatomic) BOOL preventSampling;
@property (readonly, nonatomic) NSDictionary *underlyingDictionary;
@property (readonly, nonatomic) NSDictionary *underlyingDictionaryOverride;
@property (retain, nonatomic, nullable) ACAccount *account;
@property (nonatomic) BOOL anonymous;
@property (copy, nonatomic, nullable) NSString *app;
@property (copy, nonatomic, nullable) NSString *appVersion;
@property (retain, nonatomic, nullable) NSNumber *baseVersion;
@property (copy, nonatomic, nullable) NSString *canaryIdentifier;
@property (copy, nonatomic, nullable) NSString *clientIdentifier;
@property (copy, nullable) NSString *canonicalAccountIdentifierOverride;
@property BOOL enableAccountIdentifierAutoDecoration;
@property (retain, nonatomic, nullable) NSNumber *eventTime;
@property (copy, nonatomic, nullable) NSString *eventType;
@property (retain, nonatomic, nullable) NSNumber *eventVersion;
@property (copy, nonatomic, nullable) NSString *osBuildVersion;
@property (copy, nonatomic, nullable) NSString *osName;
@property (copy, nonatomic, nullable) NSString *osVersion;
@property (nonatomic) BOOL suppressEngagement;
@property (retain, nonatomic, nullable) NSNumber *timezoneOffset;
@property (copy, nonatomic, nullable) NSString *topic;
@property (readonly) NSDictionary *engagementData;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (BOOL)supportsSecureCoding;
+ (id)_propertyValueClassesForKnownProperties;
+ (id)_buyParamsFromString:(id)string;
+ (id)_buyParamsStringFromAuthenticationContext:(id)context;
+ (id)_deepCopiedAndSanitizedTopLevelDictionaryFromDictionary:(nullable NSDictionary *)dictionary;
+ (id)_deepCopiedJSONObjectOrNilForObject:(id)object;
+ (id)_deepCopiedJSONObjectOrNilForObject:(id)object key:(id)key enforcingClassUsingKnownPropertiesClassMapping:(id)mapping;
+ (id)_topicFromAuthenticationContext:(id)context;
+ (id)createEventFromAuthenticationContext:(id)context error:(nullable NSError *)error;
+ (id)metricsAuthenticationAttemptDictionaryForAuthKitError:(nullable NSError *)error;
+ (id)sanitizedObject:(id)object;

- (nonnull instancetype)copyWithZone:(nullable struct _NSZone *)zone;
- (void)encodeWithCoder:(nullable NSCoder *)coder;
- (BOOL)isAnonymous;
- (nonnull instancetype)initWithCoder:(nullable NSCoder *)coder;
- (nonnull instancetype)initWithTopic:(id)topic;
- (void)setProperty:(id)property forBodyKey:(id)key;
- (id)_propertyForBodyKey:(id)key clientOnly:(BOOL)only;
- (BOOL)enqueueTimeUnderThirteenAccount;
- (id)_initWithSanitizedUnderlyingDictionary:(nullable NSDictionary *)dictionary account:(id)account databasePID:(id)pid;
- (id)_initWithUnderlyingDictionary:(nullable NSDictionary *)dictionary account:(id)account databasePID:(id)pid addBasefields:(BOOL)basefields;
- (void)_setProperty:(id)property forBodyKey:(id)key clientOnly:(BOOL)only;
- (void)addClientIdentifier:(id)identifier;
- (void)addPropertiesWithDictionary:(nullable NSDictionary *)dictionary;
- (nonnull instancetype)initForEngagement;
- (nonnull instancetype)initWithDatabaseEventBody:(id)body account:(id)account databasePID:(id)pid;
- (nonnull instancetype)initWithUnderlyingDictionary:(nullable NSDictionary *)dictionary;
- (BOOL)isAccountIdentifierAutoDecorationEnabled;
- (void)modifyEventWithReplacementsForDictionary:(nullable NSDictionary *)dictionary regexCache:(id)cache;
- (id)propertyForBodyKey:(id)key;
- (void)removePropertiesForKeys:(id)keys;
- (void)setEnqueueTimeUnderThirteenAccount:(BOOL)account;

@end
