//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@interface AMSMediaTokenServiceThrottler : NSObject

@property unsigned long long attemptNumber;
@property (retain, nullable) NSDate *throttleDate;
@property (readonly, nonatomic) struct os_unfair_lock_s { unsigned int x0; } accessLock;
@property (readonly, nonatomic) double baseSleepInterval;
@property (readonly, nonatomic) double maxSleepInterval;

- (void)throttle;
- (nonnull instancetype)initWithBaseSleepInterval:(double)interval maxSleepInterval:(double)interval;
- (BOOL)shouldThrottle;
- (void)setBaseSleepInterval:(double)interval maxSleepInterval:(double)interval;
- (double)_calculateThrottleInterval;
- (void)reset;

@end
