//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSBagConsumer-Protocol.h"

@interface AMSMarketingItemTaskURLBuilder : NSObject <AMSBagConsumer>

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)bagSubProfileVersion;
+ (id)bagSubProfile;
+ (id)bagKeySet;

- (id)_additionalQueryItems;
- (id)_countryCodeFromBag:(id)bag;
- (id)_formattedURLPathWithBag:(id)bag;
- (id)_languageTagFromBag:(id)bag fallback:(id)fallback;
- (id)_realmOverridesFromBag:(id)bag;
- (id)_stringForKey:(id)key fromBag:(id)bag;
- (id)_urlPathFromBag:(id)bag;
- (nullable NSURL *)urlWithServiceType:(id)type placement:(id)placement bag:(id)bag hydrateRelatedContents:(BOOL)contents offerHints:(id)hints additionalParameters:(id)parameters;

@end
