//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@interface AMSMediaRestrictionsRatingItem : NSObject <NSCoding, NSSecureCoding>

@property (nonatomic, readonly) NSString *ratingSystem;
@property (nonatomic, readonly) NSNumber *ratingValue;
@property (nonatomic, readonly) NSDictionary *dictionaryRepresentation;
@property (nonatomic, readonly) long long hash;
@property (nonatomic, readonly) NSString *description;

+ (BOOL)supportsSecureCoding;

- (nonnull instancetype)initWithDictionary:(nullable NSDictionary *)dictionary;
- (void)encodeWithCoder:(nullable NSCoder *)coder;
- (BOOL)isEqual:(nullable id)object;
- (nonnull instancetype)init;
- (nonnull instancetype)initWithCoder:(nullable NSCoder *)coder;
- (nonnull instancetype)initWithRatingSystem:(id)system intValue:(long long)value;
- (nonnull instancetype)initWithRatingSystem:(id)system numberValue:(id)value;

@end
