//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSBagConsumer-Protocol.h"
#include "AMSBagProtocol-Protocol.h"
#include "AMSEngagement.h"
#include "AMSMetricsBagContract-Protocol.h"
#include "AMSMetricsDatabaseDataSource.h"
#include "AMSMetricsFlushOperation.h"
#include "AMSMetricsProtocol-Protocol.h"
#include "AMSMetricsRegexCache.h"
#include "AMSTreatmentStore.h"
#include "AMSURLSession.h"

@interface AMSMetrics : NSObject <AMSMetricsProtocol, AMSBagConsumer> {
	NSMutableArray *_enqueuedOperations;
	AMSMetricsFlushOperation *_currentFlushOperation;
	struct os_unfair_lock_s { unsigned int _os_unfair_lock_opaque; } _enqueuedOperationsLock;
	struct os_unfair_lock_s { unsigned int _os_unfair_lock_opaque; } _flushModeLock;
	Class _flushTaskClass;
	struct os_unfair_lock_s { unsigned int _os_unfair_lock_opaque; } _bagLock;
}

@property long long destination;
@property struct os_unfair_lock_s { unsigned int x0; } engagementLock;
@property BOOL flushingDisabled;
@property (copy, nullable) UnknownBlock flushOnDidBecomeActiveBlock;
@property (copy, nullable) UnknownBlock flushIntervalBlock;
@property (readonly) AMSURLSession *URLSession;
@property (readonly) AMSMetricsRegexCache *regexCache;
@property (retain, nullable) AMSEngagement *engagement;
@property (retain, nullable) AMSTreatmentStore *treatmentStore;
@property (retain, nullable) AMSMetricsDatabaseDataSource *databaseSource;
@property (retain, nullable) id <AMSMetricsBagContract> bagContract;
@property (retain, nullable) id <AMSBagProtocol> bag;
@property (readonly) NSString *containerId;
@property (readonly) long long eventCount;
@property BOOL flushTimerEnabled;
@property BOOL includeMMeClientInfoAndDeviceHeaders;
@property long long maxBatchSize;
@property long long maxEventsPerBatch;
@property long long maxRequestCount;
@property unsigned long long metricsSigningFlavour;
@property BOOL monitorsLifecycleEvents;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)createBagForSubProfile;
+ (id)bagSubProfileVersion;
+ (id)bagSubProfile;
+ (BOOL)recordAppAnalyticsForEvent:(id)event bugType:(id)type;
+ (BOOL)disableBackgroundMetrics;
+ (id)serverTimeFromDate:(id)date;
+ (BOOL)flushTimerEnabled;
+ (id)_createURLSessionPromiseWith:(id)with;
+ (id)bagKeySet;
+ (void)_configureAccountIdentifierForEvent:(id)event andActiveAccount:(id)account;
+ (id)_defaultAccountClearingTopics;
+ (void)setFlushDelayEnabled:(BOOL)enabled;
+ (id)_makeMetricsEventAnomaliesDetector;
+ (BOOL)appAnalyticsAllowed;
+ (BOOL)diagnosticsSubmissionAllowed;
+ (void)setDisableBackgroundMetrics:(BOOL)metrics;
+ (id)_urlSessionPromiseWith:(id)with;
+ (id)internalInstanceUsingBag:(id)bag;
+ (id)serverTimeFromTimeInterval:(double)interval;
+ (id)sharedTimerQueue;
+ (void)setFlushTimerEnabled:(BOOL)enabled;
+ (void)_detectAnomaliesForMetricsEvent:(id)event;
+ (double)timeIntervalFromServerTime:(id)time;
+ (BOOL)flushDelayEnabled;

- (void)dropEvents;
- (id)promiseForEnqueueingEvents:(id)events;
- (void)_flushTimerEnabledChanged;
- (void)enqueueEvent:(id)event;
- (double)_flushIntervalWithConfiguration:(id)configuration forEvents:(id)events;
- (void)enqueueEvents:(id)events;
- (id)promiseForEnqueueingEvents:(id)events options:(long long)options;
- (void)_flushIntervalInvalidate;
- (id)flush;
- (id)flushTopic:(id)topic;
- (void)cancel;
- (id)_topicsRequiringAccountClearing;
- (void)_processOperationQueue;
- (id)_cachedAccountClearingTopicsFromBag;
- (id)_determineFlushStrategyWithDataSource:(id)source topic:(id)topic urlSession:(id)session;
- (void)_clearAccountForEventIfNeeded:(id)needed;
- (id)_flushDataSource:(id)source topic:(id)topic;
- (id)flushEvents:(id)events;
- (void)_applicationDidBecomeActive:(id)active;
- (id)_enqueueFigaroEvents:(id)events scheduleDelayedFlush:(BOOL)flush;
- (nonnull instancetype)initWithContainerID:(id)id bag:(id)bag flushTaskClass:(Class)_class;
- (BOOL)_scheduledFlushAllowedForStyle:(long long)style;
- (void)_beginFlushIntervalWithStyle:(long long)style events:(id)events;
- (id)_modifiedEvents:(id)events;
- (nonnull instancetype)initWithContainerId:(id)id bagContract:(id)contract;
- (id)_handleFlushIntervalWithStyle:(long long)style;
- (id)enqueueAsyncEvents:(id)events scheduleDelayedFlush:(BOOL)flush;
- (void)dealloc;
- (nonnull instancetype)initWithContainerID:(id)id bag:(id)bag;

@end
