//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSMetricsFigaroEventModifier.h"

@protocol OS_dispatch_queue;

@interface AMSMetricsFigaroBagConfguration : NSObject

@property (readonly, nonatomic) NSDictionary *metricsDictionary;
@property (readonly, nonatomic) NSArray *overrides;
@property (readonly, nonatomic) AMSMetricsFigaroEventModifier *defaultModifier;
@property (readonly, nonatomic) dispatch_queue_t queue;
@property (readonly, nonatomic) unsigned long long maxBatchSize;

+ (id)configurationPromiseWithBag:(id)bag;

- (id)_generateModifiersIfNeeded;
- (id)modifierForEvent:(id)event;
- (nonnull instancetype)initWithMetricsDictionary:(nullable NSDictionary *)dictionary;
- (void)prepareForFlush;

@end
