//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@interface AMSMetricsIdentifierKey : NSObject

@property BOOL crossDeviceSync;
@property (retain, nullable) NSString *name;
@property BOOL isActiveITunesAccountRequired;
@property BOOL provideU13Identifier;

+ (id)keyWithName:(id)name crossDeviceSync:(BOOL)sync;
+ (id)keyWithName:(id)name crossDeviceSync:(BOOL)sync isActiveITunesAccountRequired:(BOOL)required;
+ (id)keyWithName:(id)name crossDeviceSync:(BOOL)sync isActiveITunesAccountRequired:(BOOL)required provideU13Identifier:(BOOL)identifier;

- (nonnull NSString *)description;

@end
