//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSMockURLOverride.h"

@class NSURLProtocol;

@interface AMSMockNetworkProxy : NSURLProtocol

@property (retain, nullable) AMSMockURLOverride *currentOverride;

+ (void)clearOverrides;
+ (id)canonicalRequestForRequest:(id)request;
+ (BOOL)canInitWithRequest:(id)request;
+ (void)removeOverride:(id)override;
+ (void)addOverride:(id)override;
+ (void)_sync:(UnknownBlock)_sync;
+ (id)_executedOverrides;
+ (id)_overrides;
+ (void)_removeAllOverrides;
+ (void)_removeOverride:(id)override;
+ (id)executedOverrides;
+ (id)registeredOverrides;

- (void)startLoading;
- (void)finishWithError:(nullable NSError *)error;
- (void)sendResponse:(id)response;
- (void)stopLoading;
- (void)finishWithData:(id)data;
- (void)performRedirectFromResponse:(id)response;

@end
