//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSSQLiteConnection.h"
#include "AMSSQLiteConnectionDelegate-Protocol.h"

@protocol OS_dispatch_queue;

@interface AMSMetricsDatabase : NSObject <AMSSQLiteConnectionDelegate>

@property (retain, nullable) AMSSQLiteConnection *connection;
@property (retain, nullable) dispatch_queue_t internalQueue;
@property (retain, nullable) NSString *containerId;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)sharedDatabaseWithContainerId:(id)id;

- (BOOL)removeCrossDeviceIdentifiersWithError:(id *)error;
- (id)_lockedById;
- (BOOL)removeIdentifiersForStore:(id)store error:(id *)error;
- (nonnull instancetype)initWithContainerId:(id)id;
- (BOOL)unlockEvents:(id)events error:(id *)error;
- (BOOL)permanentlyRemoveIdentifierForKey:(id)key error:(id *)error;
- (id)_cachePath;
- (BOOL)cleanupInvalidIdentifiersWithError:(id *)error;
- (BOOL)dropAllEventsWithLockKey:(id)key error:(id *)error;
- (BOOL)unlockAllEventsWithKey:(id)key error:(id *)error;
- (id)lockAllEventsWithError:(id *)error;
- (BOOL)enumerateUnsyncedIdentifierStoresUsingBlock:(UnknownBlock)block error:(id *)error;
- (BOOL)clearIdentifierSyncStateWithError:(id *)error;
- (BOOL)connection:(id)connection needsResetForCorruptionError:(nullable NSError *)error error:(out id *)error;
- (void)close;
- (BOOL)dropEvents:(id)events error:(id *)error;
- (long long)countAllEventsWithLockKey:(id)key error:(id *)error;
- (BOOL)enumerateUnsyncedIdentifiersUsingBlock:(UnknownBlock)block error:(id *)error;
- (void)_performTransaction:(UnknownBlock)transaction;
- (void)enumerateEventsWithTopic:(id)topic lockKey:(id)key objectBlock:(UnknownBlock)block;
- (id)identifierStoreForKey:(id)key updateMaybe:(UnknownBlock)maybe error:(id *)error;
- (BOOL)insertEvents:(id)events error:(id *)error;
- (void)dealloc;
- (BOOL)removeIdentifiersForAccount:(id)account error:(id *)error;
- (id)identifierForKey:(id)key updateMaybe:(UnknownBlock)maybe error:(id *)error;

@end
