//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@interface AMSMethodImplementationCache : NSObject // (Swift)

+ (void *)implementationOf:(SEL)of forInstancesOf:(Class)of;
+ (BOOL)implementationsOf:(SEL)of areEqualIn:(Class)in and:(Class)_and;

- (nonnull instancetype)init;

@end
