//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSBuyParams.h"

@interface AMSMarketingItemAction : NSObject

@property (retain, nullable) NSDictionary *rawValues;
@property (readonly) AMSBuyParams *buyParams;
@property (readonly) NSString *callToActionLabel;
@property (readonly) NSString *disclaimerText;
@property (readonly) BOOL isDefault;
@property (readonly) BOOL isFamily;
@property (readonly) BOOL isRecommended;
@property (readonly) NSString *offerID;
@property (readonly) NSNumber *price;
@property (readonly) NSString *priceForDisplay;
@property (readonly) NSNumber *priceDiff;
@property (readonly) NSString *priceDiffForDisplay;
@property (readonly) NSString *valuePropDetail;
@property (readonly) NSString *valuePropInfo;
@property (readonly) NSArray *serviceComponents;
@property (readonly) NSString *type;
@property (readonly) NSURL *url;

- (nonnull instancetype)initWithDictionary:(nullable NSDictionary *)dictionary;
- (id)name;
- (nonnull NSString *)description;
- (id)priceFormatted;
- (id)freeTrialPeriod;
- (id)inAppID;
- (id)introOfferPrice;
- (id)_serviceComponentsFromMap:(id)map withNames:(id)names;
- (id)_serviceNames;
- (id)_servicesData;
- (id)dismissLabel;
- (id)introOfferPeriod;
- (id)introOfferPriceForDisplay;
- (BOOL)isYearly;
- (id)priceString;
- (id)recurringSubscriptionPeriod;

@end
