//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSMediaToken.h"
#include "AMSMediaTokenServiceKeychainStoreProtocol-Protocol.h"
#include "AMSMediaTokenServiceStoreProtocol-Protocol.h"

@interface AMSMediaTokenServiceStore : NSObject <AMSMediaTokenServiceStoreProtocol>

@property (readonly, nonatomic) struct os_unfair_lock_s { unsigned int x0; } accessLock;
@property (retain, nonatomic, nullable) AMSMediaToken *memoryMediaToken;
@property (readonly, nonatomic) id <AMSMediaTokenServiceKeychainStoreProtocol> keychainStore;
@property (nonatomic) BOOL patBasedToken;
@property (readonly, nonatomic) NSString *notificationObject;
@property (readonly, copy, nonatomic) NSString *clientIdentifier;
@property (readonly, nonatomic) BOOL usingAccessControlIdentifier;
@property (copy, nonatomic, nullable) NSString *keychainAccessGroup;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (BOOL)_hasAppleGroupEnabled;

- (id)_mediaTokenChangedNotificationName;
- (void)_setupKeychainNotifications;
- (void)_mediaTokenChanged:(id)changed;
- (nonnull instancetype)initWithClientIdentifier:(id)identifier keychainAccessGroup:(id)group usingAccessControlIdentifier:(BOOL)identifier patBasedToken:(BOOL)token;
- (id)_keychainAccessGroup;
- (void)_postMediaTokenChangedNotification;
- (id)storeToken:(id)token;
- (void)_teardownKeychainNotifications;
- (nonnull instancetype)initWithClientIdentifier:(id)identifier keychainStore:(id)store patBasedToken:(BOOL)token;
- (id)deleteToken;
- (id)retrieveToken;
- (nonnull instancetype)initWithClientIdentifier:(id)identifier keychainAccessGroup:(id)group patBasedToken:(BOOL)token;
- (void)dealloc;

@end
