//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSAccountCachedServerDataServiceInterface-Protocol.h"

@class v24@?0@";

@interface AMSMediaRestrictionsPerformer : NSObject { // (Swift)
	v24@?0@"<AMSAccountCachedServerDataServiceInterface>"8@"NSError"16 manager;
}

+ (id)accountCachedDataForAccount:(id)account;
+ (void)clearCachedDataUpdateDate;
+ (id)getLastCachedDataUpdateDate;

- (nonnull instancetype)init;
- (id)disableRestrictions;
- (id)editProfileLockWithPasscode:(id)passcode;
- (id)editWithRestricitons:(id)restricitons;
- (nonnull instancetype)initWithAccount:(id)account bag:(id)bag urlSessionDelegate:(id)delegate;
- (nonnull instancetype)initWithAccount:(id)account editToken:(id)token bag:(id)bag urlSessionDelegate:(id)delegate;
- (id)performSetupWithRestrictions:(id)restrictions;
- (id)removeProfileLock;
- (id)removeProfileLockWithPasscode:(id)passcode;
- (id)setupProfileLockWithPasscode:(id)passcode;
- (id)verifyProfileLockWithPasscode:(id)passcode;

@end
