//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@protocol AMSMetricsIdentifierCloudDataSourceDelegate;

@interface AMSMetricsIdentifierCloudDataSource : NSObject

@property (weak) id <AMSMetricsIdentifierCloudDataSourceDelegate> delegate;

+ (void)cleanupIdentifiers;
+ (id)_database;
+ (id)_sharedQueue;
+ (id)_saveCloudObject:(id)object intoDatabase:(id)database isServerRecord:(BOOL)record;
+ (id)_saveIdInfo:(id)info intoDatabase:(id)database isServerRecord:(BOOL)record;
+ (id)_saveStoreInfo:(id)info intoDatabase:(id)database isServerRecord:(BOOL)record;
+ (void)clearSyncState;
+ (void)removeAllRecords;

- (id)_parseRecord:(id)record error:(id *)error;
- (void)saveRecord:(id)record isServerRecord:(BOOL)record;
- (void)fetchModifiedRecordsWithCompletion:(UnknownBlock)completion;
- (void)removeRecordWithIdentifier:(id)identifier;
- (id)_createRecordForIdentifierStore:(id)store;
- (id)_createRecordForIdentifier:(id)identifier;

@end
