//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSBagProtocol-Protocol.h"
#include "AMSBuyParams.h"
#include "AMSProcessInfo.h"
#include "AMSURLRequestProperties.h"

@class NSURLSession, NSURLSessionTask, NSURLSessionTaskMetrics;

@interface AMSMetricsLoadURLContext : NSObject {
	NSDictionary *_decodedResponseBody;
}

@property (retain, nullable) AMSBuyParams *buyParams;
@property (retain, nullable) AMSURLRequestProperties *properties;
@property (retain, nullable) id <AMSBagProtocol> bag;
@property (retain, nullable) NSError *error;
@property (retain, nullable) AMSProcessInfo *processInfo;
@property (retain, nullable) NSData *responseBody;
@property (retain, nullable) NSURLSession *session;
@property (retain, nullable) NSURLSessionTask *task;
@property (retain, nullable) NSURLSessionTaskMetrics *taskMetrics;

- (void)setBagContract:(id)contract;
- (id)bagContract;
- (nonnull instancetype)initWithTask:(id)task metrics:(id)metrics;
- (id)metricsDictionaryPromise;
- (nonnull instancetype)initWithTaskInfo:(id)info serverPayload:(id)payload;

@end
