//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@class ACAccount;

@interface AMSMetricsBatch : NSObject

@property (retain, nonatomic, nullable) ACAccount *account;
@property (nonatomic) BOOL anonymous;
@property (copy, nonatomic, nullable) NSString *canaryIdentifier;
@property (nonatomic) BOOL disableLoadURLMetrics;
@property (copy, nonatomic, nullable) NSArray *droppedEvents;
@property (copy, nonatomic, nullable) NSArray *events;
@property (retain, nonatomic, nullable) NSURL *reportURL;
@property (copy, nonatomic, nullable) NSArray *skippedEvents;
@property (copy, nonatomic, nullable) NSData *serializedEventsData;


@end
