//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSBagConsumer-Protocol.h"

@interface AMSNetworkConstraints : NSObject <AMSBagConsumer>

@property (retain, nullable) NSMutableDictionary *sizeLimits;
@property (readonly) BOOL anyNetworkTypeEnabled;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)createBagForSubProfile;
+ (id)bagSubProfileVersion;
+ (id)bagSubProfile;
+ (id)bagKeySet;
+ (id)_networkConstraintsForMediaType:(id)type withArray:(id)array;
+ (id)networkConstraintsForMediaType:(id)type withBag:(id)bag;

- (BOOL)isEqual:(nullable id)object;
- (nonnull instancetype)init;
- (long long)sizeLimitForNetworkType:(id)type;
- (void)_disableAllNetworkTypes;
- (id)_initWithStoreConstraintDictionary:(nullable NSDictionary *)dictionary;
- (void)_setSizeLimit:(long long)limit forNetworkType:(id)type;
- (long long)_sizeLimitForNetworkType:(id)type;
- (BOOL)hasSizeLimitForNetworkType:(id)type;
- (BOOL)isAnyNetworkTypeEnabled;
- (BOOL)isEqualToConstraints:(id)constraints;

@end
