//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSBagConsumer-Protocol.h"
#include "AMSBagProtocol-Protocol.h"
#include "AMSProcessInfo.h"
#include "AMSTask.h"

@class ACAccount;

@interface AMSNotificationSettingsTask : AMSTask <AMSBagConsumer>

@property (retain, nullable) ACAccount *account;
@property (retain, nullable) id <AMSBagProtocol> bag;
@property (retain, nullable) AMSProcessInfo *clientInfo;
@property (readonly) NSString *identifier;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)bagSubProfileVersion;
+ (id)bagSubProfile;
+ (id)bagKeySet;

- (id)updateSettings:(id)settings;
- (id)_url;
- (nonnull instancetype)initWithIdentifier:(id)identifier account:(id)account bag:(id)bag;
- (id)_countryCodeFromBag:(id)bag;
- (id)_generateParametersForItems:(id)items;
- (id)_stringForKey:(id)key fromBag:(id)bag;
- (id)fetchAllSettings;
- (id)fetchSettingForIdentifier:(id)identifier;
- (id)fetchSettingsForSections:(id)sections;

@end
