//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSMutablePromise.h"
#include "NWNetworkOfInterestManagerDelegate-Protocol.h"

@class NWNetworkOfInterestManager;
@protocol OS_dispatch_queue;

@interface AMSNetworkQualityInquiry : NSObject <NWNetworkOfInterestManagerDelegate> {
	NWNetworkOfInterestManager *_manager;
	dispatch_queue_t _queue;
	NSMutableSet *_knownNetworks;
	NSMutableArray *_knownNetworksReadyHandlers;
	NSArray *_lastKnownReports;
	long long _lastReportRefreshTimestamp;
	AMSMutablePromise *_currentInvestigation;
}

@property (copy, nullable) NSDictionary *lastConnectionReport;

+ (BOOL)isEntitled;
+ (id)sharedInstance;
+ (id)reportForConnectionInterface:(id)interface fromReports:(id)reports;
+ (id)lastConnectionReport;

- (void)didStopTrackingNOI:(id)noi;
- (void)performWhenKnownNetworksReady:(UnknownBlock)ready;
- (BOOL)areKnownNetworksReady;
- (void)didStopTrackingAllNOIs:(id)nois;
- (void)updateLastConnectionReportWithTask:(id)task;
- (void)drainKnownNetworksReadyHandlers;
- (void)didStartTrackingNOI:(id)noi;
- (nonnull instancetype)init;
- (id)investigateNetworks;
- (void)dealloc;

@end
