//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@interface AMSNotificationSettingsSection : NSObject

@property (readonly) NSDictionary *dictionaryRepresentation;
@property (readonly) NSString *footer;
@property (readonly) NSString *identifier;
@property (readonly) NSArray *items;
@property (readonly) NSString *title;

- (nonnull instancetype)initWithDictionaryRepresentation:(id)representation;
- (nonnull NSString *)description;
- (nonnull instancetype)initWithTitle:(id)title footer:(id)footer items:(id)items;

@end
