//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSBagProtocol-Protocol.h"
#include "AMSProcessInfo.h"

@interface AMSOpenURL : NSObject

@property (retain, nullable) NSMutableSet *attemptedTargets;
@property (readonly) NSURL *URL;
@property (retain, nullable) AMSProcessInfo *clientInfo;
@property (retain, nullable) id <AMSBagProtocol> bag;

+ (BOOL)_openURL:(nullable NSURL *)url inApp:(id)app;
+ (id)_modifiedURLFromURL:(nullable NSURL *)url bundleInfo:(id)info;
+ (unsigned long long)_openModeForStandardURL:(nullable NSURL *)url inApp:(id)app withLinks:(id)links;
+ (BOOL)_openURLWithLaunchServices:(id)services;
+ (BOOL)_shouldOpenStandardURL:(nullable NSURL *)url inApp:(id)app withLinks:(id)links;
+ (BOOL)openStandardURL:(nullable NSURL *)url;
+ (void)openURL:(nullable NSURL *)url account:(id)account preferredClient:(nullable ISStoreClient *)client;
+ (id)openURL:(nullable NSURL *)url clientInfo:(id)info bag:(id)bag;

- (BOOL)_shouldOpenURL:(nullable NSURL *)url;
- (BOOL)_openURL:(nullable NSURL *)url bundleInfo:(id)info;
- (id)_performOpen;
- (nonnull instancetype)initWithURL:(nullable NSURL *)url clientInfo:(id)info bag:(id)bag;

@end
