//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSMutableBinaryPromise.h"

@interface AMSOperation : NSOperation {
	NSLock *_lock;
	NSMutableSet *_subOperations;
	BOOL _cancelled;
}

@property (retain, nullable) AMSMutableBinaryPromise *promise;
@property (weak) AMSOperation *parentOperation;
@property BOOL success;
@property (retain, nullable) NSError *error;

- (void)run;
- (void)unlock;
- (void)lock;
- (BOOL)isCancelled;
- (void)main;
- (void)cancel;
- (nonnull instancetype)init;
- (void)runSubOperation:(id)operation;
- (void)runSubOperation:(id)operation onQueue:(id)queue;

@end
