//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@protocol OS_dispatch_queue;

@interface AMSObservable : NSObject

@property (readonly) unsigned long long behavior;
@property (retain, nullable) NSError *failureError;
@property (retain, nullable) NSString *logKey;
@property (retain, nullable) NSMutableArray *observers;
@property (retain, nullable) NSMutableArray *queuedResults;
@property (retain, nullable) dispatch_queue_t sendMessageQueue;
@property (retain, nullable) NSConditionLock *stateLock;
@property (readonly) BOOL cancelled;
@property (readonly) BOOL complete;

- (void)unsubscribe:(id)unsubscribe;
- (BOOL)_isComplete;
- (nonnull instancetype)initWithObservers:(id)observers behavior:(unsigned long long)behavior;
- (BOOL)isComplete;
- (BOOL)sendResult:(id)result;
- (nonnull instancetype)initWithObserver:(id)observer;
- (BOOL)sendCompletion;
- (BOOL)isCancelled;
- (nonnull instancetype)initWithNotification:(id)notification object:(id)object;
- (nonnull instancetype)initWithObserver:(id)observer behavior:(unsigned long long)behavior;
- (void)subscribe:(id)subscribe;
- (BOOL)sendFailure:(id)failure;
- (id)subscribeWithResultBlock:(UnknownBlock)block;
- (nonnull instancetype)initWithObservers:(id)observers;
- (BOOL)cancel;
- (nonnull instancetype)init;
- (void)unsubscribeAll;
- (nonnull instancetype)initWithObject:(id)object keyPath:(id)path options:(unsigned long long)options;

@end
