//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSBagConsumer-Protocol.h"

@interface AMSPSD2EventTask : NSObject <AMSBagConsumer>

+ (id)createBagForSubProfile;
+ (id)bagSubProfileVersion;
+ (id)bagSubProfile;
+ (void)sendCUIBootstrapEventWithURL:(nullable NSURL *)url error:(nullable NSError *)error;
+ (void)sendCUIBootstrapInitiatedEventWithURL:(nullable NSURL *)url;
+ (void)sendCUICallbackEventWithResolveData:(id)data;
+ (void)sendCUINoDelegateCallbackEventWithResolveData:(id)data className:(id)name;
+ (BOOL)sendInitialPSD2EventWithAction:(id)action bag:(id)bag originalResponse:(id)response;
+ (void)sendRetryResultPSD2EventWithAction:(id)action result:(id)result error:(nullable NSError *)error bag:(id)bag;

- (nonnull instancetype)init;

@end
