//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSPurchaseInfo.h"
#include "AMSURLRequestEncoder.h"

@protocol OS_dispatch_queue;

@interface AMSPurchaseRequestEncoder : AMSURLRequestEncoder

@property (readonly) AMSPurchaseInfo *purchaseInfo;
@property (retain, nullable) dispatch_queue_t purchaseRequestQueue;

+ (long long)_anisetteTypeFromAccount:(id)account;
+ (id)_bagURLKeysForPurchaseType:(long long)type withProductType:(id)type purchase:(id)purchase prefix:(id)prefix;
+ (id)_parametersFromPurchaseInfo:(id)info;
+ (id)configureRequest:(id)request purchaseInfo:(id)info bag:(id)bag;
+ (id)_bagURLKeysFromPurchaseInfo:(id)info;
+ (id)bagURLFromPurchaseInfo:(id)info bag:(id)bag;
+ (id)_buyProductURLKeysForProductType:(id)type prefix:(id)prefix;

- (id)encodeRequest;
- (nonnull instancetype)initWithPurchaseInfo:(id)info bag:(id)bag;
- (nonnull instancetype)initWithPurchaseInfo:(id)info;

@end
