//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "_TtC18AppleMediaServices24AMSPaymentExpandableInfo.h"

@interface AMSPaymentContentItem : NSObject <NSSecureCoding>

@property (retain, nonatomic, nullable) struct CGImage * image;
@property (copy, nonatomic, nullable) NSAttributedString *title;
@property (copy, nonatomic, nullable) NSAttributedString *label;
@property (copy, nonatomic, nullable) NSString *accessibilityIdentifier;
@property (copy, nonatomic, nullable) NSString *padding;
@property (retain, nonatomic, nullable) _TtC18AppleMediaServices24AMSPaymentExpandableInfo *expandableInfo;

+ (BOOL)supportsSecureCoding;

- (void)encodeWithCoder:(nullable NSCoder *)coder;
- (nonnull instancetype)initWithCoder:(nullable NSCoder *)coder;
- (void)dealloc;

@end
