//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSBuyParams.h"
#include "AMSProcessInfo.h"
#include "AMSPurchase.h"
#include "AMSPurchaseDelegate-Protocol.h"
#include "AMSPurchaseTask.h"

@class ACAccount, LAContext;

@interface AMSPurchaseInfo : NSObject <NSSecureCoding>

@property (retain, nullable) NSXPCListenerEndpoint *paymentViewServiceListener;
@property (retain, nullable) NSNumber *paymentMethodType;
@property (readonly) NSDictionary *objectForLogging;
@property (retain, nullable) ACAccount *account;
@property (weak) AMSPurchaseTask *activePurchaseTask;
@property (retain, nullable) NSMutableDictionary *additionalHeaders;
@property BOOL addKBSync;
@property (retain, nullable) AMSBuyParams *buyParams;
@property (readonly) NSString *clientCorrelationKey;
@property (readonly) AMSProcessInfo *clientInfo;
@property (weak) id <AMSPurchaseDelegate> delegate;
@property (retain, nullable) NSDictionary *dialog;
@property (retain, nullable) NSString *dialogId;
@property BOOL didShowPaymentSheet;
@property (retain, nullable) NSNumber *expressCheckoutMode;
@property (readonly) BOOL free;
@property BOOL hasBeenAuthedForBuy;
@property BOOL hasRetriedOriginalOwnerAccount;
@property (retain, nullable) NSNumber *hostProcessIdentifier;
@property (retain, nullable) NSDictionary *idmsTokens;
@property (retain, nullable) LAContext *localAuthContext;
@property (retain, nullable) NSURL *paymentServicesURL;
@property (retain, nullable) NSString *paymentToken;
@property (readonly) AMSPurchase *purchase;

+ (BOOL)supportsSecureCoding;

- (void)encodeWithCoder:(nullable NSCoder *)coder;
- (nonnull NSString *)description;
- (nonnull instancetype)initWithCoder:(nullable NSCoder *)coder;
- (id)_purchaseStringForType:(long long)type;
- (nonnull instancetype)initWithPurchase:(id)purchase;
- (BOOL)isFree;

@end
