//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSMappedBundleInfo.h"

@interface AMSProcessInfo : NSObject <NSCopying, NSSecureCoding> {
	struct os_unfair_lock_s { unsigned int _os_unfair_lock_opaque; } _lock;
}

@property (readonly) AMSMappedBundleInfo *mappedBundleInfo;
@property (readonly) BOOL amsAccountsDaemon;
@property (readonly) BOOL accountsDaemon;
@property (retain, nullable) NSNumber *processIdentifier;
@property (copy, nullable) UnknownBlock treatmentCanonicalAccountIdentifierProvider;
@property (retain, nullable) NSString *accountMediaType;
@property (retain, nullable) NSData *auditTokenData;
@property (retain, nullable) NSString *bundleIdentifier;
@property (retain, nullable) NSURL *bundleURL;
@property (retain, nullable) NSString *clientVersion;
@property (retain, nullable) NSString *executableName;
@property (retain, nullable) NSString *localizedName;
@property (retain, nullable) NSString *partnerHeader;
@property (retain, nullable) NSString *proxyAppBundleID;
@property (copy, nullable) NSString *treatmentNamespace;
@property (retain, nullable) NSString *userAgentSuffix;

+ (id)currentProcess;
+ (BOOL)isBuddyRunning;
+ (BOOL)supportsSecureCoding;
+ (id)valueForEntitlement:(id)entitlement;
+ (id)stringForEntitlement:(id)entitlement;
+ (BOOL)hasValue:(id)value inArrayForEntitlement:(id)entitlement;
+ (id)defaultMediaTypeForCurrentProcess;
+ (id)_bundleForIdentifier:(id)identifier record:(id)record;
+ (void)copyPropertiesFrom:(id)from to:(id)to;
+ (void)setDefaultMediaTypeForCurrentProcess:(id)process;
+ (id)_currentProcessBundleIdentifier;
+ (id)_cachedProcessInfoForIdentifier:(id)identifier;
+ (BOOL)boolForMachLookupAccess:(id)access;
+ (void)_accessProcessInfoCache:(UnknownBlock)cache;
+ (id)arrayForEntitlement:(id)entitlement;
+ (id)_bundleRecordForIdentifier:(id)identifier;
+ (void)_cacheProcessInfo:(id)info;
+ (BOOL)boolForEntitlement:(id)entitlement;
+ (BOOL)hasAMSEntitlement;

- (id)generateConfigurationFromBagContract:(id)contract;
- (BOOL)isAMSAccountsDaemon;
- (id)generateConfigurationFromBag:(id)bag;
- (id)generateConfiguration;
- (nonnull instancetype)copyWithZone:(nullable struct _NSZone *)zone;
- (BOOL)isAccountsDaemon;
- (nonnull instancetype)initWithBundleIdentifier:(id)identifier;
- (void)_setComputedPropertiesForBundleIdentifier:(id)identifier;
- (void)encodeWithCoder:(nullable NSCoder *)coder;
- (BOOL)isEqual:(nullable id)object;
- (unsigned long long)hash;
- (nonnull instancetype)init;
- (nonnull NSString *)description;
- (nonnull instancetype)initWithCoder:(nullable NSCoder *)coder;

@end
