//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSBagConsumer-Protocol.h"
#include "AMSPushParsable-Protocol.h"
#include "AMSUserNotificationIntentDelegate-Protocol.h"

@interface AMSPushParsableFollowUp : NSObject <AMSPushParsable, AMSUserNotificationIntentDelegate, AMSBagConsumer>

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)createBagForSubProfile;
+ (id)bagSubProfileVersion;
+ (id)bagSubProfile;
+ (id)_createFollowUpItemFromPayload:(id)payload;
+ (id)_createFollowUpItemFromNotification:(id)notification;
+ (id)_createNotificationFromFollowUpItem:(id)item;
+ (id)_dateFromString:(id)string;
+ (void)_performClearWithPayload:(id)payload;
+ (void)_performPostWithPayload:(id)payload bag:(id)bag;
+ (BOOL)_shouldAllowFollowUp:(id)up bag:(id)bag;
+ (BOOL)_shouldClearFollowUpFromPayload:(id)payload;
+ (void)handleNotificationPayload:(id)payload config:(id)config bag:(id)bag;
+ (BOOL)isDeviceOfferNotification:(id)notification;
+ (void)removeDeviceOfferWithPayload:(id)payload logKey:(id)key bag:(id)bag;
+ (BOOL)shouldSkipAccountCheck;
+ (void)userNotification:(id)notification selectedButtonAction:(id)action bag:(id)bag;

@end
