//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@protocol AMSPushHandlerDelegate;

@interface AMSPushConfiguration : NSObject

@property (weak) id <AMSPushHandlerDelegate> delegate;
@property (retain, nullable) NSString *engagementPushTopic;
@property (retain, nullable) NSString *userNotificationExtensionId;
@property (retain, nullable) NSSet *enabledActionTypes;

- (nonnull instancetype)initWithEnabledActionTypes:(id)types;

@end
