//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSPushParsable-Protocol.h"

@interface AMSPushParsableEngagementEvent : NSObject <AMSPushParsable>

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)_eventForMapiPayload:(id)payload account:(id)account bag:(id)bag;
+ (id)_eventForStaticAssetPayload:(id)payload bag:(id)bag;
+ (void)_waitForPromises:(id)promises completion:(UnknownBlock)completion;
+ (void)handleNotificationPayload:(id)payload config:(id)config bag:(id)bag;
+ (BOOL)shouldSkipAccountCheck;

@end
