//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSAuthenticateTaskDelegate-Protocol.h"
#include "AMSBagConsumer-Protocol.h"
#include "AMSBagProtocol-Protocol.h"
#include "AMSPurchaseDelegate-Protocol.h"
#include "AMSPurchaseInfo.h"
#include "AMSPurchaseRequestEncoder.h"
#include "AMSTask.h"
#include "AMSURLProtocolDelegate-Protocol.h"
#include "AMSURLSession.h"

@interface AMSPurchaseTask : AMSTask <NSURLSessionDelegate, AMSURLProtocolDelegate, AMSAuthenticateTaskDelegate, AMSBagConsumer>

@property (readonly) AMSPurchaseInfo *purchaseInfo;
@property (retain, nullable) AMSPurchaseRequestEncoder *purchaseRequestEncoder;
@property (retain, nullable) id <AMSBagProtocol> bag;
@property (retain, nullable) AMSPurchaseInfo *purchaseInfo;
@property (retain, nullable) AMSPurchaseRequestEncoder *purchaseRequestEncoder;
@property (readonly) AMSURLSession *session;
@property (weak) id <AMSPurchaseDelegate> delegate;
@property (retain, nullable) Class paymentSheetTaskClass;
@property (retain, nullable) NSNumber *hostProcessIdentifier;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)createBagForSubProfile;
+ (id)bagSubProfileVersion;
+ (id)bagSubProfile;
+ (id)bagKeySet;
+ (void)_captureBugReportForPurchaseEventEnqueueFailure:(id)failure process:(id)process;
+ (id)_filterResponseDictionary:(nullable NSDictionary *)dictionary bag:(id)bag;
+ (id)_filterResponseDictionary:(nullable NSDictionary *)dictionary keyPaths:(id)paths;
+ (id)engagementEventWithInfo:(id)info bag:(id)bag responseDictionary:(nullable NSDictionary *)dictionary error:(nullable NSError *)error;
+ (BOOL)shouldPreauthenticatePurchaseWithInfo:(id)info;

- (id)performPurchase;
- (id)_buySignatureJSONWithFinalizedBlindedItems:(id)items;
- (id)_decorateBuyParamsWithCohortParams;
- (id)_determineIfShouldAttachPaymentServicesURL:(nullable NSURL *)url;
- (id)_determineIfShouldSendBlindedData;
- (id)_finalizeBlindingWithPurchaseInfo:(id)info responseDictionary:(nullable NSDictionary *)dictionary purchaseResult:(id)result outError:(id *)error;
- (id)_generateBlindedSignature;
- (id)_promptForAccount;
- (id)_recordEngagementEventWithInfo:(id)info responseDictionary:(nullable NSDictionary *)dictionary finalizedBlindedItems:(id)items error:(nullable NSError *)error;
- (id)_runAuthenticateRequest:(id)request;
- (id)_runDialogRequest:(id)request;
- (void)_saveBlindedData;
- (BOOL)_shouldAttemptCardEnrollment;
- (id)_shouldFinalizeBlindedDataWithResponseDictionary:(nullable NSDictionary *)dictionary;
- (BOOL)_shouldGenerateAFDSWithPurchaseInfo:(id)info;
- (void)authenticateTask:(id)task handleDialogRequest:(id)request completion:(UnknownBlock)completion;
- (void)generateFDSWithInfo:(id)info bag:(id)bag;
- (nonnull instancetype)initWithPurchase:(id)purchase bag:(id)bag;
- (id)performPreActionRequestForTaskInfo:(id)info requiresAuthorization:(BOOL)authorization;
- (id)performPreauthenticate;
- (id)performPurchaseRequest;
- (id)preauthenticateOptions;

@end
