//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSPromiseCompletionBlocks.h"
#include "AMSPromiseResult.h"

@interface AMSPromise : NSObject {
	struct os_unfair_lock_s { unsigned int _os_unfair_lock_opaque; } _stateLock;
}

@property (readonly, nonatomic) AMSPromiseCompletionBlocks *completionBlocks;
@property (retain, nonatomic, nullable) AMSPromise *retainedSelf;
@property (readonly, nonatomic) NSCondition *condition;
@property (nonatomic) BOOL conditionHasSignaled;
@property (retain, nonatomic, nullable) AMSPromiseResult *promiseResult;
@property (readonly, nonatomic) BOOL isFinishedWithLock;
@property (readonly) BOOL cancelled;
@property (readonly) BOOL finished;
@property (readonly) BOOL timedOut;

+ (id)promiseWithErrorCode:(long long)code title:(id)title message:(id)message;
+ (id)promiseWithAll:(id)all timeout:(double)timeout;
+ (id)unwrappedPromiseWithPromise:(id)promise;
+ (BOOL)_errorIsCanceledError:(nullable NSError *)error;
+ (id)promiseWithAny:(id)any;
+ (BOOL)_errorIsTimeOutError:(nullable NSError *)error;
+ (id)promiseWithAny:(id)any timeout:(double)timeout;
+ (id)promiseWithSome:(id)some timeout:(double)timeout;
+ (id)promiseFinishedWithDefaultErrorOrResult:(id)result;
+ (id)promiseWithResult:(id)result;
+ (void)_enumeratePromises:(id)promises startingAt:(long long)at block:(UnknownBlock)block;
+ (id)promiseWithPromiseResult:(id)result;
+ (id)promiseWithSome:(id)some;
+ (id)promiseWithErrorCode:(long long)code title:(id)title message:(id)message underlyingError:(nullable NSError *)error;
+ (id)promiseWithAll:(id)all;
+ (id)promiseWithFlattenedPromises:(id)promises;
+ (void)_configureFlattenedPromise:(id)promise withPromises:(id)promises results:(id)results previousError:(nullable NSError *)error currentPromiseIndex:(unsigned long long)index;
+ (id)promiseWithError:(nullable NSError *)error;

- (void)addFinishBlock:(UnknownBlock)block;
- (void)addBlock:(UnknownBlock)block orCallWithResult:(UnknownBlock)result;
- (BOOL)finishWithResult:(id)result;
- (id)resultWithError:(id *)error;
- (void)addErrorBlock:(UnknownBlock)block;
- (void)addSuccessBlock:(UnknownBlock)block;
- (void)waitUntilFinishedWithTimeout:(double)timeout;
- (id)resultBeforeDate:(id)date error:(id *)error;
- (BOOL)isCancelled;
- (id)resultWithTimeout:(double)timeout error:(id *)error;
- (UnknownBlock)errorOnlyCompletionHandlerAdapter;
- (BOOL)finishWithResult:(id)result error:(nullable NSError *)error;
- (void)waitUntilFinished;
- (void)resultWithCompletion:(UnknownBlock)completion;
- (BOOL)isFinished;
- (UnknownBlock)completionHandlerAdapter;
- (nonnull instancetype)initWithPromiseResult:(id)result;
- (id)catchWithBlock:(UnknownBlock)block;
- (BOOL)cancel;
- (id)continueWithBinaryPromiseBlock:(UnknownBlock)block;
- (BOOL)finishWithError:(nullable NSError *)error;
- (id)continueWithBlock:(UnknownBlock)block;
- (nonnull instancetype)initWithTimeout:(double)timeout;
- (BOOL)finishWithPromiseResult:(id)result;
- (void)resultWithTimeout:(double)timeout completion:(UnknownBlock)completion;
- (void)stopRetainingSelf;
- (id)valueFromAddingBlock:(UnknownBlock)block orCallWithResult:(UnknownBlock)result;
- (nonnull instancetype)init;
- (id)catchWithBinaryPromiseBlock:(UnknownBlock)block;
- (BOOL)finishWithPromise:(id)promise;
- (id)thenWithBlock:(UnknownBlock)block;
- (id)thenWithBinaryPromiseBlock:(UnknownBlock)block;
- (id)promiseWithTimeout:(double)timeout;
- (id)binaryPromiseAdapter;
- (id)binaryPromiseAdapterForClass:(Class)_class;
- (UnknownBlock)boolCompletionHandlerAdapter;
- (void)flushCompletionBlocksWithResult:(id)result;
- (BOOL)isTimedOut;
- (id)mutablePromiseAdapter;
- (UnknownBlock)nilValueCompletionHandlerAdapter;
- (void)resultBeforeDate:(id)date completion:(UnknownBlock)completion;

@end
