//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSBiometricsSignatureRequest.h"
#include "AMSCardSingleSelection.h"
#include "AMSDelegatePurchaseRequest.h"
#include "AMSPaymentSheetPerformanceMetrics.h"

@class ACAccount;

@interface AMSPaymentSheetRequest : NSObject <NSSecureCoding>

@property (readonly) unsigned long long ams_confirmationStyle;
@property BOOL isDelegateAuthentication;
@property (retain, nullable) AMSPaymentSheetPerformanceMetrics *performanceMetrics;
@property (copy, nullable) NSDictionary *responseDictionary;
@property (retain, nullable) AMSDelegatePurchaseRequest *delegatePurchaseRequest;
@property (readonly) NSDictionary *objectForLogging;
@property BOOL isDelegateAuthentication;
@property (retain, nullable) AMSPaymentSheetPerformanceMetrics *performanceMetrics;
@property (copy, nullable) NSDictionary *responseDictionary;
@property (retain, nullable) AMSDelegatePurchaseRequest *delegatePurchaseRequest;
@property (copy, nullable) ACAccount *account;
@property (copy, nullable) NSString *accountHeader;
@property BOOL applePayClassic;
@property (copy, nullable) NSArray *attributedList;
@property (retain, nullable) AMSBiometricsSignatureRequest *biometricsRequest;
@property long long confirmationTitle;
@property (copy, nullable) NSString *countryCode;
@property (copy, nullable) NSString *currencyCode;
@property (copy, nullable) NSString *delegateAuthenticateChallenge;
@property (copy, nullable) NSNumber *designVersion;
@property (copy, nullable) NSString *displayPrice;
@property (copy, nullable) NSString *explanation;
@property (copy, nullable) NSArray *flexList;
@property (retain, nullable) NSArray *inlineImages;
@property (retain, nullable) NSString *logKey;
@property (copy, nullable) NSDictionary *merchantSession;
@property (copy, nullable) NSString *message;
@property long long payee;
@property (copy, nullable) NSString *paymentSession;
@property (copy, nullable) NSString *paymentSummary;
@property (copy, nullable) NSArray *preSheetDialog;
@property (copy, nullable) NSNumber *price;
@property (copy, nullable) NSArray *priceSectionItems;
@property (copy, nullable) NSString *ratingHeader;
@property (copy, nullable) NSString *ratingValue;
@property BOOL requiresAuthorization;
@property (readonly) BOOL requiresDelegateAuthentication;
@property long long salableIcon;
@property (copy, nullable) NSURL *salableIconURL;
@property (copy, nullable) NSArray *salableInfo;
@property (copy, nullable) NSAttributedString *salableInfoLabel;
@property (copy, nullable) NSArray *secondaryFlexList;
@property long long secondarySalableIcon;
@property (copy, nullable) NSURL *secondarySalableIconURL;
@property (copy, nullable) NSArray *secondarySalableInfo;
@property (copy, nullable) NSAttributedString *secondarySalableInfoLabel;
@property (retain, nullable) AMSCardSingleSelection *selectedCard;
@property BOOL shouldUppercaseText;
@property (copy, nullable) NSString *storeName;
@property (copy, nullable) NSArray *styles;
@property (copy, nullable) NSString *title;
@property long long titleType;
@property (copy, nullable) NSString *userAgent;
@property (copy, nullable) NSString *authorizingTitle;
@property BOOL disablePasscodeFallback;
@property BOOL disablePasswordFallback;
@property BOOL drawBackground;
@property BOOL drawBottomDivider;

+ (BOOL)supportsSecureCoding;
+ (void)_sendAutoBugCaptureReportWithError:(nullable NSError *)error subtypeContext:(id)context;
+ (id)attributedStringByRemovingPlaceholderTagsFromAttributedString:(id)string;
+ (long long)imageTypeForURLResult:(nullable NSURL *)urlresult;
+ (id)paymentSheetRequestFromDictionary:(nullable NSDictionary *)dictionary account:(id)account;

- (void)encodeWithCoder:(nullable NSCoder *)coder;
- (nonnull instancetype)init;
- (nonnull instancetype)initWithCoder:(nullable NSCoder *)coder;
- (struct CGImage *)_createImageRefForImageRef:(struct CGImage *)ref withAdornmentStyle:(long long)style andDesignVersion:(id)version;
- (id)ams_createContentItemForAccount;
- (id)_amsContentItemsForFlexibleList:(id)list assetCache:(id)cache designVersion:(id)version bag:(id)bag error:(id *)error;
- (id)_attachInlineImagesToAttributedString:(id)string designVersion:(id)version bag:(id)bag;
- (id)_attachLeadingItem:(id)item attributedString:(id)string designVersion:(id)version;
- (id)_contentItemsForFlexibleList:(id)list assetCache:(id)cache designVersion:(id)version bag:(id)bag error:(id *)error;
- (struct CGPath *)_createBorderPathForAdornmentStyle:(long long)style iconWidth:(double)width iconHeight:(double)height;
- (struct CGImage *)_createDefaultImageWithImageRef:(struct CGImage *)ref size:(struct CGSize { double x0; double x1; })size borderPath:(struct CGPath *)path;
- (struct CGImage *)_createImageForAssetConfiguration:(id)configuration outAssetScale:(float *)scale;
- (struct CGImage *)_createImageMaskRefWithSize:(struct CGSize { double x0; double x1; })size andPath:(struct CGPath *)path;
- (struct CGImage *)_createImageRefForAssetURL:(nullable NSURL *)url size:(struct CGSize { double x0; double x1; })size assetType:(long long)type outAssetScale:(float *)scale;
- (struct CGImage *)_createImageRefForImageSource:(struct CGImageSource *)source screenScale:(float)scale outAssetScale:(float *)scale;
- (struct CGImage *)_createImageRefForImageURL:(nullable NSURL *)url outAssetScale:(float *)scale;
- (struct CGImage *)_createImageRefForPDFURL:(id)pdfurl size:(struct CGSize { double x0; double x1; })size outAssetScale:(float *)scale;
- (struct CGImage *)_createImageRefWithURL:(nullable NSURL *)url designVersion:(id)version adornmentStyle:(long long)style bag:(id)bag;
- (struct CGImage *)_createMaskedImageRefForImageRef:(struct CGImage *)ref withPathRef:(struct CGPath *)ref adornmentStyle:(long long)style andDesignVersion:(id)version;
- (struct CGImage *)_createRGBImageRefForGreyScaleImageRef:(struct CGImage *)ref width:(unsigned long long)width height:(unsigned long long)height;
- (struct CGImage *)_createRatingImageWithStringValue:(id)value assetScale:(float *)scale;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })_rectWithAspectRatio:(struct CGSize { double x0; double x1; })ratio insideRect:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })rect;
- (id)_replaceImagePlaceholderTag:(id)tag withAttributes:(id)attributes foregroundColor:(long long)color forAttributedString:(id)string;
- (id)_replaceImagePlaceholderTag:(id)tag withImageData:(id)data scale:(float)scale tint:(BOOL)tint forAttributedString:(id)string;
- (BOOL)_shouldDrawGrayBorderForMaskedImageWithDesignVersion:(id)version;
- (id)_summaryItemsForAttributedList:(id)list assetCache:(id)cache bag:(id)bag;
- (id)ams_amsContentItemForSalableInfoLabel:(id)label salableIconURL:(nullable NSURL *)url salableIcon:(long long)icon assetCache:(id)cache designVersion:(id)version bag:(id)bag;
- (id)ams_contentItemForSalableInfoLabel:(id)label salableIconURL:(nullable NSURL *)url salableIcon:(long long)icon assetCache:(id)cache designVersion:(id)version bag:(id)bag;
- (id)ams_createAMSContentItem:(id)item label:(id)label image:(struct CGImage *)image accessibilityIdentifier:(id)identifier padding:(id)padding;
- (id)ams_createAMSContentItemForRating;
- (id)ams_createAMSContentItemForSalableInfoWithAssetCache:(id)cache designVersion:(id)version bag:(id)bag;
- (id)ams_createAMSContentItemsForFlexibleListWithAssetCache:(id)cache designVersion:(id)version bag:(id)bag error:(id *)error;
- (id)ams_createAMSContentItemsForPreScreenDialogWithAssetCache:(id)cache designVersion:(id)version bag:(id)bag;
- (id)ams_createAMSExpandableInfo:(id)info info:(id)info bag:(id)bag error:(id *)error;
- (id)ams_createContentFromData:(id)data keys:(id)keys error:(id *)error;
- (id)ams_createContentItemForDeviceName:(id)name;
- (id)ams_createContentItemForRating;
- (id)ams_createContentItemForSalableInfoFromAMSContentItem:(id)item;
- (id)ams_createContentItemForSalableInfoWithAssetCache:(id)cache designVersion:(id)version bag:(id)bag;
- (id)ams_createContentItemsForFlexibleListWithAssetCache:(id)cache designVersion:(id)version bag:(id)bag error:(id *)error;
- (id)ams_createContentItemsForPreScreenDialogWithAssetCache:(id)cache designVersion:(id)version bag:(id)bag;
- (id)ams_createSecondaryContentItemForSalableInfoWithAssetCache:(id)cache designVersion:(id)version bag:(id)bag;
- (id)ams_createSecondaryContentItemsForFlexibleListWithAssetCache:(id)cache designVersion:(id)version bag:(id)bag;
- (id)ams_createSummaryItems;
- (id)ams_createSummaryItemsForAttributedListWithAssetCache:(id)cache bag:(id)bag;
- (unsigned long long)ams_paymentRequestorType;
- (BOOL)isApplePayClassic;
- (BOOL)isDesignVersionEqual:(id)equal;
- (BOOL)isDesignVersionEqualOrGreaterThan:(id)than;
- (BOOL)isDesignVersionLessThan:(id)than;

@end
