//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSBagProtocol-Protocol.h"
#include "AMSBinaryPromise.h"
#include "AMSFinancePaymentSheetResponse.h"
#include "AMSMutablePromise.h"
#include "AMSPaymentSheetAssetCache.h"
#include "AMSPaymentSheetRequest.h"
#include "AMSPurchaseInfo.h"
#include "AMSTask.h"
#include "PKPaymentAuthorizationControllerDelegate-Protocol.h"
#include "PKPaymentAuthorizationControllerPrivateDelegate-Protocol.h"
#include "_PaymentSheetState.h"

@class AKAppleIDAuthenticationContext, PKPaymentAuthorizationController;

@interface AMSPaymentSheetTask : AMSTask <PKPaymentAuthorizationControllerDelegate, PKPaymentAuthorizationControllerPrivateDelegate>

@property (retain, nullable) AMSPaymentSheetAssetCache *assetCache;
@property (retain, nonatomic, nullable) AKAppleIDAuthenticationContext *authenticationContext;
@property (retain, nullable) PKPaymentAuthorizationController *paymentAuthorizationController;
@property (retain, nullable) AMSMutablePromise *paymentSheetPromise;
@property (readonly) AMSFinancePaymentSheetResponse *paymentSheetResponse;
@property (readonly) AMSPaymentSheetRequest *request;
@property (retain, nullable) _PaymentSheetState *state;
@property (retain, nullable) NSMutableArray *userActions;
@property (retain, nullable) AMSBinaryPromise *initialBiometricsAvailability;
@property (retain, nullable) id <AMSBagProtocol> bag;
@property (retain, nullable) NSDictionary *metricsDictionary;
@property (copy, nullable) NSString *presentingSceneBundleIdentifier;
@property (copy, nullable) NSString *presentingSceneIdentifier;
@property (retain, nullable) id presentingWindow;
@property (retain, nullable) AMSPurchaseInfo *purchaseInfo;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (BOOL)_shouldCompanionAuthFallbackToPasswordForError:(nullable NSError *)error;

- (nonnull instancetype)initWithRequest:(id)request bag:(id)bag;
- (BOOL)cancel;
- (id)perform;
- (id)_authorizePaymentWithAuthKitResults:(id)results;
- (id)_authorizePaymentWithBiometricsRequest:(id)request payment:(id)payment;
- (id)_buildPaymentRequest;
- (void)_configureAttachSelectedCard:(id)card;
- (void)_configureBasicsForPaymentRequest:(id)request amsPaymentRequest:(id)request;
- (void)_configureConfirmationScreenForPaymentRequest:(id)request amsPaymentRequest:(id)request;
- (void)_configureContentItemsForPaymentRequest:(id)request amsPaymentRequest:(id)request error:(id *)error;
- (void)_configureCustomUIForPaymentRequest:(id)request amsPaymentRequest:(id)request;
- (void)_configureLanguage:(id)language completion:(UnknownBlock)completion;
- (void)_configureMerchantSessionForPaymentRequest:(id)request;
- (void)_configurePSD2Decoration:(id)decoration completion:(UnknownBlock)completion;
- (void)_configurePaymentSummaryForPaymentRequest:(id)request;
- (void)_configureWatchDelegateAuthContentItemsForPaymentRequest:(id)request;
- (void)_didDismissPaymentAuthorizationController:(id)controller;
- (void)_dismissPaymentAuthorizationController:(id)controller;
- (id)_metricsEvent;
- (id)_performInProcessTask;
- (id)_performRemoteTask;
- (void)_presentCompanionAuthenticationSheetWithPaymentRequest:(id)request purchaseResult:(id)result;
- (void)_presentPaymentConfirmationWithPaymentRequest:(id)request purchaseResult:(id)result;
- (id)_presentPaymentSheetWithPaymentRequest:(id)request;
- (void)paymentAuthorizationController:(id)controller didAuthorizePayment:(id)payment handler:(UnknownBlock)handler;
- (void)paymentAuthorizationController:(id)controller didEncounterAuthorizationEvent:(unsigned long long)event;
- (void)paymentAuthorizationController:(id)controller didSelectPaymentMethod:(id)method handler:(UnknownBlock)handler;
- (void)paymentAuthorizationController:(id)controller willFinishWithError:(nullable NSError *)error;
- (void)paymentAuthorizationControllerDidFinish:(id)finish;
- (id)presentationSceneBundleIdentifierForPaymentAuthorizationController:(id)controller;
- (id)presentationSceneIdentifierForPaymentAuthorizationController:(id)controller;
- (id)presentationWindowForPaymentAuthorizationController:(id)controller;

@end
