//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@interface AMSPromiseCompletionBlocks : NSObject {
	struct os_unfair_lock_s { unsigned int _os_unfair_lock_opaque; } _completionBlockLock;
	NSMutableArray *_completionBlocks;
	BOOL _shouldCallImmediately;
}

- (void)addErrorBlock:(UnknownBlock)block;
- (void)addSuccessBlock:(UnknownBlock)block;
- (void)addCompletionBlock:(UnknownBlock)block;
- (void)callSuccessBlock:(UnknownBlock)block withPromiseResult:(id)result;
- (void)callCompletionBlock:(UnknownBlock)block withPromiseResult:(id)result;
- (void)callErrorBlock:(UnknownBlock)block withPromiseResult:(id)result;
- (nonnull instancetype)init;
- (void)flushCompletionBlocksWithPromiseResult:(id)result;

@end
