//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSBuyParams.h"
#include "AMSProcessInfo.h"

@class ACAccount;

@interface AMSPurchase : NSObject <NSCopying, NSSecureCoding>

@property (copy, nullable) NSString *URLBagKey;
@property (retain, nullable) NSDictionary *blindedData;
@property (retain, nullable) NSMutableArray *metricsActivities;
@property (retain, nullable) ACAccount *account;
@property (copy, nullable) NSDictionary *additionalHeaders;
@property unsigned long long ageRatingValue;
@property (readonly, copy) AMSBuyParams *buyParams;
@property (retain, nullable) NSArray *buySignatureTypes;
@property (readonly, copy) NSString *clientCorrelationKey;
@property (copy, nullable) AMSProcessInfo *clientInfo;
@property (copy, nullable) NSString *forceAskToBuyReason;
@property BOOL ignoreRequirePasswordRestriction;
@property BOOL isExceptionRequest;
@property (copy, nullable) NSString *logUUID;
@property (copy, nullable) NSNumber *ownerAccountId;
@property (copy, nullable) NSDictionary *metricsOverlay;
@property (retain, nullable) NSXPCListenerEndpoint *paymentViewServiceListener;
@property (copy, nullable) NSDictionary *performanceMetricsOverlay;
@property (copy, nullable) NSString *presentingSceneBundleIdentifier;
@property (copy, nullable) NSString *presentingSceneIdentifier;
@property (copy, nullable) NSDictionary *publicInputComponents;
@property (readonly) long long purchaseType;
@property (readonly) BOOL redownload;
@property BOOL requiresAccount;
@property BOOL requiresApplePayClassic;
@property (nonatomic) BOOL sendBlindedData;
@property (copy, nullable) NSString *storefront;
@property (readonly) NSNumber *uniqueIdentifier;
@property BOOL userInitiated;
@property BOOL useJSONContentType;
@property BOOL asyncRecordEngagementEvent;
@property (copy, nullable) NSString *callerBundleId;
@property (copy, nullable) NSString *clientId;

+ (BOOL)supportsSecureCoding;
+ (id)_authContextTitleForConfirmationStyle:(unsigned long long)style;
+ (id)defaultAuthenticationContextForRequest:(id)request;
+ (id)purchaseFromPurchase:(id)purchase;

- (nonnull instancetype)copyWithZone:(nullable struct _NSZone *)zone;
- (id)_generateIdentifier;
- (void)encodeWithCoder:(nullable NSCoder *)coder;
- (BOOL)isEqual:(nullable id)object;
- (unsigned long long)hash;
- (nonnull NSString *)description;
- (nonnull instancetype)initWithCoder:(nullable NSCoder *)coder;
- (BOOL)isUserInitiated;
- (nonnull instancetype)initWithPurchaseType:(long long)type buyParams:(id)params;
- (long long)activityLabel;
- (id)authenticationContextForRequest:(id)request;
- (BOOL)isEqualToPurchase:(id)purchase;
- (BOOL)isRedownload;

@end
