//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@class ACAccount, ACAccountType;
@protocol OS_dispatch_queue;

@interface AMSPushPayload : NSObject {
	dispatch_queue_t _internalQueue;
}

@property (readonly) ACAccount *account;
@property (readonly) NSNumber *accountIdentifier;
@property (readonly) ACAccountType *accountType;
@property (readonly) NSString *actionType;
@property (readonly) long long alertType;
@property (readonly) NSDictionary *aps;
@property (readonly) NSString *clientIdentifier;
@property (readonly) BOOL isAccountTypeActive;
@property (readonly) NSString *logKey;
@property (retain, nullable) NSDictionary *metricsOverlay;
@property (readonly) NSDictionary *payload;
@property (readonly) long long priority;
@property (readonly) NSString *URLString;
@property (readonly) NSDictionary *flags;
@property (readonly) ACAccount *iCloudAccount;

+ (id)actionTypeFromPayload:(id)payload;

- (nonnull instancetype)initWithPayload:(id)payload;
- (id)objectForKeyedSubscript:(id)subscript;

@end
