//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@protocol AMSPurchaseServiceInterface <NSObject>

@required

- (void)cacheFDS:(id)fds forPurchaseIdentifier:(id)identifier logKey:(id)key completion:(UnknownBlock)completion;
- (void)cachedFDSForPurchaseIdentifier:(id)identifier logKey:(id)key completion:(UnknownBlock)completion;
- (void)createODISessionWithSessionIdentifier:(id)identifier cacheIdentifier:(id)identifier accountType:(unsigned long long)type bundleIdentifier:(id)identifier completion:(UnknownBlock)completion;
- (void)didConsumeFDSForPurchaseIdentifier:(id)identifier logKey:(id)key completion:(UnknownBlock)completion;
- (void)generateFDSWithRequest:(id)request completion:(UnknownBlock)completion;
- (void)getODIAssessmentForCacheIdentifier:(id)identifier clearCache:(BOOL)cache completion:(UnknownBlock)completion;
- (void)partialFDSAssessmentForRequest:(id)request completion:(UnknownBlock)completion;
- (void)provideFeedbackOnPayloadOutcome:(unsigned long long)outcome cacheIdentifier:(id)identifier clearCache:(BOOL)cache completion:(UnknownBlock)completion;
- (void)updateODIWithAttributes:(id)attributes forCacheIdentifier:(id)identifier completion:(UnknownBlock)completion;

@optional

@end
