//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSPurchaseSIWA.h"
#include "AMSPurchaseTask.h"

@class AKAuthorization, AKCredentialRequestContext;

@interface AMSPurchaseSIWATask : AMSPurchaseTask

@property (retain, nonatomic, nullable) AMSPurchaseSIWA *purchaseSIWA;
@property (retain, nonatomic, nullable) AKCredentialRequestContext *requestContext;
@property (copy, nonatomic, nullable) NSUUID *continuationRequestIdentifier;
@property (copy, nonatomic, nullable) NSError *siwaError;
@property (nonatomic) BOOL purchaseRequiresAuthorization;
@property (retain, nonatomic, nullable) AKAuthorization *authorization;

- (id)_cancelAuthorization;
- (BOOL)_beginAuthorizationWasPerformed;
- (id)_beginAuthorization;
- (id)_continueAuthorization;
- (BOOL)_siwaDidCommence;
- (void)_updateRequestContextWithPurchaseInfo:(id)info;
- (BOOL)_willRequireAskToBuyForTaskInfo:(id)info;
- (nonnull instancetype)initWithPurchaseSIWA:(id)siwa bag:(id)bag;
- (id)newAuthorizationController;
- (id)performPreActionRequestForTaskInfo:(id)info requiresAuthorization:(BOOL)authorization;
- (id)performPreauthenticate;
- (id)performPurchaseSIWA;
- (id)preauthenticateOptions;

@end
