//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSBagProtocol-Protocol.h"

@protocol AMSPurchaseResponseProtocol;

@interface AMSPurchaseQueueConfiguration : NSObject

@property (readonly) id <AMSBagProtocol> bag;
@property (retain, nullable) id <AMSPurchaseResponseProtocol> delegate;
@property (retain, nullable) Class purchaseTaskClass;

- (nonnull instancetype)initWithBag:(id)bag;

@end
