//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSPurchaseResult.h"
#include "AMSPurchaseSIWAAuthorizationResult.h"

@interface AMSPurchaseSIWAResult : NSObject <NSCopying, NSSecureCoding>

@property (readonly) AMSPurchaseResult *purchaseResult;
@property (readonly) AMSPurchaseSIWAAuthorizationResult *authorizationResult;

+ (BOOL)supportsSecureCoding;

- (nonnull instancetype)copyWithZone:(nullable struct _NSZone *)zone;
- (void)encodeWithCoder:(nullable NSCoder *)coder;
- (BOOL)isEqual:(nullable id)object;
- (unsigned long long)hash;
- (nonnull instancetype)initWithCoder:(nullable NSCoder *)coder;
- (nonnull instancetype)initWithPurchaseResult:(id)result authorizationResult:(id)result;
- (BOOL)isEqualToPurchaseSIWAResult:(id)siwaresult;

@end
