//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSBagProtocol-Protocol.h"
#include "AMSPushConfiguration.h"

@protocol AMSPushHandlerContract, AMSPushHandlerDelegate;

@interface AMSPushHandler : NSObject

@property (readonly) NSDictionary *enabledParsables;
@property (readonly) id <AMSPushHandlerContract> bagContract;
@property (readonly) id <AMSBagProtocol> bag;
@property (weak) id <AMSPushHandlerDelegate> delegate;
@property (readonly) AMSPushConfiguration *configuration;

+ (id)accountIsEligibleForPushNotifications:(id)notifications accountStore:(id)store;

- (void)_handlePushNotification:(id)notification;
- (void)handleNotification:(id)notification;
- (nonnull instancetype)initWithConfiguration:(id)configuration bagContract:(id)contract;
- (nonnull instancetype)initWithConfiguration:(id)configuration bag:(id)bag;
- (BOOL)_validatePayloadFlags:(id)flags;
- (BOOL)shouldHandleNotification:(id)notification;
- (BOOL)_passesiCloudTermsVerification:(id)verification;
- (void)dealloc;
- (void)registerForEngagementPushes;

@end
