//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSMutableLazyPromise.h"

@interface AMSPurchaseBatch : NSObject

@property (retain, nullable) NSLock *lock;
@property (readonly) NSMutableArray *returnedPurchaseIDs;
@property BOOL isComplete;
@property (readonly) AMSMutableLazyPromise *promise;
@property (readonly) NSMutableArray *purchases;
@property (readonly) NSMutableDictionary *purchaseMap;
@property (readonly) NSMutableArray *results;

- (BOOL)finishPurchase:(id)purchase withError:(nullable NSError *)error;
- (BOOL)finishPurchase:(id)purchase withResult:(id)result;
- (nonnull instancetype)initWithPurchases:(id)purchases weakPromise:(id)promise;
- (id)nextPurchase;
- (id)purchaseForPurchaseId:(id)id;

@end
