//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSPurchase.h"

@class NSURLResponse;

@interface AMSPurchaseResult : NSObject <NSCopying, NSSecureCoding>

@property (copy, nullable) NSString *correlationID;
@property (copy, nullable) NSError *error;
@property (copy, nullable) NSDictionary *loadURLEventDictionary;
@property (copy, nullable) AMSPurchase *purchase;
@property (copy, nullable) NSDictionary *responseDictionary;
@property (copy, nullable) NSURLResponse *URLResponse;
@property (retain, nullable) NSDictionary *finalizedBlindedData;
@property BOOL didShowPaymentSheet;

+ (BOOL)supportsSecureCoding;

- (nonnull instancetype)copyWithZone:(nullable struct _NSZone *)zone;
- (void)encodeWithCoder:(nullable NSCoder *)coder;
- (BOOL)isEqual:(nullable id)object;
- (unsigned long long)hash;
- (nonnull instancetype)initWithCoder:(nullable NSCoder *)coder;
- (BOOL)isEqualToPurchaseResult:(id)result;

@end
