//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSPaymentSheetAssetConfiguration-Protocol.h"

@interface AMSPaymentSheetInlineImage : NSObject <NSCopying, NSSecureCoding>

@property (readonly) id <AMSPaymentSheetAssetConfiguration> localAssetConfiguration;
@property (readonly, nonatomic) long long imageType;
@property (readonly, nonatomic) BOOL serverSupplied;
@property (readonly, copy) NSString *region;
@property (readonly, nonatomic) BOOL tint;
@property (readonly, copy) NSString *URLString;
@property (readonly, copy) NSString *value;

+ (BOOL)supportsSecureCoding;
+ (id)textEncapsulationForServerValue:(id)value;

- (nonnull instancetype)initWithDictionary:(nullable NSDictionary *)dictionary;
- (nonnull instancetype)copyWithZone:(nullable struct _NSZone *)zone;
- (void)encodeWithCoder:(nullable NSCoder *)coder;
- (nonnull instancetype)initWithCoder:(nullable NSCoder *)coder;
- (nonnull instancetype)initWithURLString:(nullable NSURL *)urlstring;
- (long long)_defaultAssetType;
- (id)_imageAssetConfigurationForDictionary:(nullable NSDictionary *)dictionary;
- (long long)_ratingTypeForType:(id)type;
- (long long)_scaleForString:(id)string;
- (id)_symbolAssetConfigurationForDictionary:(nullable NSDictionary *)dictionary;
- (BOOL)isServerSupplied;

@end
