//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSBagConsumer-Protocol.h"
#include "AMSBagProtocol-Protocol.h"
#include "AMSTask.h"

@interface AMSRatingsStorefrontTask : AMSTask <AMSBagConsumer>

@property (nonatomic, readonly) unsigned long long mediaType;
@property (nonatomic, readonly) NSString *clientIdentifier;
@property (nonatomic, readonly) id <AMSBagProtocol> bag;
@property (nonatomic, readonly) NSString *logKey;

+ (id)createBagForSubProfile;
+ (id)bagSubProfileVersion;
+ (id)bagSubProfile;

- (nonnull instancetype)init;
- (id)performTask;
- (void)cacheWithResult:(id)result on:(id)on;
- (id)cachedResultFrom:(id)from;
- (nonnull instancetype)initWithMediaType:(unsigned long long)type clientIdentifier:(id)identifier bag:(id)bag;
- (void)performTaskAsyncWithCompletionHandler:(UnknownBlock)handler;
- (void)queryItemsWithCompletionHandler:(UnknownBlock)handler;
- (nullable NSURL *)urlBagKeyForMediaType:(unsigned long long)type;
- (void)urlForMediaType:(unsigned long long)type completionHandler:(UnknownBlock)handler;

@end
