//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@interface AMSResource : NSObject

+ (id)loadHARFileWithName:(id)name bundle:(id)bundle;
+ (id)loadHARFileWithName:(id)name bundle:(id)bundle inDirectory:(id)directory;
+ (id)loadPropertyListWithName:(id)name bundle:(id)bundle error:(id *)error;

@end
