//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@interface AMSRatingsCache : NSObject

@property (readonly) unsigned long long mediaType;
@property (readonly) NSString *storeFront;

- (nonnull instancetype)initWithMediaType:(unsigned long long)type;
- (id)cachePath;
- (id)cacheDirectory;
- (BOOL)_hasCachedData;
- (BOOL)addCacheData:(id)data;
- (id)cacheTitle;
- (void)clearCacheIfNeeded;
- (id)getCacheData;
- (nonnull instancetype)initWithMediaType:(unsigned long long)type storeFront:(id)front;

@end
