//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@interface AMSRatingsStorefrontResult : NSObject

@property (readonly) NSArray *ratingsStoreFronts;

- (nonnull instancetype)initWithDictionaries:(id)dictionaries mediaType:(unsigned long long)type;
- (id)_mapRatingsDictionaries:(id)dictionaries withMediaType:(unsigned long long)type;
- (unsigned long long)_ratingInfoMediaTypeForTaskMediaType:(unsigned long long)type;
- (nonnull instancetype)initWithData:(id)data mediaType:(unsigned long long)type;
- (nonnull instancetype)initWithURLResult:(nullable NSURL *)urlresult mediaType:(unsigned long long)type;

@end
