//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@interface AMSRatingSystem : NSObject

@property (readonly) NSString *kind;
@property (readonly) NSString *label;
@property (readonly) NSArray *contentRatings;
@property (readonly) NSString *ratingSystemID;
@property (readonly) NSArray *types;

+ (id)ratingSystemWithDictionary:(nullable NSDictionary *)dictionary;

- (nonnull instancetype)initWithDictionary:(nullable NSDictionary *)dictionary;
- (nonnull NSString *)description;

@end
