//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@interface AMSStorage : NSObject

+ (void)_setBool:(BOOL)_bool forKey:(id)key;
+ (void)setDeviceOfferEligibility:(id)eligibility;
+ (void)setSharedStoreReviewMetrics:(id)metrics forProcess:(id)process;
+ (long long)_integerForKey:(id)key defaultValue:(long long)value domain:(id)domain;
+ (id)deviceOfferEligibility;
+ (void)_setBool:(BOOL)_bool forKey:(id)key domain:(id)domain;
+ (long long)_integerForKey:(id)key defaultValue:(long long)value;
+ (id)_valueForKey:(id)key;
+ (void)_setValue:(id)value forKey:(id)key domain:(id)domain;
+ (void)_setValue:(id)value forKey:(id)key;
+ (BOOL)_boolForKey:(id)key defaultValue:(BOOL)value;
+ (void)_migrateBoolToDatabase:(BOOL)database forKey:(id)key domain:(id)domain;
+ (id)bagURLCookies;
+ (void)_setInteger:(long long)integer forKey:(id)key;
+ (id)_valueForKey:(id)key domain:(id)domain;
+ (BOOL)_boolForKey:(id)key defaultValue:(BOOL)value domain:(id)domain;
+ (id)sharedStoreReviewMetricsForProcess:(id)process;
+ (BOOL)_boolFromDatabaseForKey:(id)key defaultValue:(BOOL)value domain:(id)domain error:(id *)error;
+ (id)_valueFromDatabaseForKey:(id)key domain:(id)domain error:(id *)error;
+ (void)_setValueWithCFPreferences:(id)cfpreferences forKey:(id)key domain:(id)domain;
+ (BOOL)_setValueWithDatabase:(id)database forKey:(id)key domain:(id)domain error:(id *)error;
+ (BOOL)_setIntegerWithDatabase:(long long)database forKey:(id)key domain:(id)domain error:(id *)error;
+ (void)_migrateValueToDatabase:(id)database forKey:(id)key domain:(id)domain;
+ (BOOL)_setBoolWithDatabase:(BOOL)database forKey:(id)key domain:(id)domain error:(id *)error;
+ (long long)_integerFromCFPreferencesForKey:(id)key defaultValue:(long long)value domain:(struct __CFString *)domain;
+ (void)_setInteger:(long long)integer forKey:(id)key domain:(id)domain;
+ (id)_valueFromCFPreferencesForKey:(id)key domain:(struct __CFString *)domain;
+ (void)setBagURLCookies:(nullable NSURL *)urlcookies;
+ (long long)_integerFromDatabaseForKey:(id)key defaultValue:(long long)value domain:(id)domain error:(id *)error;
+ (void)_setBoolWithCFPreferences:(BOOL)cfpreferences forKey:(id)key domain:(struct __CFString *)domain;
+ (id)_allKeysWithDomain:(id)domain;
+ (void)_migrateIntegerToDatabase:(long long)database forKey:(id)key domain:(id)domain;
+ (void)_setIntegerWithCFPreferences:(long long)cfpreferences forKey:(id)key domain:(struct __CFString *)domain;
+ (BOOL)_boolFromCFPreferencesForKey:(id)key defaultValue:(BOOL)value domain:(struct __CFString *)domain;

@end
