//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@interface AMSSQLiteConnectionOptions : NSObject <NSCopying, NSSecureCoding>

@property (copy, nonatomic, nullable) NSString *databasePath;
@property (nonatomic) long long cacheSize;
@property (copy, nonatomic, nullable) NSString *protectionType;
@property (nonatomic) BOOL readOnly;
@property (nonatomic) BOOL checkpointingOnCloseDisabled;

+ (BOOL)supportsSecureCoding;

- (nonnull instancetype)initWithDatabasePath:(id)path;
- (BOOL)isReadOnly;
- (nonnull instancetype)copyWithZone:(nullable struct _NSZone *)zone;
- (BOOL)applyToDatabase:(struct sqlite3 *)database error:(id *)error;
- (void)encodeWithCoder:(nullable NSCoder *)coder;
- (void)setCacheSizeWithNumberOfDatabasePages:(long long)pages;
- (BOOL)isCheckpointingOnCloseDisabled;
- (void)setCacheSizeWithNumberOfKilobytes:(long long)kilobytes;
- (nonnull instancetype)initWithCoder:(nullable NSCoder *)coder;

@end
