//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSProcessInfo.h"
#include "AMSTask.h"

@class ACAccountStore;

@interface AMSSetDemoAccountTask : AMSTask

@property (readonly) ACAccountStore *accountStore;
@property (retain, nullable) AMSProcessInfo *clientInfo;
@property (retain, nullable) NSString *password;
@property (retain, nullable) NSString *username;

- (nonnull instancetype)initWithUsername:(id)username password:(id)password;
- (id)performTask;
- (nonnull instancetype)initWithUsername:(id)username password:(id)password accountStore:(id)store;

@end
