//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSBagConsumer-Protocol.h"
#include "AMSBagProtocol-Protocol.h"
#include "AMSStoreReviewGatingController.h"

@protocol OS_dispatch_queue;

@interface AMSSharedStoreReview : NSObject <AMSBagConsumer>

@property (readonly) dispatch_queue_t sharedStoreReviewQueue;
@property (retain, nonatomic, nullable) AMSStoreReviewGatingController *storeReviewGatingController;
@property (retain, nullable) id <AMSBagProtocol> bag;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)createBagForSubProfile;
+ (id)bagSubProfileVersion;
+ (id)bagSubProfile;
+ (void)_applicationDidForegroundWithCurrentTime:(id)time storeReviewMetrics:(id)metrics sessionInterval:(long long)interval;
+ (BOOL)_isRepeatedPromptsSupported;
+ (BOOL)_isGroupedLogicSupported;
+ (void)_logNewSessionWithStoreReviewMetrics:(id)metrics currentTime:(id)time;
+ (id)bagKeySet;
+ (BOOL)_shouldPromptReviewForStoreReviewMetrics:(id)metrics sessionCount:(long long)count;
+ (BOOL)_shouldPromptReviewForStoreReviewMetrics:(id)metrics currentTime:(id)time sessionCount:(long long)count promptInterval:(long long)interval;
+ (void)_logDidAttemptPromptReviewWithStoreReviewMetrics:(id)metrics currentTime:(id)time;
+ (void)_persistStoreReviewMetrics:(id)metrics;
+ (id)_storeReviewMetrics;
+ (BOOL)_shouldLogNewSessionWithLastLoggedTimeStamp:(id)stamp currentTime:(id)time sessionInterval:(long long)interval;

- (nonnull instancetype)initWithBag:(id)bag;
- (id)shouldAttemptReview;
- (BOOL)isEnabled;
- (void)didAttemptPromptReview;
- (BOOL)shouldAttemptPromptReview;
- (id)isReviewEnabled;
- (void)applicationDidForeground;

@end
