//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSSQLiteBinding-Protocol.h"
#include "AMSSQLiteConnection.h"

@interface AMSSQLiteStatement : NSObject <AMSSQLiteBinding> {
	struct sqlite3_stmt * _statement;
	AMSSQLiteStatement *_strongSelf;
}

@property (readonly, nonatomic) AMSSQLiteConnection *connection;
@property (readonly, nonatomic) struct sqlite3_stmt * sqlite3_stmt;
@property (readonly, copy, nonatomic) NSDictionary *columnIndexByName;
@property (readonly, nonatomic) BOOL readOnly;
@property (readonly, copy, nonatomic) NSString *SQL;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (int)finalizeStatement;
- (int)clearBindings;
- (int)step;
- (void)bindFloat:(float)_float atPosition:(int)position;
- (void)bindInt64:(long long)int64 atPosition:(int)position;
- (void)bindNullableString:(id)string atPosition:(int)position;
- (void)bindDate:(id)date atPosition:(int)position;
- (void)bindURL:(nullable NSURL *)url atPosition:(int)position;
- (BOOL)isReadOnly;
- (void)bindDictionary:(nullable NSDictionary *)dictionary atPosition:(int)position;
- (void)bindStringCopy:(id)copy atPosition:(int)position;
- (void)bindNumber:(id)number atPosition:(int)position;
- (nonnull instancetype)initWithStatement:(struct sqlite3_stmt *)statement onConnection:(id)connection;
- (void)bindDouble:(double)_double atPosition:(int)position;
- (void)bindInt:(int)_int atPosition:(int)position;
- (void)bindArray:(id)array atPosition:(int)position;
- (void)bindString:(id)string atPosition:(int)position;
- (void)bindDataCopy:(id)copy atPosition:(int)position;
- (void)bindData:(id)data atPosition:(int)position;
- (int)reset;
- (void)bindNullAtPosition:(int)position;

@end
