//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@interface AMSStreamHTTPArchiveEntryController : NSObject

+ (void)initialize;
+ (id)buffer;
+ (void)ams_streamEntriesToDisk;
+ (id)_harFileURLsInPath:(id)path;
+ (id)ams_combineEntriesForPath:(id)path error:(id *)error;
+ (void)ams_addEntriesForTaskInfo:(id)info;
+ (void)_writeEntries:(id)entries toStream:(id)stream;
+ (id)_createNewFileWithFileName:(id)name outputDirectory:(id)directory error:(id *)error;
+ (void)_performCombiningFiles:(id)files toStream:(id)stream;
+ (id)_createNewFileNameForCombining:(BOOL)combining extension:(id)extension;
+ (BOOL)_writeFooterToStream:(id)stream;
+ (BOOL)_writeData:(id)data enumeratingBytesToStream:(id)stream;
+ (void)_moveTemporaryFileURL:(nullable NSURL *)url toFinalFileURL:(nullable NSURL *)url;
+ (id)_headerData;
+ (BOOL)_shouldWriteEntryDirectlyToDiskForURLString:(nullable NSURL *)urlstring;
+ (void)_streamToDiskWithEntries:(id)entries;
+ (BOOL)_writeHeaderToStream:(id)stream;
+ (void)_updateMaxBufferSize;
+ (id)_footerData;

@end
