//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@protocol OS_dispatch_queue;

@interface AMSSafariDataUpdate : NSObject

@property (retain, nullable) dispatch_queue_t queue;
@property (retain, nullable) NSMutableArray *updateHandlers;

- (nonnull instancetype)init;
- (void)dealloc;
- (void)_handleUpdateAvailableNotification:(id)notification;
- (void)_invokeHandlersWithURL:(nullable NSURL *)url;
- (id)publishUpdate:(id)update;
- (void)registerForUpdatesWithHandler:(UnknownBlock)handler;

@end
