//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@interface AMSSQLitePredicate : NSObject <NSCopying>

- (id)SQLForEntityClass:(Class)_class;
- (id)SQLJoinClausesForEntityClass:(Class)_class;
- (nonnull instancetype)copyWithZone:(nullable struct _NSZone *)zone;
- (BOOL)isEqual:(nullable id)object;
- (unsigned long long)hash;
- (void)applyBinding:(id)binding atIndex:(inout int *)index;

@end
