//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@protocol AMSSecurityServiceInterface <NSObject>

@required

- (void)deleteAllKeysWithCompletion:(UnknownBlock)completion;
- (void)handleResponse:(id)response completion:(UnknownBlock)completion;
- (void)hasKeysForAccount:(id)account forSignaturePurpose:(unsigned long long)purpose completion:(UnknownBlock)completion;
- (void)isActionSupportedForType:(long long)type account:(id)account options:(id)options completion:(UnknownBlock)completion;
- (void)isBiometricsAvailableForAccount:(id)account completion:(UnknownBlock)completion;
- (void)isDeviceInBiometricLockoutWithCompletion:(UnknownBlock)completion;
- (void)isIdentityMapValidWithCompletion:(UnknownBlock)completion;
- (void)paymentServicesMerchantURLWithCompletion:(UnknownBlock)completion;
- (void)performBiometricTokenUpdateWithAccount:(id)account clientInfo:(id)info additionalDialogMetrics:(id)metrics shouldGenerateKeysOnly:(BOOL)only shouldRequestConfirmation:(BOOL)confirmation userInitiated:(BOOL)initiated completion:(UnknownBlock)completion;
- (void)performBiometricsAvailabilityTaskWithAccount:(id)account signaturePurpose:(unsigned long long)purpose completion:(UnknownBlock)completion;
- (void)performClientCertChainRequestWithAccount:(id)account options:(id)options completion:(UnknownBlock)completion;
- (void)performSilentEnrollmentWithRequest:(id)request logKey:(id)key completion:(UnknownBlock)completion;
- (void)saveIdentityMapWithCompletion:(UnknownBlock)completion;
- (void)shouldAttemptApplePayWithAccount:(id)account options:(id)options countryCode:(id)code paymentNetworks:(id)networks completion:(UnknownBlock)completion;
- (void)shouldAttemptApplePayWithCountryCode:(id)code paymentNetworks:(id)networks completion:(UnknownBlock)completion;
- (void)signChallengeForRequest:(id)request completion:(UnknownBlock)completion;
- (void)signedHeadersForRequest:(id)request buyParams:(id)params completion:(UnknownBlock)completion;

@optional

@end
