//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSSQLiteConnection.h"

@interface AMSSQLiteSchema : NSObject {
	AMSSQLiteConnection *_connection;
}

@property (readonly) long long currentUserVersion;

- (nonnull instancetype)initWithConnection:(id)connection;
- (void)_setUserVersion:(long long)version;
- (BOOL)migrateToVersion:(long long)version usingBlock:(UnknownBlock)block error:(id *)error;
- (BOOL)tableExists:(id)exists;
- (BOOL)column:(id)column existsInTable:(id)table;

@end
