//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSSQLitePropertyPredicate.h"
#include "AMSSQLiteQuery.h"

@interface AMSSQLiteContainsPredicate : AMSSQLitePropertyPredicate <NSCopying>

@property (readonly, nonatomic) BOOL negative;
@property (readonly, nonatomic) AMSSQLiteQuery *query;
@property (readonly, nonatomic) NSString *queryProperty;
@property (readonly, nonatomic) NSArray *values;

+ (id)containsPredicateWithProperty:(id)property values:(id)values;
+ (id)doesNotContainPredicateWithProperty:(id)property values:(id)values;
+ (id)containsPredicateWithProperty:(id)property query:(id)query queryProperty:(id)property;

- (id)SQLForEntityClass:(Class)_class;
- (nonnull instancetype)copyWithZone:(nullable struct _NSZone *)zone;
- (BOOL)isNegative;
- (BOOL)isEqual:(nullable id)object;
- (void)applyBinding:(id)binding atIndex:(inout int *)index;

@end
