//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSTask.h"

@interface AMSSubscriptionEntitlementsTask : AMSTask

@property long long cachePolicy;
@property BOOL extendedCarrierCheck;
@property long long mediaType;

+ (unsigned long long)_segmentForMediaType:(long long)type error:(id *)error;
+ (id)updateCacheForMediaType:(long long)type account:(id)account data:(id)data;

- (nonnull instancetype)initWithMediaType:(long long)type;
- (id)_fetchEntitlementsFromASD;
- (id)_fetchEntitlementsFromIC;
- (id)_queryCachedASDSubscriptionForSegment:(unsigned long long)segment controller:(id)controller reloadIfNeeded:(BOOL)needed;
- (id)_reloadASDSubscriptionForSegment:(unsigned long long)segment controller:(id)controller;
- (id)_resultFromASDEntitlements:(id)asdentitlements;
- (id)_resultFromICResponse:(id)icresponse;
- (BOOL)_shouldIgnoreCaches;
- (BOOL)_shouldIgnoreRemoteData;
- (id)performExternalLookup;

@end
