//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSBagConsumer-Protocol.h"
#include "AMSBagProtocol-Protocol.h"
#include "AMSTask.h"

@class ACAccount;

@interface AMSSyncRestrictedRegionTask : AMSTask <AMSBagConsumer>

@property (retain, nullable) ACAccount *account;
@property (retain, nullable) id <AMSBagProtocol> bag;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)createBagForSubProfile;
+ (id)bagSubProfileVersion;
+ (id)bagSubProfile;
+ (double)checkRestrictedRegionDurationValueFromBag:(id)bag;
+ (id)createSyncAccountFlagsTaskForAccount:(id)account bag:(id)bag;
+ (BOOL)didExceededSyncDuration:(double)duration lastTimestamp:(double)timestamp currentTimestamp:(double)timestamp;
+ (double)durationOfSyncRestrictedRegionValueFromBag:(id)bag;
+ (BOOL)hasCachedRestrictedRegionsValueFromAccount:(id)account cachedTimestamp:(double *)timestamp;
+ (BOOL)storefrontContainsRestrictedRegionsValueFromBag:(id)bag;

- (nonnull instancetype)initWithAccount:(id)account;
- (void)cacheRestrictedRegionSyncTimestamp:(double)timestamp;
- (nonnull instancetype)initWithAccount:(id)account bag:(id)bag;
- (id)performSync;

@end
