//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@protocol OS_dispatch_queue;

@interface AMSServerDataCacheService : NSObject

@property (retain, nullable) NSXPCConnection *connection;
@property (retain, nullable) dispatch_queue_t queue;

- (id)proxyWithErrorHandler:(UnknownBlock)handler;
- (id)updateCacheForAccountDSID:(nullable NSNumber *)dsID withCacheTypeIDs:(id)ids;
- (id)_newRemoteConnection;
- (id)_makeRemoteConnectionInterface;
- (id)setUpCacheForAccountDSID:(nullable NSNumber *)dsID;
- (id)updateCacheForAccountDSID:(nullable NSNumber *)dsID withCachePayload:(id)payload;
- (void)_removeRemoteConnection;
- (id)granularNotificationSettingsForAccountDSID:(nullable NSNumber *)dsID bundleID:(id)id networkPolicy:(long long)policy;
- (nonnull instancetype)init;
- (id)tearDownCacheForAccountDSID:(nullable NSNumber *)dsID;
- (id)reminderEventsForAccount:(id)account service:(id)service eventType:(id)type networkPolicy:(long long)policy;
- (id)setUpCacheForAccount:(id)account;
- (void)dealloc;
- (id)dataForAccountDSID:(nullable NSNumber *)dsID cacheTypeID:(id)id networkPolicy:(long long)policy;

@end
