//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@protocol AMSSQLiteEntity <NSObject>

@required

+ (id)databaseTable;
+ (id)disambiguatedSQLForProperty:(id)property;
+ (id)foreignDatabaseColumnForProperty:(id)property;
+ (id)foreignDatabaseTableForProperty:(id)property;
+ (id)foreignDatabaseTablesToDelete;
+ (id)foreignKeyColumnForTable:(id)table;
+ (id)joinClauseForProperty:(id)property;

- (id)objectForKeyedSubscript:(id)subscript;
- (id)valueForProperty:(id)property;
- (void)setObject:(id)object forKeyedSubscript:(id)subscript;
- (BOOL)setValue:(id)value forProperty:(id)property;
- (BOOL)deleteFromDatabase;
- (id)getValuesForProperties:(id)properties;
- (BOOL)setValuesWithDictionary:(nullable NSDictionary *)dictionary;

@optional

@end
