//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSBagFrozenDataSource.h"
#include "AMSBagProtocol-Protocol.h"
#include "AMSProcessInfo.h"

@interface AMSSnapshotBag : NSObject <NSSecureCoding, AMSBagProtocol>

@property (retain, nullable) AMSBagFrozenDataSource *dataSource;
@property (readonly, nonatomic) NSDictionary *dictionary;
@property (readonly, nonatomic) AMSProcessInfo *optionalProcessInfo;
@property (readonly) NSDate *creationDate;
@property (readonly) BOOL expired;
@property (readonly) NSDate *expirationDate;
@property (readonly, copy) NSString *profile;
@property (readonly, copy) NSString *profileVersion;
@property (readonly, copy, nonatomic) AMSProcessInfo *processInfo;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (BOOL)supportsSecureCoding;

- (BOOL)isLoaded;
- (id)arrayForKey:(id)key;
- (BOOL)isExpired;
- (id)integerForKey:(id)key;
- (id)boolForKey:(id)key;
- (id)compile;
- (id)doubleForKey:(id)key;
- (id)stringForKey:(id)key;
- (nonnull instancetype)initWithData:(id)data;
- (void)createSnapshotWithCompletion:(UnknownBlock)completion;
- (void)encodeWithCoder:(nullable NSCoder *)coder;
- (id)URLForKey:(id)key;
- (nullable NSDictionary *)dictionaryForKey:(id)key;
- (id)URLForKey:(id)key account:(id)account;
- (id)_initWithDataSource:(id)source;
- (nonnull instancetype)init;
- (nonnull instancetype)initWithCoder:(nullable NSCoder *)coder;
- (id)_initWithSnapshotBag:(id)bag;

@end
