//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSSQLiteConnection.h"
#include "AMSSQLiteConnectionDelegate-Protocol.h"

@protocol OS_dispatch_queue;

@interface AMSStorageDatabase : NSObject <AMSSQLiteConnectionDelegate>

@property (retain, nullable) AMSSQLiteConnection *connection;
@property (retain, nullable) dispatch_queue_t internalQueue;
@property (retain, nullable) NSString *domain;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (BOOL)isFeatureSupported;
+ (id)sharedDatabaseWithDomain:(id)domain;

- (BOOL)booleanForKey:(id)key error:(id *)error;
- (id)_convertToValueWithData:(id)data valueType:(long long)type error:(id *)error;
- (id)isLassetAndReturnError:(id *)error;
- (BOOL)setDouble:(double)_double forKey:(id)key error:(id *)error;
- (BOOL)setInteger:(long long)integer forKey:(id)key error:(id *)error;
- (id)_cachePath;
- (BOOL)setBoolean:(BOOL)boolean forKey:(id)key error:(id *)error;
- (id)_convertToDataWithValue:(id)value valueType:(long long)type error:(id *)error;
- (id)_plistValueForData:(id)data error:(id *)error;
- (long long)integerForKey:(id)key error:(id *)error;
- (BOOL)connection:(id)connection needsResetForCorruptionError:(nullable NSError *)error error:(out id *)error;
- (void)close;
- (id)sizeWithError:(id *)error;
- (nonnull instancetype)initWithDomain:(id)domain;
- (id)allKeysForDomain:(id)domain withError:(id *)error;
- (id)valueForKey:(id)key error:(id *)error;
- (BOOL)_setValueData:(id)data valueType:(long long)type forKey:(id)key error:(id *)error;
- (double)doubleForKey:(id)key error:(id *)error;
- (void)_performTransaction:(UnknownBlock)transaction;
- (BOOL)setValue:(id)value forKey:(id)key error:(id *)error;
- (id)allKeyValuesWithError:(id *)error;
- (BOOL)setIsLasset:(id)lasset error:(id *)error;
- (long long)_valueTypeForValue:(id)value;
- (BOOL)deleteForKey:(id)key error:(id *)error;
- (id)_dataForPlistValue:(id)value error:(id *)error;
- (void)dealloc;
- (id)_allKeysPrefixedByDomainWithError:(id *)error;

@end
