//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSSQLiteConnection.h"
#include "AMSSQLiteQueryDescriptor.h"

@interface AMSSQLiteQuery : NSObject {
	AMSSQLiteQueryDescriptor *_descriptor;
}

@property (readonly) AMSSQLiteConnection *connection;
@property (readonly) AMSSQLiteQueryDescriptor *queryDescriptor;
@property (readonly) long long countOfEntities;

- (void)enumeratePersistentIDsAndProperties:(id)properties usingBlock:(UnknownBlock)block;
- (void)enumeratePersistentIDsUsingBlock:(UnknownBlock)block;
- (id)_newSelectSQLWithProperties:(id)properties;
- (void)applyBinding:(id)binding atIndex:(inout int *)index;
- (id)copyEntityIdentifiers;
- (id)copySelectSQLWithProperties:(id)properties;
- (BOOL)createTemporaryTableWithName:(id)name properties:(id)properties;
- (BOOL)deleteAllEntities;
- (void)enumerateMemoryEntitiesUsingBlock:(UnknownBlock)block;
- (void)enumerateMemoryEntitiesWithProperties:(id)properties usingBlock:(UnknownBlock)block;
- (nonnull instancetype)initOnConnection:(id)connection descriptor:(id)descriptor;

@end
