//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSThreadSafeObject.h"

@interface AMSThreadSafeSet : NSObject

@property (retain, nullable) AMSThreadSafeObject *backingSet;
@property (readonly, copy) NSArray *allObjects;
@property (readonly) unsigned long long count;

- (void)addObject:(id)object;
- (BOOL)containsObject:(id)object;
- (void)removeObject:(id)object;
- (nonnull instancetype)init;

@end
