//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@interface AMSThreadSafeObject : NSObject

@property (readonly) struct os_unfair_lock_s { unsigned int x0; } lock;
@property (retain, nullable) id underlyingObject;

- (nonnull instancetype)initWithObject:(id)object;
- (id)accessAndSetObjectWithBlock:(UnknownBlock)block;
- (void)read:(UnknownBlock)read;
- (void)setObject:(id)object;
- (id)object;
- (nonnull instancetype)init;
- (void)readWrite:(UnknownBlock)write;

@end
