//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@interface AMSTreatment : NSObject <NSSecureCoding>

@property long long participationType;
@property (readonly) NSDictionary *dictionaryRepresentation;
@property (readonly) NSDate *endDate;
@property (readonly, copy) NSString *identifier;
@property (readonly) NSDate *startDate;

+ (BOOL)supportsSecureCoding;

- (void)encodeWithCoder:(nullable NSCoder *)coder;
- (BOOL)isEqual:(nullable id)object;
- (unsigned long long)hash;
- (nonnull instancetype)initWithEndDate:(id)date identifier:(id)identifier startDate:(id)date;
- (nonnull instancetype)initWithCoder:(nullable NSCoder *)coder;

@end
