//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@interface AMSTapToRadar : NSObject

+ (long long)_classificationFromAMSClassification:(unsigned long long)amsclassification;
+ (long long)_componentIDForComponent:(unsigned long long)component;
+ (id)_componentNameForComponent:(unsigned long long)component;
+ (id)_componentVersionForComponent:(unsigned long long)component;
+ (id)_convertClassification:(unsigned long long)classification;
+ (id)_convertReproducibility:(unsigned long long)reproducibility;
+ (long long)_reproducibilityFromAMSReproducibility:(unsigned long long)amsreproducibility;
+ (BOOL)openAPIWithRadarTitle:(id)title radarDescription:(id)description promptTitle:(id)title promptDescription:(id)description classification:(unsigned long long)classification component:(unsigned long long)component reproducibility:(unsigned long long)reproducibility keywordIds:(id)ids;
+ (void)openURLWithRadarTitle:(id)title radarDescription:(id)description promptTitle:(id)title promptDescription:(id)description classification:(unsigned long long)classification component:(unsigned long long)component reproducibility:(unsigned long long)reproducibility keywordIds:(id)ids;
+ (void)openWithRadarTitle:(id)title radarDescription:(id)description promptTitle:(id)title promptDescription:(id)description classification:(unsigned long long)classification component:(unsigned long long)component reproducibility:(unsigned long long)reproducibility keywordIds:(id)ids;
+ (void)openWithTitle:(id)title description:(id)description classification:(unsigned long long)classification reproducibility:(unsigned long long)reproducibility keywordIds:(id)ids;

@end
