//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSThreadSafeObject.h"

@interface AMSThreadSafeDictionary : NSObject

@property (retain, nullable) AMSThreadSafeObject *backingDictionary;
@property (readonly, copy) NSArray *allKeys;
@property (readonly, copy) NSArray *allValues;

- (void)removeAllObjects;
- (id)objectForKey:(id)key;
- (void)removeObjectForKey:(id)key;
- (nonnull instancetype)init;
- (id)objectForKeyedSubscript:(id)subscript;
- (void)setObject:(id)object forKey:(id)key;
- (void)readWrite:(UnknownBlock)write;
- (void)setObject:(id)object forKeyedSubscript:(id)subscript;

@end
