//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@protocol AMSUserNotificationStrategy

@required

+ (BOOL)_badgeBundleId:(id)id increment:(BOOL)increment error:(id *)error;
+ (id)_activeNotificationsWithCenterBundleId:(id)id;
+ (id)_postNotification:(id)notification bag:(id)bag centerBundleId:(id)id;
+ (id)_removeNotification:(id)notification centerBundleId:(id)id;
+ (id)_removeNotificationWithIdentifier:(id)identifier centerBundleId:(id)id logKey:(id)key scheduledOnly:(BOOL)only;

@optional

@end
