//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSDeviceInfo-Protocol.h"
#include "AMSMappedBundleInfo.h"
#include "AMSProcessInfo.h"

@interface AMSUserAgent : NSObject

@property (readonly) AMSMappedBundleInfo *bundleInfo;
@property (readonly) AMSProcessInfo *processInfo;
@property (readonly) id <AMSDeviceInfo> deviceInfoProvider;
@property (retain, nullable) NSString *clientName;
@property (retain, nullable) NSString *clientVersion;

+ (id)userAgentForProcessInfo:(id)info;
+ (id)cachedUserAgentForBundleIdentifier:(id)identifier;
+ (void)cacheUserAgent:(id)agent forBundleIdentifier:(id)identifier;
+ (id)_sharedCache;

- (id)_macComponentAccountMediaType;
- (id)_initWithProcessInfo:(id)info deviceInfoProvider:(id)provider;
- (id)compile;
- (id)_sharedComponentParentheticalWithFairPlayDeviceType:(id)type;
- (id)_sharedComponentFrameworkVersion;
- (id)_macComponentWebKitVersionString;
- (id)_sharedComponentFairPlayDeviceType;
- (id)_userAgentSuffix;
- (id)_compileAndShouldCache:(BOOL *)cache;
- (id)_compiledAMSUserAgentShouldCache:(BOOL *)cache;
- (nonnull instancetype)initWithProcessInfo:(id)info;
- (id)_sharedComponentParentheticalWithFairPlayDeviceType:(id)type productType:(id)type;
- (id)_macComponentParenthetical;
- (id)_macComponentClientInfo;

@end
