//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@interface AMSUserNotificationAuthorizationOptions : NSObject <NSCopying, NSSecureCoding>

@property unsigned long long authorizationOptions;
@property (retain, nullable) NSDictionary *metricsOverlay;
@property BOOL userInitiated;

+ (BOOL)supportsSecureCoding;

- (nonnull instancetype)initWithOptionsDictionary:(nullable NSDictionary *)dictionary;
- (nonnull instancetype)copyWithZone:(nullable struct _NSZone *)zone;
- (void)encodeWithCoder:(nullable NSCoder *)coder;
- (BOOL)isEqual:(nullable id)object;
- (id)optionsDictionary;
- (nonnull instancetype)init;
- (nonnull NSString *)description;
- (nonnull instancetype)initWithCoder:(nullable NSCoder *)coder;

@end
