//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSAuthenticateResult.h"
#include "AMSDialogResult.h"

@interface AMSURLAction : NSObject <NSSecureCoding>

@property (retain, nullable) AMSAuthenticateResult *authenticateResult;
@property (retain, nullable) AMSDialogResult *dialogResult;
@property (retain, nullable) NSDictionary *updatedHeaders;
@property (retain, nullable) NSData *updatedBody;
@property (retain, nullable) NSString *updatedMethod;
@property (readonly) long long actionType;
@property (retain, nullable) NSString *updatedBuyParams;
@property (readonly) NSError *error;
@property (retain, nullable) NSString *reason;
@property (readonly) NSURL *redirectURL;
@property (retain, nullable) NSString *retryIdentifier;

+ (id)redirectActionWithURL:(nullable NSURL *)url;
+ (BOOL)supportsSecureCoding;
+ (id)retryAction;
+ (id)actionWithError:(nullable NSError *)error;
+ (id)proceedAction;

- (nonnull instancetype)initWithType:(long long)type error:(nullable NSError *)error reason:(id)reason redirectURL:(nullable NSURL *)url;
- (nonnull instancetype)initWithType:(long long)type;
- (void)encodeWithCoder:(nullable NSCoder *)coder;
- (nonnull NSString *)description;
- (nonnull instancetype)initWithCoder:(nullable NSCoder *)coder;

@end
