//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSResponseDecoding-Protocol.h"

@interface AMSURLResponseDecoder : NSObject <AMSResponseDecoding>

@property (copy, nonatomic, nullable) NSIndexSet *allowedStatusCodes;
@property (copy, nonatomic, nullable) NSSet *allowedContentTypes;

- (id)resultFromResult:(id)result error:(id *)error;
- (nonnull instancetype)init;

@end
