//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSContiguousActionPerformer.h"
#include "AMSURLAction.h"
#include "AMSURLRequestProperties.h"
#include "AMSURLSession.h"

@class NSURLResponse, NSURLSessionTask, NSURLSessionTaskMetrics;
@protocol OS_dispatch_queue;

@interface AMSURLTaskInfo : NSObject {
	BOOL _performingBlockWithDataAccess;
}

@property (readonly) struct os_unfair_recursive_lock_s { struct os_unfair_lock_s { unsigned int x0; } x0; unsigned int x1; } taskLock;
@property (readonly) dispatch_queue_t taskQueue;
@property (readonly) AMSContiguousActionPerformer *contiguousActionPerformer;
@property (copy, nullable) UnknownBlock completionBlock;
@property (readonly) NSData *data;
@property (retain, nullable) NSError *error;
@property (retain, nullable) NSURLSessionTaskMetrics *metrics;
@property unsigned long long previousAuthorizationCredentialSource;
@property (retain, nullable) AMSURLRequestProperties *properties;
@property (retain, nullable) AMSURLAction *receivedAction;
@property (retain, nullable) NSURLResponse *response;
@property (retain, nullable) NSURLResponse *originalResponse;
@property long long retryCount;
@property (readonly) NSSet *retryIdentifiers;
@property (retain, nullable) AMSURLSession *session;
@property unsigned long long signpostID;
@property (readonly) NSURLSessionTask *task;

+ (void)removeTaskInfoForTask:(id)task;
+ (id)sharedTaskStore;
+ (id)taskInfoForTask:(id)task;
+ (id)sharedTaskQueue;
+ (id)createTaskInfoForTask:(id)task;

- (void)assertIsOnPrivateQueue;
- (void)appendData:(id)data;
- (void)continueContiguousAsyncActionWithIdentifier:(unsigned long long)identifier block:(UnknownBlock)block;
- (void)setAccount:(id)account;
- (void)performAsyncBlockWithData:(UnknownBlock)data;
- (void)performSyncBlockWithExclusiveAccess:(UnknownBlock)access;
- (void)performSyncBlock:(UnknownBlock)block;
- (void)addRetryIdentifier:(id)identifier;
- (unsigned long long)startContiguousAsyncActionWithInitialBlock:(UnknownBlock)block;
- (void)performAsyncBlock:(UnknownBlock)block;
- (void)migrateFromTaskInfo:(id)info;
- (nonnull instancetype)initWithTask:(id)task;
- (void)_performDataAccessUsingBlock:(UnknownBlock)block;
- (id)createMetricsContextForDecodedObject:(id)object;
- (void)assertHasExclusiveAccess;
- (unsigned long long)startContiguousAsyncActionWithInitialDataBlock:(UnknownBlock)block;
- (void)finishContiguousAsyncActionWithIdentifier:(unsigned long long)identifier;

@end
