//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSBagConsumer-Protocol.h"
#include "AMSBagProtocol-Protocol.h"
#include "AMSFairPlayDeviceIdentity.h"
#include "AMSFairPlayDeviceIdentityNetworkProviderProtocol-Protocol.h"
#include "AMSKeychainOptions.h"
#include "AMSMetricsLoadURLOverlay.h"
#include "AMSProcessInfo.h"
#include "AMSRequestEncoding-Protocol.h"
#include "AMSResponseDecoding-Protocol.h"
#include "AMSURLBagContract-Protocol.h"
#include "AMSURLRequestProperties.h"

@class ACAccount;
@protocol OS_dispatch_queue;

@interface AMSURLRequestEncoder : NSObject <AMSBagConsumer, AMSRequestEncoding> {
	dispatch_queue_t _internalQueue;
	long long _encodeCount;
}

@property (copy, nonatomic, nullable) AMSURLRequestProperties *parentProperties;
@property BOOL alwaysIncludeAuthKitHeaders;
@property BOOL alwaysIncludeMMeClientInfoAndDeviceHeaders;
@property BOOL excludeIdentifierHeadersForAccount;
@property BOOL preserveQueryParameterEncoding;
@property BOOL shouldSetStorefrontHeader;
@property BOOL shouldSetCookieHeader;
@property (retain, nullable) id <AMSFairPlayDeviceIdentityNetworkProviderProtocol> fpdiNetworkProvider;
@property (retain, nullable) AMSFairPlayDeviceIdentity *fairPlayDeviceIdentity;
@property (retain, nullable) ACAccount *account;
@property long long anisetteType;
@property (retain, nullable) id <AMSBagProtocol> bag;
@property (retain, nullable) AMSProcessInfo *clientInfo;
@property BOOL compressRequestBody;
@property BOOL disableResponseDecoding;
@property long long dialogOptions;
@property BOOL enableRemoteSecuritySigning;
@property (retain, nullable) NSArray *groupRequestAccounts;
@property (retain, nullable) NSString *gsTokenIdentifier;
@property BOOL includeClientVersions;
@property (retain, nullable) AMSKeychainOptions *keychainOptions;
@property (retain, nullable) NSString *logUUID;
@property long long mescalType;
@property long long requestEncoding;
@property (retain, nullable) id <AMSResponseDecoding> responseDecoder;
@property BOOL shouldSetCookiesFromResponse;
@property BOOL shouldSetStorefrontFromResponse;
@property BOOL urlKnownToBeTrusted;
@property (retain, nullable) Class paymentSheetTaskClass;
@property (retain, nullable) AMSMetricsLoadURLOverlay *loadURLOverlay;
@property (retain, nullable) id <AMSURLBagContract> bagContract;
@property long long dataEncoding;
@property (copy, nullable) NSDictionary *additionalMetrics;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)createBagForSubProfile;
+ (id)bagSubProfileVersion;
+ (id)bagSubProfile;
+ (id)_createOversizedHeadersPayloadForRequest:(id)request totalHeaderSize:(unsigned long long)size threshold:(unsigned long long)threshold maxSize:(unsigned long long)size;
+ (id)bagKeySet;

- (id)requestByEncodingRequest:(id)request parameters:(id)parameters;
- (id)requestWithMethod:(long long)method URLString:(nullable NSURL *)urlstring parameters:(id)parameters error:(id *)error;
- (id)requestWithMethod:(long long)method bagURL:(nullable NSURL *)url headers:(id)headers parameters:(id)parameters;
- (id)requestWithMethod:(long long)method bagURL:(nullable NSURL *)url parameters:(id)parameters error:(id *)error;
- (id)requestWithMethod:(long long)method URL:(nullable NSURL *)url parameters:(id)parameters;
- (id)requestWithMethod:(long long)method URLString:(nullable NSURL *)urlstring error:(id *)error;
- (id)requestWithMethod:(long long)method URL:(nullable NSURL *)url error:(id *)error;
- (id)requestWithMethod:(long long)method bagURL:(nullable NSURL *)url error:(id *)error;
- (id)requestByEncodingRequest:(id)request parameters:(id)parameters error:(id *)error;
- (id)requestWithMethod:(long long)method bagURL:(nullable NSURL *)url parameters:(id)parameters;
- (id)requestByEncodingRequestAndReturnSigningErrors:(nullable NSError *)errors parameters:(id)parameters;
- (id)_methodStringFromMethod:(long long)method;
- (nonnull instancetype)initWithBagContract:(id)contract;
- (void)_triggerAutoBugCaptureForOversizedHeaders:(id)headers totalHeaderSize:(unsigned long long)size threshold:(unsigned long long)threshold maxSize:(unsigned long long)size;
- (id)requestWithMethod:(long long)method URL:(nullable NSURL *)url headers:(id)headers parameters:(id)parameters;
- (void)_personalizeKeychainOptionsForAccount:(id)account;
- (id)requestWithMethod:(long long)method URL:(nullable NSURL *)url parameters:(id)parameters error:(id *)error;
- (nonnull instancetype)initWithBag:(id)bag;
- (void)_checkHeaderSizeAndTriggerAutoBugCaptureIfNeeded:(id)needed;
- (id)_addCookiesToRequest:(id)request account:(id)account;
- (nonnull instancetype)init;

@end
