//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@class NSURLResponse, NSURLSessionTask, NSURLSessionTaskMetrics;

@interface AMSURLResult : NSObject

@property (retain, nullable) NSData *data;
@property (readonly) NSDictionary *loadURLEventDictionary;
@property (retain, nullable) NSString *logUUID;
@property (readonly) NSURLSessionTaskMetrics *taskMetrics;
@property (retain, nullable) NSURLResponse *response;
@property (retain, nullable) NSURLSessionTask *task;
@property (retain, nullable) id object;
@property (readonly) NSString *responseCorrelationId;
@property (readonly) long long responseStatusCode;
@property (readonly) NSDictionary *responseHeaders;

+ (id)URLResultPromiseWithTaskInfo:(id)info object:(id)object;

- (id)valueForHTTPHeaderField:(id)field;
- (nonnull instancetype)initWithTask:(id)task response:(id)response data:(id)data object:(id)object logUUID:(id)uuid taskMetrics:(id)metrics loadURLEventDictionary:(nullable NSDictionary *)dictionary;
- (nonnull instancetype)initWithTaskInfo:(id)info object:(id)object loadURLEventDictionary:(nullable NSDictionary *)dictionary;
- (nonnull instancetype)initWithTask:(id)task response:(id)response data:(id)data object:(id)object;
- (nonnull instancetype)initWithResult:(id)result;

@end
