//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSBagConsumer-Protocol.h"
#include "AMSUserNotificationAction.h"

@class ACAccount;

@interface AMSUserNotification : NSObject <AMSBagConsumer>

@property BOOL anonymizeMetrics;
@property long long intent;
@property (retain, nullable) NSString *categoryIdentifier;
@property BOOL shouldSuppressDefaultAction;
@property (retain, nullable) NSString *threadIdentifier;
@property (retain, nullable) ACAccount *account;
@property BOOL appPersonalize;
@property (retain, nullable) NSURL *artworkUrl;
@property (retain, nullable) NSURL *videoUrl;
@property (retain, nullable) NSArray *buttonActions;
@property (retain, nullable) NSString *centerBundleIdentifier;
@property (retain, nullable) NSString *iconBundleIdentifier;
@property (retain, nullable) AMSUserNotificationAction *defaultAction;
@property BOOL explicitContent;
@property (retain, nullable) NSString *identifier;
@property (retain, nullable) NSString *informativeText;
@property (retain, nullable) NSString *logKey;
@property (retain, nullable) NSDictionary *metricsEvent;
@property (retain, nullable) NSDate *scheduledTime;
@property (retain, nullable) NSSet *subsections;
@property (retain, nullable) NSString *subtitle;
@property (retain, nullable) NSString *title;
@property (retain, nullable) NSMutableDictionary *userInfo;
@property unsigned long long interruptionLevel;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)createBagForSubProfile;
+ (id)bagSubProfileVersion;
+ (id)bagSubProfile;
+ (id)bagKeySet;
+ (id)handleNotificationResponse:(id)response bag:(id)bag;
+ (BOOL)shouldDeleteNotificationForPayload:(id)payload outIdentifier:(id *)identifier scheduledOnly:(BOOL *)only;
+ (id)_cachedImagePathForIdentifier:(id)identifier assetURL:(nullable NSURL *)url;
+ (BOOL)_canParseNotificationWithIdentifier:(id)identifier userInfo:(id)info;
+ (id)_dateFromString:(id)string;
+ (id)_downloadAssetAtUrl:(nullable NSURL *)url withIdentifier:(id)identifier logKey:(id)key bag:(id)bag;
+ (id)_identifierFromPayload:(id)payload;
+ (id)handleNotificationResponse:(id)response bagContract:(id)contract;
+ (void)handleServiceExtensionNotificationRequest:(id)request bag:(id)bag withContentHandler:(UnknownBlock)handler;
+ (id)notificationCenter:(id)center didChangeSettings:(id)settings bag:(id)bag;
+ (id)notificationCenter:(id)center openSettingsForNotification:(id)notification bag:(id)bag;
+ (id)notificationWithPayload:(id)payload andConfig:(id)config;
+ (void)openAppUsingBundleIdentifier:(id)identifier;
+ (BOOL)shouldHandleNotificationResponse:(id)response;
+ (BOOL)shouldHandleServiceExtensionNotificationRequest:(id)request;

- (nonnull instancetype)init;
- (nonnull instancetype)initWithTitle:(id)title;
- (id)_generatePayloadWithBase:(id)base;
- (void)addButtonAction:(id)action;
- (id)createNSUserNotification;
- (id)createUNNotificationActions;
- (id)createUNNotificationContent;
- (id)createUNNotificationRequestFromContent:(id)content;
- (id)determineSelectedActionFromResponse:(id)response error:(id *)error;
- (id)handleSelectedButton:(id)button bag:(id)bag;
- (id)handleSelectedButton:(id)button bagContract:(id)contract;
- (nonnull instancetype)initWithNSUserNotification:(id)notification;
- (nonnull instancetype)initWithPayload:(id)payload andConfig:(id)config;
- (nonnull instancetype)initWithTitle:(id)title intent:(long long)intent;
- (nonnull instancetype)initWithUNNotification:(id)unnotification;

@end
