//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSMutablePromise.h"

@protocol OS_dispatch_queue;

@interface AMSUniqueExecutionQueue : NSObject

@property (copy, nullable) UnknownBlock block;
@property (retain, nullable) dispatch_queue_t completionCallbacksQueue;
@property (retain, nullable) dispatch_queue_t executeBlockQueue;
@property (retain, nullable) AMSMutablePromise *executionPromise;
@property (readonly) dispatch_queue_t executionPromiseAccessQueue;

- (void)addCompletionBlock:(UnknownBlock)block;
- (nonnull instancetype)initWithBlock:(UnknownBlock)block;
- (void)_beginExecutingBlockWithPromise:(id)promise;
- (id)_createExecutionPromise;
- (void)addCompletionBlockForSubsequentExecution:(UnknownBlock)execution;

@end
