//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSTask.h"
#include "AMSUserNotificationAuthorizationOptions.h"

@class UNUserNotificationCenter;
@protocol AMSUserNotificationAuthorizationDelegate;

@interface AMSUserNotificationAuthorizationTask : AMSTask

@property (retain, nullable) UNUserNotificationCenter *notificationCenter;
@property (readonly) NSString *bundleIdentifier;
@property (weak) id <AMSUserNotificationAuthorizationDelegate> delegate;
@property (retain, nullable) AMSUserNotificationAuthorizationOptions *options;

+ (id)_findEngagementRequestInResponse:(id)response;
+ (id)engagementRequestForFullSheet;
+ (id)recordEngagementEventWithBundleIdentifier:(id)identifier options:(id)options;

- (id)_presentDialogForUserInitiatedWithCompletion;
- (id)_startEngagementAuthorizationWithResult:(id)result;
- (nonnull instancetype)initWithBundleIdentifier:(id)identifier options:(id)options;
- (id)requestAuthorization;

@end
