//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@interface AMSUnsignedInteger : NSObject

@property (readonly) unsigned long long value;

+ (id)unsignedIntegerWithUnsignedInteger:(unsigned long long)integer;

- (BOOL)isEqual:(nullable id)object;
- (nonnull instancetype)initWithUnsignedInteger:(unsigned long long)integer;
- (BOOL)isEqualToUnsignedInteger:(id)integer;

@end
