//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSRequestEncoding-Protocol.h"
#include "AMSResponseDecoding-Protocol.h"
#include "AMSURLDelegateProxy.h"
#include "AMSURLHandling-Protocol.h"
#include "AMSURLProtocolDelegate-Protocol.h"
#include "AMSURLSecurityPolicy.h"

@class NSURLSession, NSURLSessionConfiguration;

@interface AMSURLSession : NSObject <NSURLSessionDataDelegate, NSURLSessionTaskDelegate> {
	struct os_unfair_lock_s { unsigned int _os_unfair_lock_opaque; } _propertiesLock;
}

@property (retain, nullable) AMSURLDelegateProxy *delegateProxy;
@property BOOL invalidated;
@property BOOL useFallbackBag;
@property (retain, nullable) AMSURLSecurityPolicy *securityPolicy;
@property (readonly) NSURLSessionConfiguration *configuration;
@property (weak) id <NSURLSessionDelegate, AMSURLProtocolDelegate> delegate;
@property (readonly) NSOperationQueue *delegateQueue;
@property (retain, nullable) id <AMSURLHandling> protocolHandler;
@property (retain, nullable) id <AMSRequestEncoding> requestEncoder;
@property (retain, nullable) id <AMSResponseDecoding> responseDecoder;
@property (readonly) NSURLSession *session;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (BOOL)_shouldAttemptBagLoadForURL:(nullable NSURL *)url existingBag:(id)bag;
+ (id)loggingOnlySessionUsing:(id)_using;
+ (id)imageSession;
+ (id)sharedAuthKitSession;
+ (id)minimalSessionUsing:(id)_using;
+ (id)loggingOnlySession;
+ (id)minimalSession;
+ (id)defaultSession;
+ (id)_taskFromSession:(id)session request:(id)request activity:(id)activity;

- (void)URLSession:(nullable NSURL *)urlsession dataTask:(id)task didReceiveResponse:(id)response completionHandler:(UnknownBlock)handler;
- (nonnull instancetype)initWithConfiguration:(id)configuration;
- (void)_completeTaskWithTaskInfo:(id)info result:(id)result decodedObject:(id)object error:(nullable NSError *)error;
- (id)_retryTask:(id)task action:(id)action;
- (id)dataTaskPromiseWithRequest:(id)request;
- (BOOL)_protocolHandler:(id)handler canUseAlternateImplementationOfSelector:(SEL)selector;
- (id)dataTaskPromiseWithRequest:(id)request activity:(id)activity;
- (void)finishTasksAndInvalidate;
- (id)dataTaskPromiseWithRequestPromise:(id)promise;
- (nonnull instancetype)initWithConfiguration:(id)configuration delegate:(id)delegate delegateQueue:(id)queue;
- (void)URLSession:(nullable NSURL *)urlsession task:(id)task willPerformHTTPRedirection:(id)httpredirection newRequest:(id)request completionHandler:(UnknownBlock)handler;
- (void)URLSession:(nullable NSURL *)urlsession task:(id)task didReceiveChallenge:(id)challenge completionHandler:(UnknownBlock)handler;
- (id)dataTaskPromiseWithRequestPromise:(id)promise activity:(id)activity;
- (id)_formatError:(nullable NSError *)error task:(id)task decodedObject:(id)object;
- (void)URLSession:(nullable NSURL *)urlsession task:(id)task didCompleteWithError:(nullable NSError *)error;
- (void)URLSession:(nullable NSURL *)urlsession task:(id)task didFinishCollectingMetrics:(id)metrics;
- (id)_prepareRequest:(id)request logUUID:(id)uuid;
- (id)dataTaskWithRequest:(id)request;
- (void)createDataTaskWithRequest:(id)request activity:(id)activity dataTaskCreationCompletionHandler:(UnknownBlock)handler requestCompletionHandler:(UnknownBlock)handler;
- (nonnull instancetype)init;
- (id)dataTaskWithRequest:(id)request activity:(id)activity completionHandler:(UnknownBlock)handler;
- (void)createDataTaskWithRequest:(id)request signpostID:(unsigned long long)id activity:(id)activity dataTaskCreationCompletionHandler:(UnknownBlock)handler requestCompletionHandler:(UnknownBlock)handler;
- (void)URLSession:(nullable NSURL *)urlsession task:(id)task willPerformHTTPRedirection:(id)httpredirection newRequest:(id)request taskInfo:(id)info redirectCookieRemovalExclusionList:(id)list completionHandler:(UnknownBlock)handler;
- (void)URLSession:(nullable NSURL *)urlsession dataTask:(id)task didReceiveData:(id)data;
- (id)_handleURLAction:(nullable NSURL *)urlaction task:(id)task contiguousActionIdentifier:(unsigned long long)identifier;
- (id)dataTaskWithRequest:(id)request signpostID:(unsigned long long)id completionHandler:(UnknownBlock)handler;
- (id)dataTaskWithRequest:(id)request completionHandler:(UnknownBlock)handler;
- (id)_createSharedDataForTask:(id)task properties:(id)properties completionHandler:(UnknownBlock)handler;
- (id)dataTaskWithRequest:(id)request signpostID:(unsigned long long)id activity:(id)activity completionHandler:(UnknownBlock)handler;
- (id)_reconfigureNewRequest:(id)request originalTask:(id)task protocolHandler:(id)handler redirect:(BOOL)redirect;
- (void)dealloc;
- (void)invalidateAndCancel;

@end
