//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSBagConsumer-Protocol.h"
#include "AMSBagProtocol-Protocol.h"

@interface AMSURLParser : NSObject <AMSBagConsumer>

@property (retain, nullable) id <AMSBagProtocol> bag;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)createBagForSubProfile;
+ (id)bagSubProfileVersion;
+ (id)bagSubProfile;
+ (id)bagKeySet;

- (nonnull instancetype)initWithBagContract:(id)contract;
- (id)bagContract;
- (nonnull instancetype)initWithBag:(id)bag;
- (id)_commerceUIArrayForKey:(id)key;
- (id)_correctURL:(nullable NSURL *)url;
- (id)_defaultWebAllowedForURL:(nullable NSURL *)url;
- (id)_dynamicUIAllowedForURL:(nullable NSURL *)url;
- (id)_legacyWebAllowedForURL:(nullable NSURL *)url;
- (BOOL)_matchURL:(nullable NSURL *)url toPatterns:(id)patterns;
- (id)isCommerceUIURL:(id)uiurl;
- (id)typeForCommerceUIURL:(id)uiurl;
- (id)typeForURL:(nullable NSURL *)url;

@end
