//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSUserNotificationStrategy-Protocol.h"

@interface AMSUserNotificationCenter : NSObject

@property (readonly) id <AMSUserNotificationStrategy> strategy;

+ (Class)_determineStrategyForBundleId:(id)id;
+ (id)activeNotificationsWithCenterBundleId:(id)id;
+ (BOOL)badgeBundleId:(id)id badgeId:(id)id enabled:(BOOL)enabled error:(id *)error;
+ (id)postNotification:(id)notification bag:(id)bag centerBundleId:(id)id;
+ (id)removeNotification:(id)notification centerBundleId:(id)id;
+ (id)removeNotificationWithIdentifier:(id)identifier centerBundleId:(id)id logKey:(id)key scheduledOnly:(BOOL)only;


@end
