//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSURLSession.h"

@protocol AMSURLHandling <NSObject>

@required

@property (weak) AMSURLSession *session;

- (void)decodeMutableData:(id)data task:(id)task completionHandler:(UnknownBlock)handler;
- (void)handleResponse:(id)response task:(id)task completionHandler:(UnknownBlock)handler;
- (void)handleCompletionWithTask:(id)task metrics:(id)metrics decodedObject:(id)object completionHandler:(UnknownBlock)handler;
- (void)didCreateTask:(id)task fromRequest:(id)request completionHandler:(UnknownBlock)handler;
- (void)reconfigureNewRequest:(id)request originalTask:(id)task redirect:(BOOL)redirect completionHandler:(UnknownBlock)handler;

@optional

- (void)didCreateTask:(id)task fromRequest:(id)request error:(id *)error;
- (id)decodeData:(id)data task:(id)task error:(id *)error;
- (id)decodeMutableData:(id)data task:(id)task error:(id *)error;
- (void)reconfigureNewRequest:(id)request originalTask:(id)task redirect:(BOOL)redirect error:(id *)error;
- (id)handleResponse:(id)response task:(id)task;

@end
