//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSBagProtocol-Protocol.h"
#include "AMSKeychainOptions.h"
#include "AMSMetricsLoadURLOverlay.h"
#include "AMSProcessInfo.h"
#include "AMSPurchaseInfo.h"
#include "AMSResponseDecoding-Protocol.h"

@class ACAccount;

@interface AMSURLRequestProperties : NSObject <NSCopying>

@property (copy, nullable) ACAccount *account;
@property (retain, nullable) AMSMetricsLoadURLOverlay *loadURLOverlay;
@property long long anisetteType;
@property (retain, nullable) id <AMSBagProtocol> bag;
@property (copy, nullable) AMSProcessInfo *clientInfo;
@property long long dialogOptions;
@property BOOL disableBiometricsResponseHandling;
@property BOOL disableLoadURLMetrics;
@property BOOL disableResponseDecoding;
@property (copy, nullable) NSString *gsTokenIdentifier;
@property BOOL excludeIdentifierHeadersForAccount;
@property (copy, nullable) AMSKeychainOptions *keychainOptions;
@property BOOL knownToBeTrusted;
@property (copy, nullable) NSString *logUUID;
@property long long maxRetryCount;
@property long long mescalType;
@property (retain, nullable) AMSPurchaseInfo *purchaseInfo;
@property BOOL remoteSecuritySigningEnabled;
@property (retain, nullable) id <AMSResponseDecoding> responseDecoder;
@property long long reversePushType;
@property BOOL shouldSetCookiesFromResponse;
@property BOOL shouldSetStorefrontFromResponse;
@property (copy, nullable) NSDictionary *userInfo;
@property (retain, nullable) Class paymentSheetTaskClass;

- (nonnull instancetype)copyWithZone:(nullable struct _NSZone *)zone;
- (BOOL)isEqual:(nullable id)object;
- (unsigned long long)hash;
- (nonnull instancetype)init;

@end
