//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSMetricsEvent.h"

@interface AMSUserNotificationMetricsEvent : AMSMetricsEvent

@property (retain, nullable) NSString *displayScheduledTime;
@property (retain, nullable) NSString *errorDescription;
@property BOOL postedSuccessfully;

+ (id)_propertyValueClassesForKnownProperties;
+ (id)_centerForBundleId:(id)id;
+ (id)_stringFromInteruptionLevel:(unsigned long long)level;
+ (id)eventForBadgingForMetricsDictionary:(nullable NSDictionary *)dictionary bundleID:(id)id;
+ (id)eventForContentEngagementWithNotification:(id)notification;
+ (id)eventForPostedNotification:(id)notification;
+ (id)eventForSettingsChangedWithSettings:(id)settings bundleID:(id)id;
+ (id)eventForSettingsChangedWithSettings:(id)settings bundleID:(id)id account:(id)account;
+ (id)eventForVideoPlaybackForNotification:(id)notification;
+ (id)eventFromMetricsDictionary:(nullable NSDictionary *)dictionary centerBundleId:(id)id;
+ (id)eventFromNotificationCenterSettings:(id)settings centerBundleId:(id)id;

- (id)_stringFromNotificationSetting:(long long)setting;
- (id)_createDisplayCriteriaFromSettings:(id)settings;
- (nonnull instancetype)initWithTopic:(id)topic settings:(id)settings notificationSettingsForTopic:(id)topic centerBundleId:(id)id;

@end
