//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSMetricsLoadURLOverlay.h"
#include "AMSURLRequestProperties.h"

@class NSMutableURLRequest, NSURLRequest;

@interface AMSURLRequest : NSMutableURLRequest <NSCopying, NSMutableCopying>

@property (readonly, nonatomic) AMSURLRequestProperties *properties;
@property (readonly, nonatomic) NSURLRequest *urlRequest;
@property (retain, nullable) AMSMetricsLoadURLOverlay *loadURLOverlay;

+ (id)logableDescriptionForRequest:(id)request;

- (nonnull instancetype)initWithRequest:(id)request;
- (nonnull instancetype)initWithRequest:(id)request purchaseType:(long long)type buyParams:(id)params;
- (nonnull instancetype)initWithRequest:(id)request bag:(id)bag;
- (nonnull instancetype)copyWithZone:(nullable struct _NSZone *)zone;
- (nonnull instancetype)initWithRequest:(id)request properties:(id)properties;
- (nonnull instancetype)initWithURL:(nullable NSURL *)url cachePolicy:(unsigned long long)policy timeoutInterval:(double)interval;
- (id)mutableCopyWithZone:(struct _NSZone *)zone;
- (nonnull NSString *)description;
- (id)_initWithCFURLRequest:(struct _CFURLRequest *)cfurlrequest;

@end
