//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@interface AMSXDDevice : NSObject <NSSecureCoding>

@property (readonly) NSDictionary *JSONDictionary;
@property (readonly) NSString *identifier;
@property long long type;

+ (BOOL)supportsSecureCoding;
+ (id)deviceFromIdentifier:(id)identifier;
+ (id)allPairedDevices;
+ (id)activePairedDevices;

- (void)encodeWithCoder:(nullable NSCoder *)coder;
- (nonnull instancetype)initWithCoder:(nullable NSCoder *)coder;
- (nonnull instancetype)initWithJSONDictionary:(id)jsondictionary;
- (nonnull instancetype)initWithDeviceID:(id)id type:(long long)type;

@end
