//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@class PBCodable;

@interface AMSXDProtoMessage : PBCodable <NSCopying>

@property (retain, nonatomic, nullable) NSData *messageData;
@property (readonly, nonatomic) BOOL hasLogKey;
@property (retain, nonatomic, nullable) NSString *logKey;

- (nullable NSDictionary *)dictionaryRepresentation;
- (nonnull instancetype)copyWithZone:(nullable struct _NSZone *)zone;
- (void)copyTo:(id)to;
- (BOOL)isEqual:(nullable id)object;
- (BOOL)readFrom:(id)from;
- (unsigned long long)hash;
- (void)mergeFrom:(id)from;
- (void)writeTo:(id)to;
- (nonnull NSString *)description;

@end
