//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@interface NSArray (AppleMediaServices) <AMSHashable, AMSSecureCodingSanitizable>

+ (id)ams_arrayWithItem:(id)item count:(unsigned long long)count;
+ (void)ams_enumerateObjectsForArrays:(id)arrays usingBlock:(UnknownBlock)block;

- (id)ams_mapWithTransformIgnoresNil:(UnknownBlock)nil;
- (BOOL)ams_allWithOptions:(unsigned long long)options test:(UnknownBlock)test;
- (BOOL)ams_allWithTest:(UnknownBlock)test;
- (BOOL)ams_anyWithOptions:(unsigned long long)options test:(UnknownBlock)test;
- (BOOL)ams_anyWithTest:(UnknownBlock)test;
- (id)ams_arrayByRemovingObjectsFromArray:(id)array;
- (BOOL)ams_concurrentAllWithTest:(UnknownBlock)test;
- (BOOL)ams_concurrentAnyWithTest:(UnknownBlock)test;
- (id)ams_dictionaryUsingTransform:(UnknownBlock)transform;
- (id)ams_filterUsingTest:(UnknownBlock)test;
- (id)ams_firstObjectPassingTest:(UnknownBlock)test;
- (id)ams_invertedDictionaryUsingTransform:(UnknownBlock)transform;
- (id)ams_invertedDictionaryUsingTransformIgnoresNil:(UnknownBlock)nil;
- (id)ams_mapWithTransform:(UnknownBlock)transform;
- (id)ams_nonEmptyComponentsJoinedByString:(id)string;
- (id)ams_objectAtIndex:(long long)index;
- (id)ams_reduceWithInitialResult:(id)result updateAccumulatingResult:(UnknownBlock)result;
- (id)ams_sanitizedForSecureCoding;
- (id)hashedDescription;

@end
