//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@interface NSCoder (AppleMediaServices)

- (id)ams_decodeJSONDictionaryForKey:(id)key;
- (id)_ams_decodeJSONObjectForKey:(id)key error:(id *)error;
- (id)_ams_decodePropertyListObjectForKey:(id)key error:(id *)error;
- (BOOL)_ams_encodeJSONObject:(id)jsonobject forKey:(id)key error:(id *)error;
- (BOOL)_ams_encodePropertyListObject:(id)object forKey:(id)key format:(unsigned long long)format error:(id *)error;
- (id)ams_decodeBase64EncodedDataForKey:(id)key;
- (id)ams_decodeJSONArrayForKey:(id)key;
- (id)ams_decodePropertyListArrayForKey:(id)key;
- (id)ams_decodePropertyListDictionaryForKey:(id)key;
- (void)ams_encodeBase64EncodedData:(id)data forKey:(id)key;
- (void)ams_encodeJSONArray:(id)jsonarray forKey:(id)key;
- (void)ams_encodeJSONDictionary:(id)jsondictionary forKey:(id)key;
- (void)ams_encodePropertyListArray:(id)array format:(unsigned long long)format forKey:(id)key;
- (void)ams_encodePropertyListDictionary:(nullable NSDictionary *)dictionary format:(unsigned long long)format forKey:(id)key;

@end
