//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@interface NSDate (AppleMediaServices)

+ (id)ams_momentInUTCGregorianAtYear:(unsigned long long)year month:(unsigned long long)month day:(unsigned long long)day hour:(unsigned long long)hour minute:(unsigned long long)minute second:(unsigned long long)second;

@end
