//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@interface NSData (AMSFPDI)

+ (id)_AESKeyForDataProtectionClass:(unsigned long long)_class error:(id *)error;
+ (struct __CFString *)_accessibleAttributeForDataProtectionClass:(unsigned long long)_class;
+ (id)_generateInitializationVectorDataWithError:(id *)error;
+ (id)_labelForDataProtectionClass:(unsigned long long)_class;
+ (id)ams_createDataWithFPDIResult:(void *)fpdiresult length:(unsigned int)length;
+ (id)ams_generateEncryptionKey;

- (id)_decompressGZIP;
- (id)_decompressLZMA;
- (id)_compressGZIP;
- (id)_compressLZMA;
- (id)ams_SHA1;
- (id)ams_compressWithAlgorithm:(long long)algorithm;
- (id)ams_compressedData;
- (id)ams_decompressWithAlgorithm:(long long)algorithm;
- (id)ams_decompressedData;
- (id)ams_decryptUsingDataProtectionClass:(unsigned long long)_class initializationVectorData:(id)data tagData:(id)data error:(id *)error;
- (id)ams_decryptUsingKey:(id)key initializationVectorData:(id)data tagData:(id)data error:(id *)error;
- (struct { id x0; id x1; id x2; })ams_encryptDataUsingDataProtectionClass:(unsigned long long)_class error:(id *)error;
- (struct { id x0; id x1; id x2; })ams_encryptDataUsingKey:(id)key error:(id *)error;
- (id)ams_hexAddressDescription;
- (id)ams_nvramDescription;
- (id)ams_urlSafeBase64EncodedString;

@end
