//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@interface NSDictionary (AppleMediaServices_EncryptionResult) <AMSHashable, AMSSecureCodingSanitizable>

+ (id)ams_dictionaryWithEncryptionResult:(struct { id x0; id x1; id x2; })result;

- (id)ams_DSID;
- (id)ams_secureToken;
- (id)ams_accountFlags;
- (id)ams_altDSID;
- (id)ams_arrayUsingTransform:(UnknownBlock)transform;
- (id)ams_compactMapValues:(UnknownBlock)values;
- (id)ams_componentsJoinedByString:(id)string;
- (id)ams_creditsString;
- (id)ams_dictionaryByAddingEntriesFromDictionary:(nullable NSDictionary *)dictionary;
- (id)ams_dictionaryRemovingKeys:(id)keys;
- (struct { id x0; id x1; id x2; })ams_encryptionResult;
- (long long)ams_errorCode;
- (id)ams_filterUsingTest:(UnknownBlock)test;
- (id)ams_firstKeyObjectPassingTest:(UnknownBlock)test;
- (id)ams_firstKeyPassingTest:(UnknownBlock)test;
- (id)ams_firstName;
- (id)ams_firstObjectPassingTest:(UnknownBlock)test;
- (BOOL)ams_isManagedAppleID;
- (id)ams_keysForChangedValuesComparedToDictionary:(nullable NSDictionary *)dictionary;
- (id)ams_lastName;
- (id)ams_mapWithTransform:(UnknownBlock)transform;
- (id)ams_objectForCaseInsensitiveKey:(id)key;
- (id)ams_objectForKey:(id)key defaultValue:(id)value;
- (id)ams_privacyAcknowledgement;
- (id)ams_sanitizedForSecureCoding;
- (id)ams_username;
- (id)ams_valuesForKeys:(id)keys;
- (id)hashedDescription;

@end
