//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@interface NSError (AppleMediaServices) <AMSSecureCodingSanitizable>

- (id)_ams_firstUnderlyingErrorPassingTest:(UnknownBlock)test;
- (id)ams_errorByAddingToMultipleUnderlyingErrors:(nullable NSError *)errors;
- (id)ams_errorByAddingUnderlyingError:(nullable NSError *)error;
- (id)ams_errorByAddingUserInfo:(id)info;
- (id)ams_errorByCombiningWithUnderlyingError:(nullable NSError *)error;
- (id)ams_errorWithMultipleUnderlyingErrors:(nullable NSError *)errors;
- (id)ams_errorWithUnderlyingError:(nullable NSError *)error;
- (BOOL)ams_hasDomain:(id)domain;
- (BOOL)ams_hasDomain:(id)domain code:(unsigned long long)code;
- (BOOL)ams_isBagValueMissingError;
- (BOOL)ams_isTimeoutError;
- (BOOL)ams_isUserCancelledError;
- (id)ams_message;
- (id)ams_multipleUnderlyingErrors;
- (BOOL)ams_recursiveHasDomain:(id)domain code:(unsigned long long)code;
- (id)ams_sanitizedForSecureCoding;
- (id)ams_title;
- (id)ams_underlyingError;
- (id)ams_underlyingErrorWithDomain:(id)domain;
- (id)ams_underlyingErrorWithDomain:(id)domain code:(unsigned long long)code;

@end
