//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@interface NSHTTPCookie (AppleMediaServices) <NSSecureCoding, AMSHashable>

+ (BOOL)supportsSecureCoding;
+ (id)ams_cookieByMarkingCookieAsDeleted:(id)deleted;
+ (id)ams_cookiesByMergingProperties:(id)properties intoProperties:(id)properties;
+ (id)ams_cookiesForProperties:(id)properties;
+ (id)ams_propertiesForCookies:(id)cookies;
+ (id)ams_propertyXPCClasses;
+ (id)classesForPropertyCoding;

- (void)encodeWithCoder:(nullable NSCoder *)coder;
- (nonnull instancetype)initWithCoder:(nullable NSCoder *)coder;
- (BOOL)ams_matchesURL:(nullable NSURL *)url;
- (BOOL)_domainMatchesURL:(nullable NSURL *)url;
- (BOOL)_httpOnlyMatchesURL:(nullable NSURL *)url;
- (BOOL)_pathMatchesURL:(nullable NSURL *)url;
- (BOOL)_secureOnlyMatchesURL:(nullable NSURL *)url;
- (BOOL)ams_isCookieValidForBag;
- (BOOL)ams_isDeleted;
- (BOOL)ams_isEqualToCookie:(id)cookie;
- (BOOL)ams_isEquivalent:(id)equivalent;
- (BOOL)ams_isExpired;
- (BOOL)ams_shouldReplaceCookie:(id)cookie;
- (id)hashedDescription;

@end
