//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

#include "AMSBagConsumer-Protocol.h"

@interface NSHTTPURLResponse (AMSAnisette)

- (long long)_anisetteType;
- (id)ams_actionData;
- (id)ams_actionDataV1;
- (id)ams_actionDataV1_5;
- (id)ams_actionName;
- (id)ams_actionNameV1;
- (id)ams_actionNameV1_5;
- (id)ams_fsrAnonymousID;
- (id)ams_fsrCallbackUrl;
- (id)ams_fsrData;
- (id)ams_fsrInitUrl;
- (id)ams_fsrKeyID;
- (id)ams_fsrNameSpace;
- (id)ams_fsrRequestInterval;
- (id)ams_fsrTransactionID;
- (BOOL)ams_isFraudReportCallbackResponse;
- (BOOL)ams_isFraudReportInitURLResponse;
- (BOOL)ams_isFraudReportRetryResponse;

@end
