//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@interface NSMutableDictionary (AppleMediaServices)

- (void)ams_flatInsertValue:(id)value forKeyPath:(id)path;
- (void)ams_setValue:(id)value forKeyPath:(id)path shouldAppendToContainers:(BOOL)containers shouldFlatten:(BOOL)flatten;
- (void)ams_deleteValueForKeyPath:(id)path;
- (void)ams_insertValue:(id)value forKeyPath:(id)path;
- (void)ams_setNullableObject:(id)object forKey:(id)key;
- (void)ams_setValue:(id)value forKeyPath:(id)path;
- (void)ams_setValue:(id)value forKeyPathComponents:(id)components shouldAppendToContainers:(BOOL)containers shouldFlatten:(BOOL)flatten;

@end
