//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@interface NSSet (AppleMediaServices)

+ (id)ams_JSONClasses;
+ (id)ams_PLISTClasses;

- (id)ams_mapWithTransformIgnoresNil:(UnknownBlock)nil;
- (BOOL)ams_allWithTest:(UnknownBlock)test;
- (BOOL)ams_anyWithTest:(UnknownBlock)test;
- (id)ams_filterUsingTest:(UnknownBlock)test;
- (id)ams_firstObjectPassingTest:(UnknownBlock)test;
- (id)ams_mapWithTransform:(UnknownBlock)transform;
- (id)ams_nonEmptyComponentsJoinedByString:(id)string;

@end
