//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@interface NSString (AppleMediaServices)

+ (id)_replaceBreakingSpaceMarkupForMutableAttributedString:(id)string;
+ (id)_replaceMarkupForMutableAttributedString:(id)string markupType:(long long)type;

- (BOOL)ams_caseInsensitiveEquals:(id)equals;
- (id)ams_dataFromPaddedBase64URLEncodedString;
- (void)ams_enumerateRangesOfString:(id)string options:(unsigned long long)options usingBlock:(UnknownBlock)block;
- (BOOL)ams_isPercentEncodedForAllowedCharacters:(id)characters;
- (BOOL)ams_matchesRegex:(id)regex;
- (id)ams_padForBase64EncodedString;
- (id)ams_replaceAccountPatternWithUsername:(id)username;
- (id)ams_replacingMarkupUsingAccount:(id)account shouldUppercase:(BOOL)uppercase;
- (id)ams_sha256HashStringUsingEncoding:(unsigned long long)encoding error:(id *)error;
- (id)ams_sha512HashStringUsingEncoding:(unsigned long long)encoding error:(id *)error;
- (id)ams_splitKeyPathStringKeepingEnclosedParts;
- (id)ams_stringByRemovingCharactersInSet:(id)set;

@end
