//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@interface NSURL (AppleMediaServices)

+ (BOOL)_isAppendWithUnmodifiedParametersFeatureFlagEnabled;
+ (id)ams_cachesDirectory;
+ (id)ams_dataVaultDirectory;
+ (id)ams_dynamicUIDirectory;
+ (id)ams_engagementDirectory;
+ (id)ams_paymentSheetsUIDirectory;
+ (id)ams_realHomeDirectory;
+ (id)ams_unescapedStringForString:(id)string;

- (id)ams_URLQueryAllowedCharacterSet;
- (id)ams_URLBySortingQueryParameters;
- (id)_sortedQueryItemsFromQueryItems:(id)items;
- (id)ams_URLByAppendingQueryItems:(id)items preservingQueryEncoding:(BOOL)encoding;
- (id)ams_URLByAppendingQueryParameter:(id)parameter name:(id)name;
- (id)ams_URLByAppendingQueryParameters:(id)parameters;
- (id)ams_URLByAppendingQueryParameters:(id)parameters preservingQueryEncoding:(BOOL)encoding;
- (id)ams_URLByDeletingTrailingSlash;
- (id)ams_URLByReplaceingQueryParameters:(id)parameters;
- (id)ams_URLByReplacingQueryItems:(id)items withEncodedParameters:(BOOL)parameters;
- (id)ams_URLByReplacingQueryParameters:(id)parameters;
- (id)ams_URLByReplacingQueryParameters:(id)parameters withEncodedParameters:(BOOL)parameters;
- (id)ams_URLByReplacingSchemeWithScheme:(id)scheme;
- (id)ams_appendingQueryParameters:(id)parameters;
- (BOOL)ams_isBagLoadURL;
- (BOOL)ams_isHTTP;
- (BOOL)ams_isSecure;
- (id)ams_parameters;
- (id)ams_schemeSwizzledURL;
- (id)ams_unmodifiedParameters;

@end
