//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@interface NSURLSessionConfiguration (AppleMediaServices_Project)

+ (id)ams_configurationWithClientInfo:(id)info bag:(id)bag;
+ (id)ams_configurationWithProcessInfo:(id)info bag:(id)bag;
+ (id)ams_imageConfiguration;

- (void)ams_configureWithClientInfo:(id)info;
- (id)ams_configureWithClientInfo:(id)info bag:(id)bag;
- (void)ams_configureWithProcessInfo:(id)info bag:(id)bag;

@end
