//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@protocol PKPaymentAuthorizationControllerPrivateDelegate <NSObject>

@required

@optional

- (void)paymentAuthorizationController:(id)controller didAuthorizePurchase:(id)purchase completion:(UnknownBlock)completion;
- (void)paymentAuthorizationController:(id)controller didAuthorizeApplePayTrustSignature:(id)signature handler:(UnknownBlock)handler;
- (void)paymentAuthorizationController:(id)controller didAuthorizeContextWithHandler:(UnknownBlock)handler;
- (void)paymentAuthorizationController:(id)controller didAuthorizePeerPaymentQuote:(id)quote handler:(UnknownBlock)handler;
- (void)paymentAuthorizationController:(id)controller didEncounterAuthorizationEvent:(unsigned long long)event;
- (void)paymentAuthorizationController:(id)controller didRequestMerchantSession:(UnknownBlock)session;
- (void)paymentAuthorizationController:(id)controller didRequestMerchantSessionWithURL:(nullable NSURL *)url merchantSessionUpdate:(UnknownBlock)update;
- (void)paymentAuthorizationController:(id)controller didUpdateAccountServicePaymentMethod:(id)method handler:(UnknownBlock)handler;
- (void)paymentAuthorizationController:(id)controller willFinishWithError:(nullable NSError *)error;
- (id)presentationSceneBundleIdentifierForPaymentAuthorizationController:(id)controller;
- (id)presentationSceneIdentifierForPaymentAuthorizationController:(id)controller;

@end
