//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.682, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 9.5.8.1.1
//

@protocol PKPaymentAuthorizationControllerDelegate <NSObject>

@required

- (void)paymentAuthorizationControllerDidFinish:(id)finish;
- (id)presentationWindowForPaymentAuthorizationController:(id)controller;

@optional

- (void)paymentAuthorizationController:(id)controller didRequestMerchantSessionUpdate:(UnknownBlock)update;
- (void)paymentAuthorizationController:(id)controller didSelectShippingMethod:(id)method handler:(UnknownBlock)handler;
- (void)paymentAuthorizationController:(id)controller didAuthorizePayment:(id)payment completion:(UnknownBlock)completion;
- (void)paymentAuthorizationController:(id)controller didAuthorizePayment:(id)payment handler:(UnknownBlock)handler;
- (void)paymentAuthorizationController:(id)controller didChangeCouponCode:(id)code handler:(UnknownBlock)handler;
- (void)paymentAuthorizationController:(id)controller didSelectPaymentMethod:(id)method completion:(UnknownBlock)completion;
- (void)paymentAuthorizationController:(id)controller didSelectPaymentMethod:(id)method handler:(UnknownBlock)handler;
- (void)paymentAuthorizationController:(id)controller didSelectShippingContact:(id)contact completion:(UnknownBlock)completion;
- (void)paymentAuthorizationController:(id)controller didSelectShippingContact:(id)contact handler:(UnknownBlock)handler;
- (void)paymentAuthorizationController:(id)controller didSelectShippingMethod:(id)method completion:(UnknownBlock)completion;
- (void)paymentAuthorizationControllerWillAuthorizePayment:(id)payment;

@end
